# Practical exercise 1: Data Types

## String operations (special characters, concatenation)

In [1]:
# Run the following code: 

my_string = 'Don\'t mess with' + " lfrit"
print(my_string)

Don't mess with lfrit

In [11]:
# Re-enter the first line of code (In [1]), after removing the \, and check the output. 
# Now, try to assign the string value in In [1] using double quotes, and check the output. How has the behaviour changed? 
my_string = "Don't mess with" + " lfrit"
print(my_string)

Don't mess with lfrit

## Operations on incompatible types

In [12]:
a = 1 # define a variable 'a'
type(a) # return the type of 'a', the last line of cells will be printed even if without calling print() function

int

In [13]:
b = 2
print(type(b))
print(a + b) # you can add two numbers

<class 'int'>
3

In [14]:
c = 'two'
print(type(c))
print(a + c) # you will get a 'TypeError' since adding a number and a string is not supported in Python

<class 'str'>

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [15]:
d = "five"
c + d # this line will be executed correctly, since both c and d are strings. The '+' here will concatenate two strings together.

'twofive'

In [16]:
c + " " + d + " twelve" # variable c, [space], variable d, [space]twelve will be concatenated together.

'two five twelve'

# Practical exercise 2: Retrieving Data 
“Predicting the age of abalone from physical measurements. The age of abalone is 
determined by cutting the shell through the cone, staining it, and counting the number of 
rings through a microscope -- a boring and time-consuming task. Other measurements, 
which are easier to obtain, are used to predict the age. Further information, such as weather 
patterns and location (hence food availability) may be required to solve the problem.”

In [22]:
import pandas as pd # import pandas package and define a nickname 'pd' for convenience

In [23]:
# Load a csv file from the web (you can use either the following ‘online’ or ‘offline’ method to load the data) 

# online
abalone_p = "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"

# Read a comma-separated values (csv) file from a URL into DataFrame.
# Please understand how read_csv() works via:
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv
abalone = pd.read_csv(abalone_p, sep=',', decimal='.', header=None, 
                      names=['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 
                             'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings'])
abalone

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [27]:
# offline
# 1. Download the abalone dataset from Canvas → Modules → Week 3
# 2. Move the file to your home directory next to your jupyter notebook 
abalone_p = 'abalone.data.csv'

# Read a local comma-separated values (csv) file into DataFrame.
# Please understand how read_csv() works via:
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv
abalone = pd.read_csv(abalone_p, sep=',', decimal='.', header=None, 
                      names=['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 
                             'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings'])
abalone

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

## Check the types of loaded columns

In [28]:
# Return the dtypes (Data Types) in the DataFrame.
# Please understand 'dtypes' via:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html
abalone.dtypes

Sex                object
Length            float64
Diameter          float64
Height            float64
Whole weight      float64
Shucked weight    float64
Viscera weight    float64
Shell weight      float64
Rings               int64
dtype: object

## Print the first n rows

In [29]:
# Return the first n rows.
# Please understand how head() works via:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html

abalone.head(2)

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.15,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.07,7

## Get the names of columns

In [30]:
# The column labels of the DataFrame.
abalone.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

## Extract n columns

In [31]:
# Extract the column named 'Rings', return a Series Object, of which the first column is "Index", 
# the second column is values of the corresponding column 'Rings'
y = abalone['Rings'] 
y

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

In [32]:
# Extract multiple columns ['Sex', 'Diameter'] at once, return a DataFrame Object, 
# of which the first column is "Index" as well.

X = abalone[['Sex', 'Diameter']]
X

     Sex  Diameter
0      M     0.365
1      M     0.265
2      F     0.420
3      M     0.365
4      I     0.255
...   ..       ...
4172   F     0.450
4173   M     0.440
4174   M     0.475
4175   F     0.485
4176   M     0.555

[4177 rows x 2 columns]

## Size of the dataset (X, y)

In [ ]:
y.shape # Return a tuple of the shape of the underlying data.

(4177,)

In [18]:
X.shape # Return a tuple representing the dimensionality of the DataFrame.

(4177, 2)

## Generate frequency table for Rings values

In [19]:
# Return a Series containing counts of unique values.
# Please understand value_counts() of Series via:
# https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html

y.value_counts()

9     689
10    634
8     568
11    487
7     391
12    267
6     259
13    203
14    126
5     115
15    103
16     67
17     58
4      57
18     42
19     32
20     26
3      15
21     14
23      9
22      6
24      2
27      2
1       1
25      1
2       1
26      1
29      1
Name: Rings, dtype: int64

## Create a DataFrame by customized data

In [20]:
# Create two-dimensional, size-mutable, potentially heterogeneous tabular data by yourself.
# Please understand how pd.DataFrame works via:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

# {'key1': [], 'key2': [], ...} is a dictionary in Python
df1 = pd.DataFrame({'name': ['Jason', 'Lucy', 'Helen'], 'height': [180, 170, 165], 'weight': [75, 65, 72]}) 
df1

    name  height  weight
0  Jason     180      75
1   Lucy     170      65
2  Helen     165      72

In [21]:
df2 = pd.DataFrame({'name': ['Jason', 'Lucy', 'Helen'], 'mathematics': [80, 90, 65], 'science': [75, 65, 72]})
df2

    name  mathematics  science
0  Jason           80       75
1   Lucy           90       65
2  Helen           65       72

In [22]:
df3 = pd.DataFrame({'name': ['Jason', 'Lucy', 'Helen'], 'company': ['RMIT', 'RMIT', 'RMIT'], 'salary': [100000, '120,000', '110,000']})
df3

    name company   salary
0  Jason    RMIT   100000
1   Lucy    RMIT  120,000
2  Helen    RMIT  110,000

In [23]:
df4 = pd.DataFrame({'name': ['Jason', 'Lucy', 'Helen'], '# of attendance': [22, 22, 15]})
df4

    name  # of attendance
0  Jason               22
1   Lucy               22
2  Helen               15

## Merge different DataFrames by 'name'

In [24]:
# Merge DataFrame or named Series objects with a database-style join.
# Please understand how merge() function works via:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html#pandas.DataFrame.merge

merged_df = df1.merge(df2, on='name', how='inner')
merged_df = merged_df.merge(df3, on='name', how='inner')
merged_df = merged_df.merge(df4, on='name', how='inner')
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15

In [25]:
# Use Method Chain

merged_df = df1.merge(df2, on='name', how='inner').merge(df3, on='name', how='inner').merge(df4, on='name', how='inner')
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15

In [26]:
# Use For loop

all_df = [df2, df3, df4]
merged_df = df1
for df in all_df:
    merged_df = merged_df.merge(df, on='name', how='inner')
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15

# Practical Exercise 3: Data Preparation

## Copy the Abalone dataset

In [27]:
# Make a copy of this object’s indices and data.
# Please understand the copy() function via:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html

fake_abalone = abalone.copy()
fake_abalone

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

## Add redundant whitespaces

In [28]:
# Access a group of rows and columns by label(s) or a boolean array.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html

fake_abalone.loc[fake_abalone.Rings.isin([1, 2, 3]), 'Sex'] = 'I '
fake_abalone['Sex'].value_counts()

M     1525
I     1328
F     1307
I       17
Name: Sex, dtype: int64

## Remove redundant whitespaces

In [29]:
# Remove leading and trailing characters.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.strip.html

fake_abalone['Sex'] = fake_abalone['Sex'].str.strip()
fake_abalone['Sex'].value_counts()

M    1525
I    1345
F    1307
Name: Sex, dtype: int64

## Replace ‘I’ (Infant) labels with ‘K’ (Kid)

In [30]:
# Replace values given in to_replace with value.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.Series.replace.html

fake_abalone['Sex'].replace('I', 'K', inplace=True) 
fake_abalone

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,K,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

## Inject NaN (Not a Number) data

In [31]:
print(fake_abalone[['Diameter', 'Rings']][fake_abalone.Rings == 22])

# Inject NaN data to the column 'Diameter' when fake_abalone.Rings == 22
fake_abalone.loc[fake_abalone.Rings == 22, 'Diameter'] = float('NaN') 

print(fake_abalone[['Diameter', 'Rings']][fake_abalone.Rings == 22])

     Diameter  Rings
232     0.505     22
270     0.525     22
275     0.540     22
351     0.450     22
433     0.420     22
675     0.395     22
     Diameter  Rings
232       NaN     22
270       NaN     22
275       NaN     22
351       NaN     22
433       NaN     22
675       NaN     22

## Drop missing data

In [32]:
# Remove missing values.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

fake_abalone = fake_abalone.dropna()
print(fake_abalone[['Diameter', 'Rings']][fake_abalone.Rings == 22])

Empty DataFrame
Columns: [Diameter, Rings]
Index: []

## Inject again

In [33]:
fake_abalone = abalone.copy()

print(fake_abalone[['Diameter', 'Rings']][fake_abalone.Rings == 22])
fake_abalone.loc[fake_abalone.Rings == 22, 'Diameter'] = float('NaN')
print(fake_abalone[['Diameter', 'Rings']][fake_abalone.Rings == 22])

     Diameter  Rings
232     0.505     22
270     0.525     22
275     0.540     22
351     0.450     22
433     0.420     22
675     0.395     22
     Diameter  Rings
232       NaN     22
270       NaN     22
275       NaN     22
351       NaN     22
433       NaN     22
675       NaN     22

## Replace missing data with more meaningful values (negative constant, mean and median)

In [34]:
# Fill NA/NaN values using the specified method.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html

# pandas.Series.mean: Return the mean of the values over the requested axis.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.Series.mean.html

fake_abalone['Diameter'].fillna(fake_abalone['Diameter'].mean(axis=0), inplace=True)
fake_abalone[['Diameter', 'Rings']][fake_abalone.Rings == 22]

     Diameter  Rings
232  0.407788     22
270  0.407788     22
275  0.407788     22
351  0.407788     22
433  0.407788     22
675  0.407788     22

## Add new observation to merged_df

In [35]:
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15

In [36]:
# A part of Helen's attendance is recorded into another dataset, which needs to be added to merged_df
# Please refer to the doc of append() method: 
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html

merged_df = merged_df.append({'name': 'Helen', 'height': 165, 'weight': 72, 'mathematics': 65, 
                              'science': 72, 'company': 'RMIT', 
                              'salary': '110,000', '# of attendance': 6}, ignore_index=True)
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15
3,Helen,165,72,65,72,RMIT,"110,000",6

## The rows with index 2 and 3 are recorded separately for the same staff, which needs to merge to one row.

In [37]:
# groupby(): Group DataFrame using a mapper or by a Series of columns.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

# transform(): Call function producing a like-indexed Series on each group and return a Series 
# having the same indexes as the original object filled with the transformed values.
# Please refer to: 
# https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.SeriesGroupBy.transform.html

merged_df['# of attendance'] = merged_df.groupby(['name', 'height', 'weight', 'mathematics', 'science', 
                                                  'company', 'salary'])['# of attendance'].transform('sum') # use the return values of sum() function as the transformed values
merged_df['# of attendance']

0    22
1    22
2    21
3    21
Name: # of attendance, dtype: int64

## Remove duplicates

In [38]:
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",21
3,Helen,165,72,65,72,RMIT,"110,000",21

In [39]:
# Return DataFrame with duplicate rows removed.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html

merged_df = merged_df.drop_duplicates(subset=['name', 'height', 'weight', 'mathematics', 'science', 
                                              'company', 'salary']).reset_index(drop=True)
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",21

## Transfer 'salary' to numbers

In [40]:
# Use astype to transform data type
# astype(): Cast a pandas object to a specified dtype dtype.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.Series.astype.html

# str.replace(): Replace each occurrence of pattern/regex in the Series/Index.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html

merged_df['salary'] = merged_df['salary'].astype('str').str.replace(',', '').astype('int')
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,120000,22
2,Helen,165,72,65,72,RMIT,110000,21

In [41]:
# Or use pd.to_numeric
# Convert argument to a numeric type.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html

merged_df['salary'] = pd.to_numeric(merged_df['salary'].astype('str').str.replace(',', ''))
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,120000,22
2,Helen,165,72,65,72,RMIT,110000,21

# Advanced Exercise: Dealing with big datasets 
Please don’t try this exercise until you are done with all the previous. ;-)

## Re-load the abalone file from the web

In [42]:
abalone_p = "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"

In [43]:
'''
Load the dataset in chunks of the same size; each chunk is a piece of the dataset that contains all 
the columns and the number of lines set in the function call (the chunksize parameter). 
'''

abalone_chunks = pd.read_csv(abalone_p, sep=',', decimal='.', header=None, 
                             names=['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 
                                    'Shucked weight', 'Viscera weight', 'Shell weight',  'Rings'],  
                             chunksize=10)

In [44]:
'''
Note that the output of the read_csv function in this case is not a pandas DataFrame but an 
iterator-like object. In fact, to get the results, you need to iterate that object. 
'''

for chunk in abalone_chunks:
    print(chunk.shape)
    print(chunk)

(10, 9)
  Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395
5   I   0.425     0.300   0.095        0.3515          0.1410          0.0775
6   F   0.530     0.415   0.150        0.7775          0.2370          0.1415
7   F   0.545     0.425   0.125        0.7680          0.2940          0.1495
8   M   0.475     0.370   0.125        0.5095          0.2165          0.1125
9   F   0.550     0.440   0.150        0.8945          0.3145          0.1510

   Shell weight  Rings
0         0.150     15
1         0.070      7
2         0.210      9
3         0.155     10
4         0.055      7
5         0.120      8
6         0.330     20
7         0.260     16
8         0.165      9
9         0.320     19
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
10   F   0.525     0.380   0.140        0.6065          0.1940
11   M   0.430     0.350   0.110        0.4060          0.1675
12   M   0.490     0.380   0.135        0.5415          0.2175
13   F   0.535     0.405   0.145        0.6845          0.2725
14   F   0.470     0.355   0.100        0.4755          0.1675
15   M   0.500     0.400   0.130        0.6645          0.2580
16   I   0.355     0.280   0.085        0.2905          0.0950
17   F   0.440     0.340   0.100        0.4510          0.1880
18   M   0.365     0.295   0.080        0.2555          0.0970
19   M   0.450     0.320   0.100        0.3810          0.1705

    Viscera weight  Shell weight  Rings
10          0.1475         0.210     14
11          0.0810         0.135     10
12          0.0950         0.190     11
13          0.1710         0.205     10
14          0.0805         0.185     10
15          0.1330         0.240     12
16          0.0395         0.115      7
17          0.0870         0.130     10
18          0.0430         0.100      7
19          0.0750         0.115      9
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
20   M   0.355     0.280   0.095        0.2455          0.0955
21   I   0.380     0.275   0.100        0.2255          0.0800
22   F   0.565     0.440   0.155        0.9395          0.4275
23   F   0.550     0.415   0.135        0.7635          0.3180
24   F   0.615     0.480   0.165        1.1615          0.5130
25   F   0.560     0.440   0.140        0.9285          0.3825
26   F   0.580     0.450   0.185        0.9955          0.3945
27   M   0.590     0.445   0.140        0.9310          0.3560
28   M   0.605     0.475   0.180        0.9365          0.3940
29   M   0.575     0.425   0.140        0.8635          0.3930

    Viscera weight  Shell weight  Rings
20           0.062         0.075     11
21           0.049         0.085     10
22           0.214         0.270     12
23           0.210         0.200      9
24           0.301         0.305     10
25           0.188         0.300     11
26           0.272         0.285     11
27           0.234         0.280     12
28           0.219         0.295     15
29           0.227         0.200     11
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
30   M   0.580     0.470   0.165        0.9975          0.3935
31   F   0.680     0.560   0.165        1.6390          0.6055
32   M   0.665     0.525   0.165        1.3380          0.5515
33   F   0.680     0.550   0.175        1.7980          0.8150
34   F   0.705     0.550   0.200        1.7095          0.6330
35   M   0.465     0.355   0.105        0.4795          0.2270
36   F   0.540     0.475   0.155        1.2170          0.5305
37   F   0.450     0.355   0.105        0.5225          0.2370
38   F   0.575     0.445   0.135        0.8830          0.3810
39   M   0.355     0.290   0.090        0.3275          0.1340

    Viscera weight  Shell weight  Rings
30          0.2420         0.330     10
31          0.2805         0.460     15
32          0.3575         0.350     18
33          0.3925         0.455     19
34          0.4115         0.490     13
35          0.1240         0.125      8
36          0.3075         0.340     16
37          0.1165         0.145      8
38          0.2035         0.260     11
39          0.0860         0.090      9
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
40   F   0.450     0.335   0.105        0.4250          0.1865
41   F   0.550     0.425   0.135        0.8515          0.3620
42   I   0.240     0.175   0.045        0.0700          0.0315
43   I   0.205     0.150   0.055        0.0420          0.0255
44   I   0.210     0.150   0.050        0.0420          0.0175
45   I   0.390     0.295   0.095        0.2030          0.0875
46   M   0.470     0.370   0.120        0.5795          0.2930
47   F   0.460     0.375   0.120        0.4605          0.1775
48   I   0.325     0.245   0.070        0.1610          0.0755
49   F   0.525     0.425   0.160        0.8355          0.3545

    Viscera weight  Shell weight  Rings
40          0.0910         0.115      9
41          0.1960         0.270     14
42          0.0235         0.020      5
43          0.0150         0.012      5
44          0.0125         0.015      4
45          0.0450         0.075      7
46          0.2270         0.140      9
47          0.1100         0.150      7
48          0.0255         0.045      6
49          0.2135         0.245      9
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
50   I   0.520     0.410   0.120        0.5950          0.2385
51   M   0.400     0.320   0.095        0.3030          0.1335
52   M   0.485     0.360   0.130        0.5415          0.2595
53   F   0.470     0.360   0.120        0.4775          0.2105
54   M   0.405     0.310   0.100        0.3850          0.1730
55   F   0.500     0.400   0.140        0.6615          0.2565
56   M   0.445     0.350   0.120        0.4425          0.1920
57   M   0.470     0.385   0.135        0.5895          0.2765
58   I   0.245     0.190   0.060        0.0860          0.0420
59   F   0.505     0.400   0.125        0.5830          0.2460

    Viscera weight  Shell weight  Rings
50          0.1110         0.190      8
51          0.0600         0.100      7
52          0.0960         0.160     10
53          0.1055         0.150     10
54          0.0915         0.110      7
55          0.1755         0.220      8
56          0.0955         0.135      8
57          0.1200         0.170      8
58          0.0140         0.025      4
59          0.1300         0.175      7
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
60   M   0.450     0.345   0.105        0.4115          0.1800
61   M   0.505     0.405   0.110        0.6250          0.3050
62   F   0.530     0.410   0.130        0.6965          0.3020
63   M   0.425     0.325   0.095        0.3785          0.1705
64   M   0.520     0.400   0.120        0.5800          0.2340
65   M   0.475     0.355   0.120        0.4800          0.2340
66   F   0.565     0.440   0.160        0.9150          0.3540
67   F   0.595     0.495   0.185        1.2850          0.4160
68   F   0.475     0.390   0.120        0.5305          0.2135
69   I   0.310     0.235   0.070        0.1510          0.0630

    Viscera weight  Shell weight  Rings
60          0.1125         0.135      7
61          0.1600         0.175      9
62          0.1935         0.200     10
63          0.0800         0.100      7
64          0.1315         0.185      8
65          0.1015         0.135      8
66          0.1935         0.320     12
67          0.2240         0.485     13
68          0.1155         0.170     10
69          0.0405         0.045      6
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
70   M   0.555     0.425   0.130        0.7665          0.2640
71   F   0.400     0.320   0.110        0.3530          0.1405
72   F   0.595     0.475   0.170        1.2470          0.4800
73   M   0.570     0.480   0.175        1.1850          0.4740
74   F   0.605     0.450   0.195        1.0980          0.4810
75   F   0.600     0.475   0.150        1.0075          0.4425
76   M   0.595     0.475   0.140        0.9440          0.3625
77   F   0.600     0.470   0.150        0.9220          0.3630
78   F   0.555     0.425   0.140        0.7880          0.2820
79   F   0.615     0.475   0.170        1.1025          0.4695

    Viscera weight  Shell weight  Rings
70          0.1680         0.275     13
71          0.0985         0.100      8
72          0.2250         0.425     20
73          0.2610         0.380     11
74          0.2895         0.315     13
75          0.2210         0.280     15
76          0.1890         0.315      9
77          0.1940         0.305     10
78          0.1595         0.285     11
79          0.2355         0.345     14
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
80   F   0.575     0.445   0.140        0.9410          0.3845
81   M   0.620     0.510   0.175        1.6150          0.5105
82   F   0.520     0.425   0.165        0.9885          0.3960
83   M   0.595     0.475   0.160        1.3175          0.4080
84   M   0.580     0.450   0.140        1.0130          0.3800
85   F   0.570     0.465   0.180        1.2950          0.3390
86   M   0.625     0.465   0.140        1.1950          0.4825
87   M   0.560     0.440   0.160        0.8645          0.3305
88   F   0.460     0.355   0.130        0.5170          0.2205
89   F   0.575     0.450   0.160        0.9775          0.3135

    Viscera weight  Shell weight  Rings
80          0.2520         0.285      9
81          0.1920         0.675     12
82          0.2250         0.320     16
83          0.2340         0.580     21
84          0.2160         0.360     14
85          0.2225         0.440     12
86          0.2050         0.400     13
87          0.2075         0.260     10
88          0.1140         0.165      9
89          0.2310         0.330     12
(10, 9)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
90   M   0.565     0.425   0.135        0.8115          0.3410
91   M   0.555     0.440   0.150        0.7550          0.3070
92   M   0.595     0.465   0.175        1.1150          0.4015
93   F   0.625     0.495   0.165        1.2620          0.5070
94   M   0.695     0.560   0.190        1.4940          0.5880
95   M   0.665     0.535   0.195        1.6060          0.5755
96   M   0.535     0.435   0.150        0.7250          0.2690
97   M   0.470     0.375   0.130        0.5230          0.2140
98   M   0.470     0.370   0.130        0.5225          0.2010
99   F   0.475     0.375   0.125        0.5785          0.2775

    Viscera weight  Shell weight  Rings
90          0.1675         0.255     15
91          0.1525         0.260     12
92          0.2540         0.390     13
93          0.3180         0.390     10
94          0.3425         0.485     15
95          0.3880         0.480     14
96          0.1385         0.250      9
97          0.1320         0.145      8
98          0.1330         0.165      7
99          0.0850         0.155     10
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
100   I   0.360     0.265   0.095        0.2315          0.1050
101   M   0.550     0.435   0.145        0.8430          0.3280
102   M   0.530     0.435   0.160        0.8830          0.3160
103   M   0.530     0.415   0.140        0.7240          0.3105
104   M   0.605     0.470   0.160        1.1735          0.4975
105   F   0.520     0.410   0.155        0.7270          0.2910
106   F   0.545     0.430   0.165        0.8020          0.2935
107   F   0.500     0.400   0.125        0.6675          0.2610
108   F   0.510     0.390   0.135        0.6335          0.2310
109   F   0.435     0.395   0.105        0.3635          0.1360

     Viscera weight  Shell weight  Rings
100          0.0460         0.075      7
101          0.1915         0.255     15
102          0.1640         0.335     15
103          0.1675         0.205     10
104          0.2405         0.345     12
105          0.1835         0.235     12
106          0.1830         0.280     11
107          0.1315         0.220     10
108          0.1790         0.200      9
109          0.0980         0.130      9
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
110   M   0.495     0.395   0.125        0.5415          0.2375
111   M   0.465     0.360   0.105        0.4310          0.1720
112   I   0.435     0.320   0.080        0.3325          0.1485
113   M   0.425     0.350   0.105        0.3930          0.1300
114   F   0.545     0.410   0.125        0.6935          0.2975
115   F   0.530     0.415   0.115        0.5915          0.2330
116   F   0.490     0.375   0.135        0.6125          0.2555
117   M   0.440     0.340   0.105        0.4020          0.1305
118   F   0.560     0.430   0.150        0.8825          0.3465
119   M   0.405     0.305   0.085        0.2605          0.1145

     Viscera weight  Shell weight  Rings
110          0.1345         0.155      9
111          0.1070         0.175      9
112          0.0635         0.105      9
113          0.0630         0.165      9
114          0.1460         0.210     11
115          0.1585         0.180     11
116          0.1020         0.220     11
117          0.0955         0.165     10
118          0.1720         0.310      9
119          0.0595         0.085      8
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
120   F   0.470     0.365   0.105        0.4205          0.1630
121   I   0.385     0.295   0.085        0.2535          0.1030
122   F   0.515     0.425   0.140        0.7660          0.3040
123   M   0.370     0.265   0.075        0.2140          0.0900
124   I   0.360     0.280   0.080        0.1755          0.0810
125   I   0.270     0.195   0.060        0.0730          0.0285
126   I   0.375     0.275   0.090        0.2380          0.1075
127   I   0.385     0.290   0.085        0.2505          0.1120
128   M   0.700     0.535   0.160        1.7255          0.6300
129   M   0.710     0.540   0.165        1.9590          0.7665

     Viscera weight  Shell weight  Rings
120          0.1035         0.140      9
121          0.0575         0.085      7
122          0.1725         0.255     14
123          0.0510         0.070      6
124          0.0505         0.070      6
125          0.0235         0.030      5
126          0.0545         0.070      6
127          0.0610         0.080      8
128          0.2635         0.540     19
129          0.2610         0.780     18
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
130   M   0.595     0.480   0.165        1.2620          0.4835
131   F   0.440     0.350   0.125        0.4035          0.1750
132   F   0.325     0.260   0.090        0.1915          0.0850
133   I   0.350     0.260   0.095        0.2110          0.0860
134   I   0.265     0.200   0.065        0.0975          0.0400
135   F   0.425     0.330   0.115        0.4060          0.1635
136   F   0.305     0.230   0.080        0.1560          0.0675
137   M   0.345     0.255   0.090        0.2005          0.0940
138   F   0.405     0.325   0.110        0.3555          0.1510
139   M   0.375     0.285   0.095        0.2530          0.0960

     Viscera weight  Shell weight  Rings
130          0.2830        0.4100     17
131          0.0630        0.1290      9
132          0.0360        0.0620      7
133          0.0560        0.0680      7
134          0.0205        0.0280      7
135          0.0810        0.1355      8
136          0.0345        0.0480      7
137          0.0295        0.0630      9
138          0.0630        0.1170      9
139          0.0575        0.0925      9
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
140   F   0.565     0.445   0.155        0.8260          0.3410
141   F   0.550     0.450   0.145        0.7410          0.2950
142   M   0.650     0.520   0.190        1.3445          0.5190
143   M   0.560     0.455   0.155        0.7970          0.3400
144   M   0.475     0.375   0.130        0.5175          0.2075
145   F   0.490     0.380   0.125        0.5490          0.2450
146   M   0.460     0.350   0.120        0.5150          0.2240
147   I   0.280     0.205   0.080        0.1270          0.0520
148   I   0.175     0.130   0.055        0.0315          0.0105
149   I   0.170     0.130   0.095        0.0300          0.0130

     Viscera weight  Shell weight  Rings
140          0.2055        0.2475     10
141          0.1435        0.2665     10
142          0.3060        0.4465     16
143          0.1900        0.2425     11
144          0.1165        0.1700     10
145          0.1075        0.1740     10
146          0.1080        0.1565     10
147          0.0390        0.0420      9
148          0.0065        0.0125      5
149          0.0080        0.0100      4
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
150   M   0.590     0.475   0.145        1.0530          0.4415
151   F   0.605     0.500   0.185        1.1185          0.4690
152   F   0.635     0.515   0.190        1.3715          0.5065
153   F   0.605     0.485   0.160        1.0565          0.3700
154   F   0.565     0.450   0.135        0.9885          0.3870
155   M   0.515     0.405   0.130        0.7220          0.3200
156   F   0.575     0.460   0.190        0.9940          0.3920
157   M   0.645     0.485   0.215        1.5140          0.5460
158   F   0.580     0.455   0.170        0.9075          0.3740
159   F   0.575     0.460   0.165        1.1240          0.2985

     Viscera weight  Shell weight  Rings
150          0.2620         0.325     15
151          0.2585         0.335      9
152          0.3050         0.450     10
153          0.2355         0.355     10
154          0.1495         0.310     12
155          0.1310         0.210     10
156          0.2425         0.340     13
157          0.2615         0.635     16
158          0.2135         0.285     13
159          0.1785         0.440     13
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
160   M   0.605     0.465   0.165        1.0560          0.4215
161   F   0.605     0.485   0.160        1.2220          0.5300
162   M   0.610     0.485   0.175        1.2445          0.5440
163   F   0.725     0.560   0.210        2.1410          0.6500
164   F   0.650     0.545   0.230        1.7520          0.5605
165   M   0.725     0.570   0.190        2.5500          1.0705
166   F   0.725     0.575   0.175        2.1240          0.7650
167   F   0.680     0.570   0.205        1.8420          0.6250
168   M   0.705     0.560   0.220        1.9810          0.8175
169   F   0.680     0.515   0.175        1.6185          0.5125

     Viscera weight  Shell weight  Rings
160          0.2475         0.340     13
161          0.2575         0.280     13
162          0.2970         0.345     12
163          0.3980         1.005     18
164          0.2895         0.815     16
165          0.4830         0.725     14
166          0.4515         0.850     20
167          0.4080         0.650     20
168          0.3085         0.760     14
169          0.4090         0.620     12
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
170   M   0.695     0.550   0.215        1.9565          0.7125
171   F   0.530     0.395   0.145        0.7750          0.3080
172   M   0.525     0.435   0.155        1.0650          0.4860
173   F   0.520     0.405   0.115        0.7760          0.3200
174   I   0.235     0.160   0.040        0.0480          0.0185

(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
310   F   0.630     0.485   0.190        1.2435          0.4635
311   M   0.560     0.440   0.140        0.9710          0.4430
312   M   0.595     0.455   0.195        1.3305          0.4595
313   F   0.620     0.470   0.200        1.2255          0.3810
314   M   0.630     0.485   0.175        1.3000          0.4335
315   I   0.450     0.355   0.110        0.4585          0.1940
316   F   0.635     0.535   0.190        1.2420          0.5760
317   M   0.450     0.350   0.100        0.3675          0.1465
318   F   0.580     0.455   0.155        0.8365          0.3150
319   I   0.330     0.255   0.095        0.1720          0.0660

     Viscera weight  Shell weight  Rings
310          0.3055         0.390     21
311          0.2045         0.265     14
312          0.3235         0.345     19
313          0.2700         0.435     23
314          0.2945         0.460     23
315          0.0670         0.140      8
316          0.2475         0.390     14
317          0.1015         0.120     10
318          0.1385         0.320     18
319          0.0255         0.060      6
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
320   I   0.265     0.210   0.060        0.0965          0.0425
321   I   0.190     0.145   0.040        0.0380          0.0165
322   M   0.385     0.310   0.100        0.2845          0.1065
323   I   0.265     0.205   0.070        0.1055          0.0390
324   M   0.335     0.265   0.105        0.2220          0.0935
325   I   0.355     0.275   0.090        0.2510          0.0970
326   I   0.320     0.255   0.100        0.1755          0.0730
327   M   0.510     0.400   0.130        0.6435          0.2700
328   M   0.360     0.295   0.105        0.2410          0.0865
329   I   0.360     0.280   0.090        0.2255          0.0885

     Viscera weight  Shell weight  Rings
320          0.0220         0.030      5
321          0.0065         0.015      4
322          0.0750         0.100     11
323          0.0410         0.035      5
324          0.0560         0.075      7
325          0.0530         0.080      7
326          0.0415         0.065      7
327          0.1665         0.205     12
328          0.0530         0.095      8
329          0.0400         0.090      8
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
330   M   0.500     0.380   0.155        0.5955          0.2135
331   F   0.400     0.325   0.120        0.3185          0.1340
332   I   0.300     0.220   0.080        0.1210          0.0475
333   I   0.235     0.175   0.040        0.0705          0.0335
334   F   0.740     0.600   0.195        1.9740          0.5980
335   M   0.620     0.465   0.190        1.3415          0.5705
336   M   0.600     0.475   0.190        1.0875          0.4030
337   M   0.590     0.450   0.185        1.2830          0.4730
338   M   0.620     0.475   0.185        1.3250          0.6045
339   F   0.565     0.450   0.195        1.0035          0.4060

     Viscera weight  Shell weight  Rings
330          0.1610         0.200     12
331          0.0565         0.095      8
332          0.0420         0.035      5
333          0.0150         0.020      5
334          0.4085         0.710     16
335          0.3175         0.355     11
336          0.2655         0.325     14
337          0.2760         0.425     16
338          0.3250         0.330     13
339          0.2505         0.285     15
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
340   M   0.575     0.455   0.145        1.1650          0.5810
341   F   0.620     0.510   0.205        1.3475          0.4775
342   M   0.620     0.465   0.185        1.2740          0.5790
343   F   0.505     0.375   0.180        0.5680          0.2325
344   F   0.460     0.425   0.155        0.7460          0.3005
345   M   0.490     0.390   0.140        0.7070          0.2795
346   F   0.525     0.420   0.160        0.7560          0.2745
347   I   0.340     0.260   0.080        0.2000          0.0800
348   I   0.375     0.305   0.115        0.2715          0.0920
349   M   0.610     0.480   0.150        1.2000          0.5600

     Viscera weight  Shell weight  Rings
340          0.2275         0.300     14
341          0.2565         0.480     14
342          0.3065         0.320     12
343          0.1495         0.170     12
344          0.1520         0.240      8
345          0.2185         0.180     13
346          0.1730         0.275      9
347          0.0555         0.055      6
348          0.0740         0.090      8
349          0.2455         0.280     14
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
350   F   0.610     0.495   0.185        1.1530          0.5360
351   F   0.585     0.450   0.170        0.8685          0.3325
352   M   0.570     0.460   0.140        0.9535          0.4465
353   M   0.580     0.455   0.170        0.9300          0.4080
354   M   0.635     0.515   0.170        1.2750          0.5090
355   M   0.700     0.580   0.205        2.1300          0.7415
356   M   0.675     0.525   0.185        1.5870          0.6935
357   F   0.645     0.525   0.190        1.8085          0.7035
358   M   0.745     0.585   0.215        2.4990          0.9265
359   F   0.685     0.545   0.180        1.7680          0.7495

     Viscera weight  Shell weight  Rings
350          0.2905         0.245      8
351          0.1635         0.270     22
352          0.2065         0.245     12
353          0.2590         0.220      9
354          0.2860         0.340     16
355          0.4900         0.580     20
356          0.3360         0.395     13
357          0.3885         0.395     18
358          0.4720         0.700     17
359          0.3920         0.485     16
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
360   M   0.605     0.490   0.180        1.2270          0.4800
361   F   0.590     0.465   0.150        0.9970          0.3920
362   F   0.650     0.525   0.175        1.4225          0.6100
363   F   0.600     0.480   0.150        1.0290          0.4085
364   F   0.620     0.500   0.175        1.1860          0.4985
365   M   0.630     0.515   0.160        1.0160          0.4215
366   M   0.580     0.465   0.145        0.8870          0.4405
367   F   0.580     0.455   0.120        1.0735          0.4790
368   M   0.630     0.490   0.180        1.1300          0.4580
369   F   0.690     0.560   0.215        1.7190          0.6800

     Viscera weight  Shell weight  Rings
360          0.2870         0.350     18
361          0.2460         0.340     12
362          0.2995         0.445     20
363          0.2705         0.295     16
364          0.3015         0.350     12
365          0.2440         0.355     19
366          0.1655         0.265     11
367          0.2735         0.265     10
368          0.2765         0.315     12
369          0.2990         0.470     17
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
370   F   0.650     0.545   0.165        1.5660          0.6645
371   F   0.660     0.565   0.195        1.7605          0.6920
372   F   0.680     0.580   0.200        1.7870          0.5850
373   F   0.700     0.575   0.170        1.3100          0.5095
374   M   0.685     0.520   0.150        1.3430          0.4635
375   F   0.675     0.545   0.195        1.7345          0.6845
376   M   0.630     0.490   0.190        1.1775          0.4935
377   F   0.585     0.450   0.160        1.0770          0.4995
378   M   0.565     0.465   0.175        0.9950          0.3895
379   F   0.610     0.495   0.185        1.1085          0.3705

     Viscera weight  Shell weight  Rings
370          0.3455         0.415     16
371          0.3265         0.500     16
372          0.4530         0.600     19
373          0.3140         0.420     14
374          0.2920         0.400     13
375          0.3695         0.605     20
376          0.3365         0.285     11
377          0.2875         0.250     10
378          0.1830         0.370     15
379          0.3135         0.330     12
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
380   M   0.605     0.470   0.180        1.1405          0.3755
381   M   0.535     0.420   0.145        0.7910          0.3300
382   M   0.485     0.400   0.135        0.6630          0.3130
383   M   0.470     0.375   0.120        0.5565          0.2260
384   M   0.545     0.425   0.135        0.8445          0.3730
385   F   0.455     0.370   0.105        0.4925          0.2160
386   M   0.540     0.420   0.155        0.7385          0.3515
387   M   0.460     0.380   0.135        0.4820          0.2070
388   M   0.490     0.420   0.125        0.6090          0.2390
389   I   0.465     0.375   0.120        0.4710          0.2220

     Viscera weight  Shell weight  Rings
380          0.2805         0.385     15
381          0.1890         0.250     10
382          0.1370         0.200     10
383          0.1220         0.195     12
384          0.2100         0.235     10
385          0.1245         0.135      9
386          0.1520         0.215     12
387          0.1225         0.145     10
388          0.1435         0.220     14
389          0.1190         0.140      9
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
390   I   0.415     0.325   0.100        0.3215          0.1535
391   M   0.475     0.375   0.125        0.5930          0.2770
392   F   0.470     0.375   0.125        0.5615          0.2520
393   I   0.365     0.295   0.095        0.2500          0.1075
394   I   0.345     0.275   0.095        0.1995          0.0755
395   I   0.390     0.310   0.100        0.3020          0.1160
396   F   0.500     0.395   0.140        0.7155          0.3165
397   M   0.470     0.380   0.145        0.5865          0.2385
398   M   0.535     0.440   0.150        0.6765          0.2560
399   M   0.585     0.455   0.150        0.9870          0.4355

     Viscera weight  Shell weight  Rings
390          0.0595         0.105     10
391          0.1150         0.180     10
392          0.1370         0.180     10
393          0.0545         0.080      9
394          0.0535         0.070      6
395          0.0640         0.115     11
396          0.1760         0.240     10
397          0.1440         0.185      8
398          0.1390         0.260     12
399          0.2075         0.310     11
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
400   F   0.485     0.365   0.120        0.5885          0.2700
401   M   0.515     0.455   0.135        0.7225          0.2950
402   F   0.435     0.325   0.110        0.4335          0.1780
403   F   0.515     0.415   0.140        0.6935          0.3115
404   I   0.440     0.345   0.120        0.3650          0.1655
405   F   0.525     0.440   0.150        0.8425          0.3685
406   M   0.450     0.355   0.115        0.4790          0.2125
407   M   0.590     0.485   0.120        0.9110          0.3900
408   M   0.555     0.450   0.145        0.9150          0.4000
409   M   0.570     0.440   0.095        0.8270          0.3395

     Viscera weight  Shell weight  Rings
400          0.1310         0.175      9
401          0.1625         0.235      9
402          0.0985         0.155      7
403          0.1520         0.200     10
404          0.0830         0.110      7
405          0.1985         0.240     12
406          0.1045         0.150      8
407          0.1820         0.290     16
408          0.2460         0.285     11
409          0.2215         0.235      8
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
410   M   0.590     0.500   0.165        1.1045          0.4565
411   M   0.585     0.475   0.120        0.9450          0.4100
412   F   0.580     0.460   0.120        0.9935          0.4625
413   M   0.545     0.440   0.120        0.8565          0.3475
414   F   0.605     0.495   0.170        1.2385          0.5280
415   F   0.620     0.470   0.140        1.0325          0.3605
416   F   0.630     0.500   0.170        1.3135          0.5595
417   M   0.630     0.515   0.165        1.3520          0.4880
418   F   0.630     0.500   0.155        1.0050          0.3670
419   M   0.545     0.410   0.140        0.6250          0.2230

     Viscera weight  Shell weight  Rings
410          0.2425         0.340     15
411          0.2115         0.280     14
412          0.2385         0.280     11
413          0.1715         0.240     12
414          0.2465         0.390     14
415          0.2240         0.360     15
416          0.2670         0.400     20
417          0.3490         0.450     20
418          0.1990         0.360     16
419          0.1600         0.235     13
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
420   F   0.670     0.540   0.165        1.5015          0.5180
421   I   0.490     0.380   0.120        0.5290          0.2165
422   F   0.490     0.390   0.135        0.5785          0.2465
423   I   0.290     0.225   0.070        0.1010          0.0360
424   I   0.260     0.200   0.070        0.0920          0.0370
425   M   0.580     0.450   0.175        1.0680          0.4250
426   F   0.610     0.485   0.165        1.0915          0.3935
427   M   0.600     0.500   0.160        1.0150          0.3995
428   F   0.560     0.455   0.125        0.9430          0.3440
429   F   0.575     0.450   0.170        1.0475          0.3775

     Viscera weight  Shell weight  Rings
420          0.3580         0.505     14
421          0.1390         0.155     11
422          0.1230         0.200     13
423          0.0235         0.035      8
424          0.0200         0.030      6
425          0.2030         0.320     13
426          0.2435         0.330     18
427          0.1735         0.330     19
428          0.1290         0.375     21
429          0.1705         0.385     18
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
430   F   0.570     0.450   0.175        0.9555          0.3800
431   M   0.600     0.470   0.155        1.0360          0.4375
432   M   0.565     0.455   0.170        0.9065          0.3420
433   M   0.545     0.420   0.140        0.7505          0.2475
434   I   0.440     0.345   0.100        0.3660          0.1220
435   M   0.500     0.410   0.150        0.6620          0.2815
436   I   0.360     0.275   0.095        0.2170          0.0840
437   I   0.385     0.305   0.095        0.2520          0.0915
438   M   0.390     0.300   0.090        0.3055          0.1430
439   M   0.500     0.415   0.165        0.6885          0.2490

     Viscera weight  Shell weight  Rings
430          0.1665         0.295     18
431          0.1960         0.325     20
432          0.1560         0.320     18
433          0.1300         0.255     22
434          0.0905         0.120     13
435          0.1370         0.220     11
436          0.0435         0.090      7
437          0.0550         0.090     14
438          0.0645         0.085      9
439          0.1380         0.250     13
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
440   I   0.360     0.275   0.110        0.2335          0.0950
441   I   0.335     0.260   0.100        0.1920          0.0785
442   F   0.505     0.425   0.140        0.8500          0.2750
443   I   0.395     0.295   0.100        0.2715          0.1340
444   F   0.410     0.325   0.105        0.3635          0.1590
445   F   0.560     0.455   0.190        0.7140          0.2830
446   M   0.565     0.435   0.185        0.9815          0.3290
447   M   0.565     0.455   0.185        0.9265          0.3540
448   M   0.605     0.500   0.175        1.0980          0.4765
449   F   0.565     0.455   0.150        0.8205          0.3650

     Viscera weight  Shell weight  Rings
440          0.0525         0.085     10
441          0.0585         0.070      8
442          0.1625         0.285     19
443          0.0325         0.085     10
444          0.0770         0.120     10
445          0.1290         0.275      9
446          0.1360         0.390     13
447          0.1575         0.375     16
448          0.2320         0.375     12
449          0.1590         0.260     18
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
450   M   0.725     0.565   0.215        1.8910          0.6975
451   F   0.675     0.535   0.160        1.4100          0.5920
452   F   0.665     0.555   0.195        1.4385          0.5810
453   F   0.565     0.490   0.155        0.9245          0.4050
454   F   0.645     0.550   0.175        1.2915          0.5700
455   M   0.575     0.470   0.140        0.8375          0.3485
456   F   0.640     0.540   0.175        1.2210          0.5100
457   I   0.360     0.280   0.105        0.1990          0.0695
458   I   0.415     0.310   0.110        0.2965          0.1230
459   F   0.525     0.410   0.135        0.7085          0.2930

     Viscera weight  Shell weight  Rings
450          0.4725        0.5800     16
451          0.3175        0.4200     16
452          0.3540        0.3600     17
453          0.2195        0.2550     11
454          0.3045        0.3300     14
455          0.1735        0.2400     11
456          0.2590        0.3900     15
457          0.0450        0.0800      9
458          0.0570        0.0995     10
459          0.1525        0.2350     11
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
460   M   0.380     0.285   0.100        0.2665          0.1150
461   F   0.585     0.465   0.170        0.9915          0.3865
462   I   0.240     0.185   0.070        0.0715          0.0260
463   I   0.220     0.165   0.055        0.0545          0.0215
464   I   0.255     0.195   0.070        0.0735          0.0255
465   I   0.175     0.125   0.050        0.0235          0.0080
466   F   0.670     0.550   0.190        1.3905          0.5425
467   M   0.655     0.530   0.195        1.3880          0.5670
468   F   0.680     0.550   0.210        1.7445          0.5975
469   M   0.675     0.555   0.200        1.4385          0.5450

     Viscera weight  Shell weight  Rings
460          0.0610         0.075     11
461          0.2240         0.265     12
462          0.0180         0.025      6
463          0.0120         0.020      5
464          0.0200         0.025      6
465          0.0035         0.008      5
466          0.3035         0.400     12
467          0.2735         0.410     13
468          0.3050         0.625     17
469          0.2665         0.465     21
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
470   F   0.530     0.440   0.135        0.7835          0.3130
471   F   0.515     0.405   0.120        0.6460          0.2895
472   I   0.430     0.340   0.120        0.3575          0.1510
473   F   0.520     0.405   0.120        0.6270          0.2645
474   F   0.545     0.415   0.160        0.7715          0.2720
475   M   0.530     0.415   0.175        0.7395          0.2610
476   F   0.465     0.350   0.115        0.4210          0.1565
477   M   0.665     0.540   0.175        1.3470          0.4955
478   M   0.735     0.590   0.225        1.7560          0.6370
479   M   0.660     0.545   0.185        1.3200          0.5305

     Viscera weight  Shell weight  Rings
470          0.1715        0.2185      9
471          0.1405        0.1770     10
472          0.0645        0.1045      9
473          0.1415        0.1810     11
474          0.1455        0.2765     10
475          0.1395        0.2645     17
476          0.0910        0.1345      9
477          0.2540        0.4150     17
478          0.3405        0.5800     21
479          0.2635        0.4550     16
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
480   F   0.700     0.585   0.185        1.8075          0.7055

629          0.0460         0.065     10
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
630   I   0.475     0.365   0.115        0.4900          0.2230
631   F   0.430     0.340   0.120        0.3910          0.1555
632   M   0.460     0.365   0.125        0.4670          0.1895
633   I   0.470     0.360   0.130        0.5225          0.1980
634   M   0.360     0.295   0.100        0.2105          0.0660
635   M   0.355     0.265   0.090        0.1680          0.0500
636   M   0.380     0.235   0.100        0.2580          0.1055
637   M   0.355     0.260   0.085        0.1905          0.0810
638   I   0.440     0.345   0.120        0.4870          0.1965
639   F   0.510     0.400   0.130        0.5735          0.2190

     Viscera weight  Shell weight  Rings
630          0.1235        0.1335      9
631          0.0950        0.1405      7
632          0.0945        0.1580     10
633          0.1065        0.1650      9
634          0.0525        0.0750      9
635          0.0410        0.0630      8
636          0.0540        0.0800      7
637          0.0485        0.0550      6
638          0.1080        0.1600     14
639          0.1365        0.1950     13
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
640   M   0.325     0.240   0.085        0.1730          0.0795
641   I   0.620     0.485   0.180        1.1785          0.4675
642   F   0.590     0.450   0.160        0.9000          0.3580
643   M   0.330     0.255   0.095        0.1875          0.0735
644   M   0.450     0.340   0.130        0.3715          0.1605
645   I   0.445     0.330   0.120        0.3470          0.1200
646   M   0.330     0.215   0.075        0.1145          0.0450
647   M   0.480     0.375   0.145        0.7770          0.2160
648   I   0.460     0.350   0.120        0.4885          0.1930
649   F   0.475     0.360   0.125        0.4470          0.1695

     Viscera weight  Shell weight  Rings
640          0.0380         0.050      7
641          0.2655         0.390     13
642          0.1560         0.315     19
643          0.0450         0.060      7
644          0.0795         0.105      9
645          0.0840         0.105     11
646          0.0265         0.035      6
647          0.1300         0.170      9
648          0.1050         0.155     11
649          0.0810         0.140      9
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
650   M   0.255     0.180   0.065        0.0790          0.0340
651   I   0.335     0.245   0.090        0.1665          0.0595
652   I   0.470     0.350   0.130        0.4660          0.1845
653   M   0.310     0.225   0.080        0.1345          0.0540
654   F   0.370     0.280   0.110        0.2305          0.0945
655   M   0.295     0.215   0.075        0.1290          0.0500
656   F   0.555     0.435   0.165        0.9700          0.3360
657   F   0.615     0.515   0.170        1.1400          0.4305
658   I   0.580     0.490   0.195        1.3165          0.5305
659   F   0.585     0.475   0.185        0.9585          0.4145

     Viscera weight  Shell weight  Rings
650          0.0140         0.025      5
651          0.0400         0.060      6
652          0.0990         0.145     11
653          0.0240         0.050      7
654          0.0465         0.075     10
655          0.0295         0.040      7
656          0.2315         0.295     17
657          0.2245         0.420     16
658          0.2540         0.410     18
659          0.1615         0.330     11
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
660   I   0.650     0.525   0.180        1.6260          0.5970
661   I   0.535     0.450   0.170        0.7810          0.3055
662   F   0.415     0.340   0.130        0.3675          0.1460
663   F   0.380     0.305   0.105        0.2810          0.1045
664   I   0.450     0.355   0.120        0.4120          0.1145
665   F   0.395     0.295   0.095        0.2245          0.0780
666   M   0.455     0.350   0.120        0.4835          0.1815
667   F   0.485     0.380   0.150        0.6050          0.2155
668   M   0.550     0.425   0.155        0.9175          0.2775
669   F   0.450     0.350   0.145        0.5425          0.1765

     Viscera weight  Shell weight  Rings
660          0.3445         0.530     18
661          0.1555         0.295     11
662          0.0885         0.120     10
663          0.0615         0.090     12
664          0.0665         0.160     19
665          0.0540         0.080     10
666          0.1440         0.160     11
667          0.1400         0.180     15
668          0.2430         0.335     13
669          0.1230         0.175     13
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
670   M   0.475     0.385   0.145        0.6175          0.2350
671   F   0.500     0.380   0.155        0.6550          0.2405
672   F   0.530     0.410   0.165        0.8115          0.2400
673   M   0.490     0.390   0.150        0.5730          0.2250
674   F   0.490     0.385   0.150        0.7865          0.2410
675   F   0.520     0.395   0.180        0.6400          0.1580
676   M   0.540     0.415   0.145        0.7400          0.2635
677   F   0.500     0.375   0.115        0.5945          0.1850
678   F   0.450     0.380   0.165        0.8165          0.2500
679   F   0.370     0.275   0.100        0.2225          0.0930

     Viscera weight  Shell weight  Rings
670          0.1080         0.215     14
671          0.1430         0.205     17
672          0.1690         0.240     19
673          0.1240         0.170     21
674          0.1400         0.240     23
675          0.1100         0.245     22
676          0.1680         0.245     12
677          0.1480         0.190     11
678          0.1915         0.265     23
679          0.0260         0.080      8
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
680   I   0.370     0.275   0.100        0.2295          0.0885
681   M   0.485     0.370   0.140        0.5725          0.2040
682   F   0.435     0.325   0.115        0.3915          0.1540
683   M   0.535     0.405   0.185        0.8345          0.3175
684   M   0.510     0.400   0.140        0.6515          0.2455
685   M   0.565     0.440   0.185        0.9090          0.3440
686   F   0.535     0.400   0.150        0.8045          0.3345
687   F   0.535     0.405   0.125        0.9270          0.2600
688   M   0.525     0.400   0.170        0.7305          0.2790
689   M   0.590     0.440   0.150        0.9555          0.3660

     Viscera weight  Shell weight  Rings
680          0.0465         0.070      7
681          0.1415         0.175     10
682          0.0940         0.120      7
683          0.1725         0.290     16
684          0.1665         0.185     10
685          0.2325         0.255     15
686          0.2125         0.210     13
687          0.1425         0.345     16
688          0.2055         0.195     11
689          0.2425         0.295     11
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
690   M   0.500     0.375   0.150        0.6360          0.2535
691   I   0.255     0.190   0.075        0.0865          0.0345
692   F   0.430     0.325   0.115        0.3865          0.1475
693   M   0.380     0.290   0.120        0.2830          0.1175
694   I   0.165     0.110   0.020        0.0190          0.0065
695   I   0.315     0.230   0.090        0.1285          0.0430
696   I   0.155     0.105   0.050        0.0175          0.0050
697   M   0.280     0.205   0.100        0.1165          0.0545
698   F   0.430     0.335   0.120        0.4440          0.1550
699   F   0.395     0.315   0.105        0.3515          0.1185

     Viscera weight  Shell weight  Rings
690          0.1450        0.1900     10
691          0.0205        0.0250      5
692          0.1065        0.1100     11
693          0.0655        0.0850      9
694          0.0025        0.0050      4
695          0.0400        0.0400      7
696          0.0035        0.0050      4
697          0.0285        0.0300      5
698          0.1145        0.1400     13
699          0.0910        0.1195     16
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
700   M   0.385     0.285   0.105        0.2905          0.1215
701   F   0.480     0.385   0.135        0.5360          0.1895
702   F   0.445     0.330   0.105        0.4525          0.1800
703   M   0.395     0.295   0.115        0.3160          0.1205
704   M   0.400     0.300   0.125        0.4170          0.1910
705   M   0.415     0.325   0.140        0.4170          0.1535
706   M   0.315     0.250   0.090        0.2030          0.0615
707   F   0.345     0.260   0.090        0.2070          0.0775
708   M   0.360     0.295   0.130        0.2765          0.0895
709   I   0.295     0.225   0.090        0.1105          0.0405

     Viscera weight  Shell weight  Rings
700          0.0685        0.0875     12
701          0.1420        0.1730     14
702          0.1030        0.1230      9
703          0.0595        0.1105     12
704          0.0900        0.1175      9
705          0.1015        0.1440     10
706          0.0370        0.0795     11
707          0.0435        0.0765     10
708          0.0570        0.1005     10
709          0.0245        0.0320      7
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
710   I   0.325     0.250   0.080        0.1760          0.0595
711   M   0.375     0.300   0.100        0.2465          0.1040
712   I   0.280     0.205   0.055        0.1135          0.0450
713   M   0.355     0.265   0.085        0.2010          0.0690
714   M   0.350     0.255   0.080        0.1915          0.0800
715   I   0.275     0.200   0.065        0.1035          0.0475
716   I   0.290     0.205   0.070        0.0975          0.0360
717   I   0.250     0.190   0.060        0.0765          0.0360
718   I   0.180     0.125   0.035        0.0265          0.0095
719   I   0.150     0.100   0.025        0.0150          0.0045

     Viscera weight  Shell weight  Rings
710          0.0355        0.0630      7
711          0.0475        0.0830     11
712          0.0275        0.0335      7
713          0.0530        0.0695      8
714          0.0385        0.0630      9
715          0.0205        0.0300      7
716          0.0190        0.0350      8
717          0.0115        0.0245      6
718          0.0055        0.0085      4
719          0.0040        0.0050      2
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
720   I   0.160     0.110   0.025        0.0180          0.0065
721   M   0.555     0.455   0.160        1.0575          0.3925
722   M   0.555     0.440   0.150        1.0920          0.4160
723   M   0.525     0.410   0.130        0.9900          0.3865
724   M   0.465     0.360   0.080        0.4880          0.1910
725   F   0.490     0.360   0.110        0.5005          0.1610
726   M   0.400     0.305   0.085        0.2970          0.1080
727   F   0.480     0.375   0.105        0.5250          0.2185
728   M   0.505     0.400   0.125        0.7700          0.2735
729   F   0.520     0.400   0.120        0.6515          0.2610

     Viscera weight  Shell weight  Rings
720          0.0055        0.0050      3
721          0.2280        0.2930     13
722          0.2120        0.4405     15
723          0.2430        0.2950     15
724          0.1250        0.1550     11
725          0.1070        0.1950     17
726          0.0705        0.1000     10
727          0.1195        0.1550     12
728          0.1590        0.2550     13
729          0.2015        0.1650     15
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
730   M   0.525     0.400   0.130        0.8295          0.2405
731   M   0.545     0.420   0.130        0.8790          0.3740
732   M   0.520     0.400   0.120        0.8230          0.2980
733   M   0.505     0.380   0.130        0.6560          0.2270
734   M   0.525     0.425   0.120        0.8665          0.2825
735   M   0.510     0.390   0.125        0.6565          0.2620
736   M   0.520     0.385   0.115        0.6690          0.2385
737   F   0.520     0.405   0.125        0.6435          0.2415
738   M   0.535     0.410   0.135        0.8620          0.2855
739   M   0.445     0.345   0.090        0.3795          0.1430

     Viscera weight  Shell weight  Rings
730          0.1825         0.275     11
731          0.1695         0.230     13
732          0.1805         0.265     15
733          0.1785         0.220     13
734          0.1760         0.290     18
735          0.1835         0.175     10
736          0.1720         0.205     12
737          0.1735         0.210     12
738          0.1525         0.320     14
739          0.0740         0.125     10
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
740   M   0.530     0.440   0.205        0.8350          0.3200
741   F   0.360     0.265   0.090        0.2065          0.0780
742   F   0.535     0.420   0.150        0.7365          0.2785
743   F   0.520     0.405   0.140        0.8175          0.2795
744   M   0.530     0.415   0.130        0.8425          0.2750
745   F   0.530     0.420   0.130        1.0010          0.3400
746   F   0.660     0.520   0.200        1.6760          0.6730
747   M   0.520     0.385   0.140        0.6595          0.2485
748   M   0.535     0.420   0.130        0.8055          0.3010
749   M   0.695     0.515   0.175        1.5165          0.5780

     Viscera weight  Shell weight  Rings
740          0.2175         0.245     14
741          0.0570         0.060      8
742          0.1860         0.215     14
743          0.1830         0.260     17
744          0.1945         0.265     20
745          0.2260         0.265     17
746          0.4805         0.450     17
747          0.2035         0.160      9
748          0.1810         0.280     14
749          0.4105         0.390     15
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
750   F   0.510     0.390   0.105        0.6120          0.1870
751   M   0.485     0.355   0.120        0.5470          0.2150
752   F   0.605     0.460   0.170        1.1220          0.3470
753   F   0.580     0.455   0.165        1.1365          0.3690
754   M   0.650     0.515   0.175        1.4805          0.5295
755   M   0.620     0.505   0.185        1.5275          0.6900
756   M   0.615     0.525   0.155        1.1375          0.3670
757   F   0.605     0.495   0.190        1.4370          0.4690
758   M   0.570     0.440   0.155        1.1160          0.4775
759   M   0.570     0.430   0.120        1.0615          0.3480

     Viscera weight  Shell weight  Rings
750          0.1500         0.195     13
751          0.1615         0.140     10
752          0.3045         0.315     13
753          0.3005         0.275     13
754          0.2720         0.525     20
755          0.3680         0.350     13
756          0.2360         0.370     20
757          0.2655         0.410     15
758          0.2315         0.270     13
759          0.1670         0.310     15
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
760   M   0.585     0.405   0.150        1.2565          0.4350
761   F   0.550     0.440   0.155        0.9460          0.3130
762   F   0.540     0.440   0.135        0.9590          0.2385
763   M   0.640     0.510   0.190        1.6130          0.6215
764   F   0.610     0.470   0.145        1.1530          0.4030
765   M   0.545     0.450   0.150        0.9780          0.3365
766   F   0.590     0.445   0.130        1.1325          0.3825
767   M   0.345     0.270   0.095        0.1970          0.0665
768   F   0.550     0.430   0.155        0.7850          0.2890
769   F   0.530     0.425   0.170        0.9490          0.3485

     Viscera weight  Shell weight  Rings
760          0.2020         0.325     15
761          0.1825         0.335     16
762          0.2210         0.300     17
763          0.3610         0.470     14
764          0.2960         0.320     14
765          0.1905         0.300     11
766          0.2340         0.320     13
767          0.0500         0.070      9
768          0.2270         0.233     11
769          0.2395         0.278     17
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
770   F   0.530     0.455   0.165        0.9805          0.3155
771   I   0.485     0.375   0.140        0.5210          0.2000
772   M   0.385     0.275   0.115        0.2685          0.0975
773   M   0.455     0.340   0.135        0.4620          0.1675
774   M   0.490     0.380   0.140        0.7605          0.2450
775   M   0.530     0.410   0.165        0.7320          0.1890
776   M   0.505     0.385   0.145        0.6775          0.2360
777   M   0.490     0.380   0.140        0.6385          0.2305
778   M   0.465     0.350   0.140        0.5755          0.2015
779   F   0.470     0.360   0.145        0.5370          0.1725

     Viscera weight  Shell weight  Rings
770          0.2815        0.2965     11
771          0.1230        0.1700      8
772          0.0825        0.0850      8
773          0.1580        0.1200      9
774          0.1670        0.1850     10
775          0.1700        0.3100     11
776          0.1790        0.2000     15
777          0.1420        0.1950     13
778          0.1505        0.1900     15
779          0.1375        0.1950     15
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
780   M   0.560     0.410   0.165        0.9300          0.3505
781   M   0.505     0.385   0.150        0.6415          0.2460
782   M   0.515     0.435   0.145        0.8815          0.2920
783   I   0.385     0.280   0.125        0.2440          0.1020
784   I   0.215     0.155   0.060        0.0525          0.0210
785   M   0.550     0.415   0.175        1.0420          0.3295
786   F   0.515     0.390   0.130        0.5755          0.1975
787   M   0.495     0.385   0.135        0.7090          0.2110
788   F   0.505     0.390   0.160        0.6440          0.2475
789   F   0.600     0.465   0.165        0.8875          0.3090

     Viscera weight  Shell weight  Rings
780          0.2370        0.3000     13
781          0.1520        0.2150     12
782          0.2060        0.2550     10
783          0.0380        0.0850      6
784          0.0165        0.0150      5
785          0.2325        0.2905     15
786          0.1300        0.1845      9
787          0.1375        0.2620     12
788          0.2025        0.1635      9
789          0.2460        0.2620     12
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
790   F   0.570     0.465   0.160        0.8935          0.3145
791   F   0.485     0.375   0.135        0.5560          0.1925
792   M   0.470     0.370   0.180        0.5100          0.1915
793   M   0.575     0.450   0.165        0.9215          0.3275
794   M   0.580     0.465   0.160        1.0345          0.3150
795   M   0.515     0.405   0.145        0.6950          0.2150
796   M   0.530     0.410   0.155        0.7155          0.2805
797   M   0.440     0.335   0.110        0.3940          0.1570
798   M   0.520     0.420   0.160        0.7450          0.2550
799   F   0.425     0.345   0.110        0.3665          0.1250

     Viscera weight  Shell weight  Rings
790          0.2575        0.2630     10
791          0.1315        0.1685     10
792          0.1285        0.1625      9
793          0.2250        0.2560     12
794          0.2600        0.3635     12
795          0.1635        0.2340     15
796          0.1685        0.2140     11
797          0.0960        0.1220      9
798          0.1570        0.2885     11
799          0.0810        0.1170     11
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \

(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
960   M   0.500     0.400   0.125        0.6725          0.3360
961   F   0.505     0.390   0.130        0.6740          0.3165
962   I   0.505     0.390   0.150        0.6850          0.3620
963   M   0.505     0.410   0.125        0.6420          0.2890
964   I   0.505     0.355   0.125        0.6010          0.2500
965   M   0.510     0.390   0.135        0.7690          0.3935
966   I   0.510     0.375   0.100        0.5785          0.2380
967   I   0.510     0.405   0.135        0.7690          0.3655
968   M   0.510     0.405   0.150        0.7035          0.3470
969   M   0.510     0.410   0.145        0.7960          0.3865

     Viscera weight  Shell weight  Rings
960          0.1200        0.1825      7
961          0.1410        0.1785      9
962          0.1310        0.1560      8
963          0.1330        0.1550      9
964          0.1205        0.1850      8
965          0.1455        0.1900      8
966          0.1225        0.1750      7
967          0.1585        0.1800      7
968          0.1340        0.1885      8
969          0.1815        0.1955      8
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
970   F   0.515     0.430   0.140        0.8340          0.3670
971   M   0.515     0.390   0.155        0.7125          0.3695
972   F   0.525     0.415   0.140        0.7240          0.3475
973   M   0.525     0.400   0.140        0.7325          0.3340
974   F   0.530     0.425   0.130        0.7585          0.3250
975   F   0.530     0.425   0.150        0.8495          0.3280
976   M   0.530     0.405   0.125        0.6515          0.2715
977   F   0.535     0.400   0.135        0.8215          0.3935
978   M   0.535     0.430   0.140        0.7165          0.2855
979   M   0.535     0.435   0.140        0.8740          0.3735

     Viscera weight  Shell weight  Rings
970          0.2000        0.2300      8
971          0.1370        0.1550      7
972          0.1730        0.1750      8
973          0.1575        0.1700     11
974          0.1970        0.2050      8
975          0.2320        0.2020      8
976          0.1605        0.1860      7
977          0.1960        0.2050      8
978          0.1595        0.2155      8
979          0.2290        0.2195      8
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
980   F   0.550     0.445   0.155        0.9905          0.5440
981   F   0.550     0.430   0.140        0.8105          0.3680
982   F   0.560     0.455   0.160        0.9670          0.4525
983   F   0.565     0.400   0.130        0.6975          0.3075
984   M   0.570     0.450   0.155        1.1950          0.5625
985   M   0.570     0.450   0.155        1.1935          0.5130
986   F   0.570     0.455   0.150        1.1070          0.5400
987   M   0.570     0.445   0.140        1.0635          0.5265
988   M   0.570     0.460   0.170        0.9035          0.4075
989   M   0.575     0.475   0.160        1.1140          0.4955

     Viscera weight  Shell weight  Rings
980          0.1780         0.218      9
981          0.1610         0.275      9
982          0.2070         0.274      9
983          0.1665         0.180      8
984          0.2565         0.295     10
985          0.2100         0.343     10
986          0.2550         0.270      8
987          0.2195         0.240      8
988          0.1935         0.214      7
989          0.2745         0.290      9
(10, 9)
    Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
990   F   0.575     0.460   0.160        1.1030          0.5380
991   F   0.580     0.460   0.150        1.1155          0.5575
992   F   0.580     0.460   0.180        1.0515          0.4095
993   M   0.580     0.455   0.150        1.0120          0.4985
994   F   0.580     0.450   0.145        1.1370          0.5585
995   M   0.580     0.490   0.130        1.1335          0.5860
996   M   0.590     0.465   0.155        1.1360          0.5245
997   M   0.590     0.470   0.160        1.2060          0.4790
998   F   0.590     0.455   0.145        1.0630          0.5155
999   F   0.595     0.470   0.155        1.1210          0.4515

     Viscera weight  Shell weight  Rings
990          0.2210        0.2490      9
991          0.2255        0.2900      7
992          0.2595        0.2760      8
993          0.2115        0.2835     10
994          0.2200        0.2900      8
995          0.2565        0.2370      9
996          0.2615        0.2750     11
997          0.2425        0.3090      8
998          0.2445        0.2500      8
999          0.1780        0.1550     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1000   F   0.595     0.450   0.150        1.1140          0.5865
1001   M   0.595     0.475   0.165        1.2130          0.6210
1002   F   0.595     0.460   0.140        1.0045          0.4655
1003   M   0.595     0.455   0.150        1.0440          0.5180
1004   F   0.605     0.490   0.150        1.1345          0.5265
1005   M   0.605     0.475   0.155        1.1610          0.5720
1006   M   0.605     0.470   0.165        1.2315          0.6025
1007   M   0.610     0.470   0.150        1.1625          0.5650
1008   M   0.610     0.475   0.155        1.1680          0.5540
1009   F   0.615     0.480   0.160        1.2525          0.5850

      Viscera weight  Shell weight  Rings
1000          0.2205        0.2500     11
1001          0.2435        0.2740      9
1002          0.2095        0.2515      9
1003          0.2205        0.2700      9
1004          0.2645        0.2950      9
1005          0.2455        0.2750      9
1006          0.2620        0.2925     11
1007          0.2580        0.3085     11
1008          0.2390        0.3295     10
1009          0.2595        0.3300      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1010   F   0.620     0.510   0.180        1.3315          0.5940
1011   F   0.625     0.480   0.170        1.3525          0.6235
1012   M   0.625     0.490   0.175        1.3325          0.5705
1013   F   0.625     0.475   0.175        1.1435          0.4755
1014   F   0.625     0.500   0.165        1.2880          0.5730
1015   F   0.625     0.485   0.200        1.3800          0.5845
1016   M   0.630     0.485   0.155        1.2780          0.6370
1017   F   0.630     0.495   0.165        1.3075          0.5990
1018   M   0.630     0.480   0.150        1.1785          0.5185
1019   M   0.635     0.490   0.175        1.3750          0.6230

      Viscera weight  Shell weight  Rings
1010          0.2760        0.3880     11
1011          0.2780        0.3650     10
1012          0.2710        0.4050     10
1013          0.2475        0.3490     10
1014          0.3035        0.3150      9
1015          0.3020        0.4010      9
1016          0.2750        0.3100      8
1017          0.2840        0.3150     11
1018          0.2480        0.3235      8
1019          0.2705        0.3950     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1020   M   0.635     0.525   0.185        1.4065          0.6840
1021   M   0.640     0.505   0.155        1.4025          0.7050
1022   F   0.640     0.500   0.170        1.5175          0.6930
1023   F   0.640     0.500   0.175        1.3940          0.4935
1024   F   0.645     0.500   0.155        1.2205          0.6145
1025   M   0.645     0.520   0.175        1.6360          0.7790
1026   M   0.645     0.520   0.175        1.5610          0.7090
1027   F   0.645     0.505   0.165        1.4325          0.6840
1028   M   0.645     0.500   0.175        1.3385          0.6330
1029   F   0.645     0.500   0.160        1.2465          0.5475

      Viscera weight  Shell weight  Rings
1020          0.3000        0.3745     10
1021          0.2655        0.3350     10
1022          0.3260        0.4090     11
1023          0.2910        0.4000     10
1024          0.2360        0.3185     10
1025          0.3420        0.4320     11
1026          0.3555        0.4000      8
1027          0.3080        0.3360      8
1028          0.2990        0.3490     11
1029          0.3270        0.3000     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1030   F   0.645     0.515   0.150        1.2120          0.5150
1031   M   0.650     0.495   0.160        1.3040          0.5700
1032   M   0.650     0.520   0.210        1.6785          0.6665
1033   M   0.650     0.525   0.185        1.6220          0.6645
1034   F   0.655     0.460   0.160        1.4940          0.6895
1035   F   0.655     0.510   0.175        1.6525          0.8515
1036   F   0.660     0.505   0.185        1.5280          0.6900
1037   M   0.660     0.535   0.190        1.5905          0.6425
1038   M   0.660     0.495   0.195        1.6275          0.5940
1039   F   0.660     0.475   0.180        1.3695          0.6410

      Viscera weight  Shell weight  Rings
1030          0.2055        0.3850     10
1031          0.3120        0.3725      9
1032          0.3080        0.4600     11
1033          0.3225        0.4770     10
1034          0.3310        0.1825      9
1035          0.3365        0.4030     10
1036          0.3025        0.4410     11
1037          0.2970        0.5175      9
1038          0.3595        0.4850     10
1039          0.2940        0.3350      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1040   M   0.670     0.525   0.165        1.6085          0.6820
1041   F   0.675     0.570   0.225        1.5870          0.7390
1042   F   0.675     0.565   0.195        1.8375          0.7645
1043   M   0.680     0.535   0.185        1.6070          0.7245
1044   M   0.690     0.525   0.175        1.7005          0.8255
1045   M   0.690     0.505   0.200        1.8720          0.8930
1046   F   0.695     0.535   0.175        1.8385          0.8035
1047   F   0.705     0.535   0.180        1.6850          0.6930
1048   M   0.710     0.565   0.205        2.1980          1.0120
1049   M   0.715     0.565   0.175        1.9525          0.7645

      Viscera weight  Shell weight  Rings
1040          0.3145        0.4005     11
1041          0.2995        0.4350     10
1042          0.3615        0.5530     12
1043          0.3215        0.4980     12
1044          0.3620        0.4050      8
1045          0.4015        0.4800     10
1046          0.3960        0.5030     10
1047          0.4200        0.4045     12
1048          0.5225        0.5475     11
1049          0.4185        0.4135     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1050   F   0.715     0.525   0.185        1.5600          0.6655
1051   F   0.735     0.600   0.220        2.5550          1.1335
1052   M   0.765     0.600   0.220        2.3020          1.0070
1053   I   0.185     0.130   0.045        0.0290          0.0120
1054   I   0.195     0.150   0.045        0.0375          0.0180
1055   I   0.195     0.135   0.040        0.0325          0.0135
1056   I   0.200     0.155   0.040        0.0435          0.0155
1057   I   0.225     0.165   0.055        0.0590          0.0270
1058   I   0.245     0.180   0.065        0.0710          0.0300
1059   I   0.250     0.180   0.065        0.0685          0.0245

      Viscera weight  Shell weight  Rings
1050          0.3830        0.4050     11
1051          0.4400        0.6000     11
1052          0.5090        0.6205     12
1053          0.0075        0.0095      4
1054          0.0060        0.0110      3
1055          0.0050        0.0095      4
1056          0.0090        0.0070      4
1057          0.0125        0.0150      4
1058          0.0130        0.0215      4
1059          0.0155        0.0225      5
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1060   I   0.265     0.195   0.055        0.0840          0.0365
1061   I   0.275     0.195   0.065        0.1060          0.0540
1062   I   0.280     0.210   0.085        0.1075          0.0415
1063   I   0.285     0.220   0.065        0.0960          0.0405
1064   I   0.300     0.220   0.080        0.1255          0.0550
1065   I   0.315     0.235   0.055        0.1510          0.0650
1066   I   0.320     0.225   0.085        0.1415          0.0675
1067   I   0.340     0.265   0.080        0.2015          0.0900
1068   I   0.370     0.280   0.100        0.2210          0.1165
1069   I   0.375     0.280   0.080        0.2345          0.1125

      Viscera weight  Shell weight  Rings
1060          0.0175        0.0250      7
1061          0.0200        0.0280      6
1062          0.0240        0.0340      5
1063          0.0205        0.0300      5
1064          0.0265        0.0390      6
1065          0.0270        0.0390      6
1066          0.0295        0.0405      6
1067          0.0475        0.0550      5
1068          0.0265        0.0635      6
1069          0.0455        0.0670      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1070   I   0.375     0.275   0.100        0.2325          0.1165
1071   I   0.385     0.290   0.080        0.2485          0.1220
1072   I   0.400     0.320   0.095        0.3480          0.1940
1073   I   0.405     0.300   0.110        0.3200          0.1720
1074   I   0.410     0.300   0.100        0.2820          0.1255
1075   I   0.410     0.325   0.100        0.3245          0.1320
1076   I   0.420     0.300   0.105        0.3160          0.1255
1077   I   0.420     0.320   0.110        0.3625          0.1740
1078   I   0.420     0.310   0.095        0.2790          0.1255
1079   I   0.425     0.325   0.115        0.3685          0.1620

      Viscera weight  Shell weight  Rings
1070          0.0420        0.0650      6
1071          0.0495        0.0650      7
1072          0.0530        0.0870      6
1073          0.0440        0.0930      7
1074          0.0570        0.0875      7
1075          0.0720        0.1060      6
1076          0.0700        0.1035      7
1077          0.0635        0.1050      7
1078          0.0510        0.0880      6
1079          0.0865        0.1045      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1080   M   0.430     0.335   0.120        0.3970          0.1985
1081   I   0.435     0.330   0.110        0.4130          0.2055
1082   I   0.435     0.345   0.115        0.4180          0.2220
1083   I   0.440     0.330   0.110        0.3705          0.1545
1084   I   0.445     0.345   0.105        0.4090          0.1675
1085   I   0.445     0.340   0.145        0.4340          0.1945
1086   I   0.445     0.335   0.110        0.4110          0.1985
1087   I   0.450     0.365   0.125        0.4620          0.2135
1088   I   0.450     0.340   0.120        0.4925          0.2410
1089   I   0.450     0.330   0.105        0.3715          0.1865

      Viscera weight  Shell weight  Rings
1080          0.0865        0.1035      7
1081          0.0960        0.0960      6
1082          0.0735        0.1060      7
1083          0.0840        0.1200      7
1084          0.1015        0.1170      7
1085          0.0905        0.1300      7
1086          0.0935        0.1090      8
1087          0.0985        0.1315      8
1088          0.1075        0.1200      6
1089          0.0785        0.0975      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1090   I   0.450     0.330   0.100        0.4110          0.1945
1091   I   0.450     0.330   0.110        0.3685          0.1600
1092   I   0.460     0.350   0.115        0.4155          0.1800
1093   M   0.470     0.360   0.105        0.5440          0.2700
1094   I   0.470     0.380   0.125        0.4845          0.2110
1095   I   0.475     0.350   0.110        0.4565          0.2060
1096   I   0.475     0.350   0.100        0.4545          0.2165
1097   I   0.480     0.380   0.125        0.6245          0.3395
1098   M   0.490     0.465   0.125        0.5225          0.2350
1099   I   0.500     0.375   0.140        0.5495          0.2480

      Viscera weight  Shell weight  Rings
1090          0.1000        0.0980      6
1091          0.0885        0.1020      6
1092          0.0980        0.1175      7
1093          0.1395        0.1290      7
1094          0.1075        0.1420      6
1095          0.0990        0.1300      6
1096          0.1110        0.1150      7
1097          0.1085        0.1665      8
1098          0.1300        0.1410      7
1099          0.1120        0.1585      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1100   I   0.500     0.375   0.120        0.5420          0.2150
1101   I   0.500     0.380   0.125        0.5190          0.2485
1102   M   0.500     0.390   0.125        0.5215          0.2485
1103   F   0.505     0.390   0.125        0.5445          0.2460
1104   I   0.510     0.405   0.125        0.6795          0.3465
1105   F   0.510     0.400   0.125        0.5450          0.2610
1106   I   0.510     0.400   0.125        0.5575          0.2615
1107   I   0.510     0.380   0.115        0.5155          0.2150
1108   I   0.515     0.385   0.125        0.6115          0.3175
1109   M   0.520     0.400   0.145        0.7765          0.3525

      Viscera weight  Shell weight  Rings
1100          0.1160        0.1700      9
1101          0.1135        0.1340      8
1102          0.1170        0.1310      6
1103          0.1500        0.1405      7
1104          0.1395        0.1820      8
1105          0.1150        0.1385      6
1106          0.1195        0.1525      9
1107          0.1135        0.1660      8
1108          0.1265        0.1500      8
1109          0.1845        0.1850      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1110   I   0.520     0.380   0.135        0.5395          0.2295
1111   I   0.520     0.380   0.125        0.5545          0.2880
1112   F   0.520     0.460   0.150        1.0190          0.5230
1113   I   0.525     0.400   0.130        0.6455          0.3250
1114   I   0.525     0.400   0.140        0.6010          0.2625
1115   M   0.525     0.405   0.120        0.7555          0.3755
1116   I   0.525     0.395   0.120        0.6080          0.2970
1117   I   0.530     0.400   0.125        0.6170          0.2790
1118   I   0.535     0.390   0.125        0.5990          0.2595
1119   I   0.540     0.420   0.140        0.6665          0.3125

      Viscera weight  Shell weight  Rings
1110          0.1330        0.1570      8
1111          0.1295        0.1670      8
1112          0.1985        0.2540      7
1113          0.1245        0.1700      8
1114          0.1285        0.1835      9
1115          0.1555        0.2010      9
1116          0.1395        0.1405      8
1117          0.1270        0.1900      8
1118          0.1490        0.1690      9
1119          0.1380        0.1895     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1120   M   0.545     0.390   0.135        0.7835          0.4225
1121   M   0.545     0.410   0.120        0.7930          0.4340
1122   M   0.545     0.415   0.140        0.8200          0.4615
1123   F   0.550     0.415   0.135        0.8145          0.4270
1124   F   0.550     0.430   0.150        0.8400          0.3950
1125   M   0.550     0.425   0.150        0.8315          0.4110
1126   M   0.560     0.430   0.145        0.8995          0.4640
1127   M   0.560     0.445   0.160        0.8965          0.4200
1128   F   0.560     0.440   0.155        0.6405          0.3360
1129   M   0.560     0.415   0.145        0.8520          0.4300

      Viscera weight  Shell weight  Rings
1120          0.1815        0.1560      7
1121          0.1405        0.1900      9
1122          0.1270        0.2180      9
1123          0.1855        0.1750      8
1124          0.1950        0.2230      8
1125          0.1765        0.2165     10
1126          0.1775        0.2340      9

(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1300   I   0.530     0.425   0.130        0.7675          0.4190
1301   I   0.535     0.400   0.135        0.6025          0.2895
1302   I   0.535     0.415   0.150        0.5765          0.3595
1303   F   0.535     0.410   0.130        0.7145          0.3350
1304   M   0.535     0.435   0.150        0.7170          0.3475
1305   F   0.540     0.420   0.145        0.8655          0.4315
1306   I   0.540     0.420   0.140        0.7265          0.3205
1307   I   0.545     0.435   0.135        0.7715          0.3720
1308   F   0.545     0.445   0.150        0.8000          0.3535
1309   I   0.545     0.430   0.150        0.7285          0.3020

      Viscera weight  Shell weight  Rings
1300          0.1205        0.2100      9
1301          0.1210        0.1540      9
1302          0.1350        0.2250      8
1303          0.1440        0.2075      9
1304          0.1445        0.1940      9
1305          0.1630        0.2175     10
1306          0.1445        0.2290      9
1307          0.1480        0.2270      8
1308          0.1630        0.2070      9
1309          0.1315        0.2545     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1310   I   0.545     0.405   0.135        0.5945          0.2700
1311   I   0.550     0.430   0.145        0.7895          0.3745
1312   F   0.550     0.405   0.125        0.6510          0.2965
1313   M   0.550     0.430   0.150        0.8745          0.4130
1314   I   0.550     0.435   0.140        0.7535          0.3285
1315   I   0.550     0.425   0.135        0.7305          0.3325
1316   M   0.555     0.440   0.140        0.8705          0.4070
1317   I   0.555     0.430   0.155        0.7395          0.3135
1318   I   0.555     0.430   0.140        0.7665          0.3410
1319   I   0.555     0.425   0.145        0.7905          0.3485

      Viscera weight  Shell weight  Rings
1310          0.1185        0.1850      8
1311          0.1710        0.2230     11
1312          0.1370        0.2000      9
1313          0.1905        0.2480      9
1314          0.1555        0.2325     10
1315          0.1545        0.2150      9
1316          0.1560        0.2550      9
1317          0.1435        0.2800     10
1318          0.1650        0.2300      9
1319          0.1765        0.2250      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1320   I   0.560     0.425   0.135        0.8205          0.3715
1321   I   0.560     0.425   0.145        0.6880          0.3095
1322   F   0.560     0.445   0.155        1.2240          0.5565
1323   I   0.560     0.455   0.145        0.9740          0.5470
1324   I   0.565     0.440   0.175        0.8735          0.4140
1325   F   0.565     0.450   0.145        0.8495          0.4215
1326   M   0.565     0.445   0.150        0.7960          0.3635
1327   M   0.565     0.390   0.125        0.7440          0.3520
1328   I   0.570     0.450   0.145        0.7510          0.2825
1329   I   0.570     0.450   0.135        0.7940          0.3815

      Viscera weight  Shell weight  Rings
1320          0.1850        0.2360      9
1321          0.1305        0.2165      9
1322          0.3225        0.2695     10
1323          0.1615        0.2350      9
1324          0.2100        0.2100     11
1325          0.1685        0.2250      8
1326          0.1840        0.2190      8
1327          0.1300        0.1685     11
1328          0.2195        0.2215     10
1329          0.1415        0.2450      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1330   F   0.570     0.460   0.135        0.9795          0.3970
1331   M   0.570     0.435   0.170        0.8730          0.3820
1332   I   0.570     0.440   0.130        0.7665          0.3470
1333   M   0.570     0.435   0.125        0.8965          0.3830
1334   F   0.575     0.420   0.135        0.8570          0.4610
1335   F   0.575     0.480   0.165        1.0780          0.5110
1336   M   0.575     0.460   0.155        0.8920          0.4415
1337   M   0.580     0.460   0.155        1.4395          0.6715
1338   M   0.580     0.455   0.135        0.7955          0.4050
1339   F   0.580     0.445   0.150        0.8580          0.4000

      Viscera weight  Shell weight  Rings
1330          0.2525        0.2655      9
1331          0.1830        0.2705     10
1332          0.1785        0.2020     10
1333          0.1835        0.2750      9
1334          0.1470        0.2125     10
1335          0.2095        0.3060      9
1336          0.1760        0.2200     10
1337          0.2730        0.2955     10
1338          0.1670        0.2040     10
1339          0.1560        0.2530      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1340   M   0.585     0.465   0.155        0.9145          0.4555
1341   M   0.585     0.490   0.185        1.1710          0.5220
1342   I   0.585     0.475   0.160        1.0505          0.4800
1343   M   0.585     0.460   0.165        1.1135          0.5825
1344   M   0.585     0.470   0.165        1.4090          0.8000
1345   M   0.585     0.475   0.150        1.0650          0.5315
1346   M   0.585     0.450   0.180        0.7995          0.3360
1347   I   0.590     0.445   0.135        0.7715          0.3280
1348   M   0.590     0.470   0.180        1.1870          0.5985
1349   M   0.590     0.455   0.155        0.8855          0.3880

      Viscera weight  Shell weight  Rings
1340          0.1965        0.2350      9
1341          0.2535        0.3350     10
1342          0.2340        0.2850     10
1343          0.2345        0.2740     10
1344          0.2290        0.2950     10
1345          0.1990        0.2885     10
1346          0.1855        0.2370      8
1347          0.1745        0.2300      9
1348          0.2270        0.3100      9
1349          0.1880        0.2750     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1350   F   0.595     0.465   0.150        0.9800          0.4115
1351   F   0.595     0.465   0.155        1.0260          0.4645
1352   M   0.600     0.475   0.170        1.1315          0.5080
1353   M   0.600     0.480   0.155        1.0140          0.4510
1354   I   0.600     0.475   0.150        1.1200          0.5650
1355   F   0.600     0.465   0.155        1.0400          0.4755
1356   F   0.600     0.455   0.145        0.8895          0.4190
1357   M   0.600     0.460   0.155        0.9595          0.4455
1358   I   0.605     0.485   0.150        1.2380          0.6315
1359   M   0.605     0.490   0.140        0.9755          0.4190

      Viscera weight  Shell weight  Rings
1350          0.1960        0.2255     10
1351          0.1120        0.3050     12
1352          0.2720        0.3090     10
1353          0.1885        0.3250     11
1354          0.2465        0.2700     10
1355          0.2500        0.2800     11
1356          0.1715        0.2690     10
1357          0.1890        0.2950     11
1358          0.2260        0.3300     11
1359          0.2060        0.3150     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1360   I   0.605     0.435   0.130        0.9025          0.4320
1361   F   0.605     0.475   0.175        1.0760          0.4630
1362   F   0.605     0.470   0.160        1.0835          0.5405
1363   M   0.610     0.450   0.150        0.8710          0.4070
1364   M   0.610     0.480   0.165        1.2440          0.6345
1365   M   0.610     0.475   0.170        1.0265          0.4350
1366   I   0.610     0.465   0.150        0.9605          0.4495
1367   M   0.610     0.480   0.170        1.1370          0.4565
1368   M   0.610     0.460   0.160        1.0000          0.4940
1369   F   0.615     0.475   0.155        1.0040          0.4475

      Viscera weight  Shell weight  Rings
1360          0.1740        0.2600     11
1361          0.2195        0.3350      9
1362          0.2215        0.2750     12
1363          0.1835        0.2500     10
1364          0.2570        0.3050     12
1365          0.2335        0.3035     10
1366          0.1725        0.2860      9
1367          0.2900        0.3470     10
1368          0.1970        0.2750     10
1369          0.1930        0.2895     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1370   M   0.615     0.470   0.165        1.1280          0.4465
1371   M   0.615     0.500   0.170        1.0540          0.4845
1372   F   0.615     0.475   0.165        1.0230          0.4905
1373   M   0.615     0.475   0.170        1.1290          0.4795
1374   M   0.615     0.480   0.175        1.1180          0.4460
1375   F   0.615     0.475   0.155        1.1150          0.4840
1376   M   0.620     0.510   0.175        1.2815          0.5715
1377   M   0.620     0.495   0.180        1.2555          0.5765
1378   F   0.620     0.500   0.150        1.2930          0.5960
1379   F   0.620     0.475   0.160        1.1295          0.4630

      Viscera weight  Shell weight  Rings
1370          0.2195        0.3400     10
1371          0.2280        0.2950     10
1372          0.1955        0.3035     12
1373          0.3020        0.3000     10
1374          0.3195        0.3000      9
1375          0.2115        0.3550     10
1376          0.2385        0.3900     10
1377          0.2540        0.3550     12
1378          0.3135        0.3540     10
1379          0.2685        0.3300     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1380   M   0.625     0.455   0.170        1.0820          0.4955
1381   F   0.625     0.505   0.175        1.1500          0.5475
1382   F   0.625     0.515   0.160        1.2640          0.5715
1383   F   0.625     0.480   0.155        1.2035          0.5865
1384   F   0.630     0.485   0.170        1.3205          0.5945
1385   I   0.630     0.505   0.180        1.2720          0.6025
1386   M   0.630     0.485   0.145        1.0620          0.5065
1387   I   0.630     0.475   0.145        1.0605          0.5165
1388   M   0.630     0.495   0.160        1.0930          0.4970
1389   M   0.635     0.490   0.160        1.1010          0.5340

      Viscera weight  Shell weight  Rings
1380          0.2345        0.3150      9
1381          0.2560        0.3045     11
1382          0.3260        0.3210      9
1383          0.2390        0.3185     12
1384          0.3450        0.3450      9
1385          0.2950        0.3150     11
1386          0.1785        0.3365     12
1387          0.2195        0.2800     10
1388          0.2210        0.3150     12
1389          0.1865        0.3455     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1390   F   0.635     0.500   0.165        1.4595          0.7050
1391   F   0.635     0.495   0.175        1.2110          0.7070
1392   M   0.635     0.475   0.170        1.1935          0.5205
1393   M   0.635     0.510   0.155        0.9860          0.4050
1394   M   0.640     0.565   0.230        1.5210          0.6440
1395   M   0.640     0.525   0.180        1.3135          0.4865
1396   M   0.645     0.510   0.160        1.1835          0.5560
1397   M   0.645     0.500   0.195        1.4010          0.6165
1398   M   0.645     0.525   0.160        1.5075          0.7455
1399   F   0.650     0.505   0.165        1.1600          0.4785

      Viscera weight  Shell weight  Rings
1390          0.2645        0.3900      9
1391          0.2725        0.3230      9
1392          0.2695        0.3665     10
1393          0.2255        0.3100     10
1394          0.3720        0.4060     15
1395          0.2995        0.4075     10
1396          0.2385        0.3450     11
1397          0.3515        0.3725     10
1398          0.2450        0.4325     11
1399          0.2740        0.3490     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1400   F   0.650     0.590   0.220        1.6620          0.7700
1401   M   0.650     0.525   0.175        1.5365          0.6865
1402   M   0.650     0.510   0.190        1.5420          0.7155
1403   F   0.650     0.510   0.170        1.5670          0.7245
1404   F   0.655     0.525   0.190        1.3595          0.5640
1405   M   0.655     0.535   0.205        1.6445          0.7305
1406   F   0.655     0.520   0.190        1.4545          0.6000
1407   M   0.655     0.490   0.175        1.3585          0.6395
1408   F   0.660     0.495   0.210        1.5480          0.7240
1409   F   0.660     0.515   0.170        1.3370          0.6150

      Viscera weight  Shell weight  Rings
1400          0.3780        0.4350     11
1401          0.3585        0.4050     11
1402          0.3735        0.3750      9
1403          0.3490        0.3910     10
1404          0.3215        0.3985     10
1405          0.3595        0.4600     13
1406          0.3865        0.3830     10
1407          0.2940        0.3650     10
1408          0.3525        0.3925     10
1409          0.3125        0.3575     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1410   F   0.665     0.530   0.180        1.4910          0.6345
1411   F   0.670     0.530   0.225        1.5615          0.6300
1412   F   0.670     0.505   0.175        1.0145          0.4375
1413   M   0.675     0.545   0.185        1.7375          0.8760
1414   M   0.685     0.545   0.205        1.7925          0.8145
1415   F   0.695     0.565   0.190        1.7635          0.7465
1416   F   0.700     0.545   0.130        1.5560          0.6725
1417   M   0.705     0.565   0.515        2.2100          1.1075
1418   M   0.705     0.555   0.215        2.1410          1.0465
1419   F   0.705     0.570   0.180        1.5345          0.9600

      Viscera weight  Shell weight  Rings
1410          0.3420        0.4350     10
1411          0.4870        0.3725     11
1412          0.2710        0.3745     10
1413          0.3135        0.4690     13
1414          0.4160        0.4610      9
1415          0.3990        0.4975     11
1416          0.3740        0.1950     12
1417          0.4865        0.5120     10
1418          0.3830        0.5280     11
1419          0.4195        0.4300     12
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1420   F   0.710     0.550   0.170        1.6140          0.7430
1421   F   0.720     0.575   0.170        1.9335          0.9130
1422   M   0.720     0.575   0.215        2.1730          0.9515
1423   F   0.725     0.600   0.200        1.7370          0.6970
1424   F   0.730     0.580   0.190        1.7375          0.6785
1425   F   0.735     0.565   0.205        2.1275          0.9490
1426   F   0.745     0.570   0.215        2.2500          1.1565
1427   F   0.750     0.610   0.235        2.5085          1.2320
1428   F   0.815     0.650   0.250        2.2550          0.8905
1429   I   0.140     0.105   0.035        0.0140          0.0055

      Viscera weight  Shell weight  Rings
1420          0.3450        0.4500     11
1421          0.3890        0.5100     13
1422          0.5640        0.5365     12
1423          0.3585        0.5950     11
1424          0.4345        0.5200     11
1425          0.4600        0.5650     12
1426          0.4460        0.5580      9
1427          0.5190        0.6120     14
1428          0.4200        0.7975     14
1429          0.0025        0.0040      3
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1430   I   0.230     0.165   0.060        0.0515          0.0190
1431   I   0.365     0.265   0.135        0.2215          0.1050
1432   I   0.365     0.255   0.080        0.1985          0.0785
1433   I   0.370     0.270   0.095        0.2320          0.1325
1434   I   0.375     0.280   0.085        0.3155          0.1870
1435   I   0.385     0.300   0.090        0.2470          0.1225
1436   I   0.395     0.295   0.090        0.3025          0.1430
1437   I   0.400     0.290   0.110        0.3290          0.1880
1438   I   0.400     0.300   0.090        0.2815          0.1185
1439   I   0.405     0.310   0.095        0.3425          0.1785

      Viscera weight  Shell weight  Rings
1430          0.0145        0.0360      4
1431          0.0470        0.0605      7
1432          0.0345        0.0530      5
1433          0.0410        0.0615      6
1434          0.0460        0.0670      7
1435          0.0440        0.0675      5
1436          0.0665        0.0765      5
1437          0.0455        0.0825      6
1438          0.0610        0.0800      7
1439          0.0640        0.0855      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1440   I   0.405     0.290   0.090        0.2825          0.1120
1441   I   0.405     0.300   0.105        0.3040          0.1455
1442   I   0.410     0.320   0.095        0.2905          0.1410
1443   M   0.415     0.315   0.115        0.3895          0.2015
1444   I   0.425     0.340   0.105        0.3890          0.2015
1445   I   0.430     0.340   0.105        0.4405          0.2385
1446   I   0.440     0.340   0.105        0.3690          0.1640
1447   M   0.440     0.320   0.120        0.4565          0.2435
1448   I   0.440     0.365   0.110        0.4465          0.2130
1449   M   0.450     0.335   0.125        0.4475          0.2165

      Viscera weight  Shell weight  Rings
1440          0.0750        0.0815      7
1441          0.0610        0.0805      6
1442          0.0630        0.0730      5
1443          0.0650        0.1030      9
1444          0.0905        0.0880      6
1445          0.0745        0.1075      6
1446          0.0800        0.1015      5
1447          0.0920        0.1025      8
1448          0.0890        0.1135      9
1449          0.1260        0.1100      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1450   I   0.455     0.335   0.135        0.5010          0.2740
1451   I   0.460     0.355   0.110        0.4360          0.1975
1452   I   0.470     0.345   0.140        0.4615          0.2290
1453   I   0.470     0.350   0.125        0.4315          0.1900
1454   I   0.470     0.355   0.120        0.3685          0.1260
1455   M   0.475     0.370   0.125        0.6490          0.3470
1456   I   0.475     0.365   0.115        0.4590          0.2175
1457   F   0.475     0.365   0.115        0.5660          0.2810
1458   I   0.480     0.360   0.125        0.5420          0.2795
1459   I   0.485     0.380   0.120        0.4725          0.2075

      Viscera weight  Shell weight  Rings
1450          0.0995        0.1065      7
1451          0.0960        0.1250      8
1452          0.1105        0.1160      9
1453          0.1165        0.1175      6
1454          0.0835        0.1365      6
1455          0.1360        0.1420      8
1456          0.0930        0.1165      7
1457          0.1170        0.1335      7
1458          0.1025        0.1470      7
1459          0.1075        0.1470      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1460   M   0.485     0.390   0.085        0.6435          0.2945
1461   M   0.485     0.370   0.130        0.5260          0.2485
1462   F   0.495     0.380   0.120        0.5730          0.2655
1463   M   0.505     0.385   0.105        0.5525          0.2390
1464   F   0.505     0.380   0.135        0.6855          0.3610
1465   I   0.515     0.395   0.125        0.5560          0.2695
1466   M   0.515     0.425   0.145        0.9365          0.4970
1467   I   0.515     0.400   0.125        0.5625          0.2500
1468   M   0.520     0.400   0.125        0.5590          0.2540
1469   M   0.525     0.400   0.140        0.7205          0.3685

      Viscera weight  Shell weight  Rings
1460          0.1030        0.1980      8
1461          0.1050        0.1555      6
1462          0.1285        0.1440      7
1463          0.1245        0.1555      9

1639          0.1760        0.2540     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1640   F   0.575     0.435   0.150        1.0305          0.4605
1641   M   0.575     0.445   0.160        0.8390          0.4005
1642   M   0.575     0.440   0.160        0.9615          0.4830
1643   F   0.580     0.435   0.150        0.8340          0.4280
1644   M   0.580     0.460   0.155        1.0335          0.4690
1645   M   0.580     0.430   0.130        0.7980          0.3650
1646   I   0.580     0.445   0.125        0.7095          0.3030
1647   F   0.585     0.445   0.140        0.9130          0.4305
1648   M   0.590     0.490   0.165        1.2070          0.5590
1649   I   0.590     0.450   0.145        1.0220          0.4280

      Viscera weight  Shell weight  Rings
1640          0.2180        0.3600      8
1641          0.1980        0.2390      9
1642          0.1660        0.2750     13
1643          0.1515        0.2300      8
1644          0.2225        0.2950     10
1645          0.1730        0.2285     10
1646          0.1405        0.2350      9
1647          0.2205        0.2530     10
1648          0.2350        0.3090     10
1649          0.2680        0.2650     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1650   I   0.590     0.460   0.145        0.9015          0.4190
1651   F   0.595     0.435   0.150        0.9000          0.4175
1652   M   0.595     0.450   0.140        0.8380          0.3965
1653   M   0.595     0.450   0.145        0.9590          0.4630
1654   I   0.595     0.460   0.150        0.8335          0.3770
1655   F   0.600     0.460   0.155        0.9735          0.4270
1656   F   0.600     0.475   0.150        1.1300          0.5750
1657   M   0.600     0.480   0.165        0.9165          0.4135
1658   I   0.600     0.480   0.170        0.9175          0.3800
1659   F   0.600     0.480   0.180        1.0645          0.4495

      Viscera weight  Shell weight  Rings
1650          0.1785        0.2600     11
1651          0.1700        0.2650      8
1652          0.1940        0.2170     10
1653          0.2065        0.2535     10
1654          0.1925        0.2350      8
1655          0.2045        0.3000      8
1656          0.1960        0.3050      9
1657          0.1965        0.2725      9
1658          0.2225        0.2900      8
1659          0.2455        0.3250     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1660   M   0.600     0.470   0.165        1.0590          0.5040
1661   M   0.600     0.470   0.160        1.1940          0.5625
1662   F   0.605     0.455   0.145        0.9775          0.4680
1663   M   0.605     0.475   0.145        0.8840          0.3835
1664   I   0.605     0.470   0.145        0.8025          0.3790
1665   F   0.605     0.480   0.140        0.9910          0.4735
1666   F   0.605     0.470   0.155        0.9740          0.3930
1667   F   0.605     0.505   0.180        1.4340          0.7285
1668   M   0.610     0.475   0.155        0.9830          0.4565
1669   F   0.610     0.465   0.160        1.0725          0.4835

      Viscera weight  Shell weight  Rings
1660          0.2410        0.2750      9
1661          0.3045        0.2635     10
1662          0.1775        0.2750      9
1663          0.1905        0.2700      8
1664          0.2265        0.2200      9
1665          0.2345        0.2400      8
1666          0.2240        0.3345      9
1667          0.2640        0.4310     11
1668          0.2280        0.2660     10
1669          0.2515        0.2800     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1670   F   0.610     0.485   0.150        1.2405          0.6025
1671   M   0.610     0.470   0.160        1.0220          0.4490
1672   F   0.610     0.475   0.160        1.1155          0.3835
1673   I   0.610     0.465   0.125        0.9225          0.4360
1674   M   0.610     0.470   0.170        1.1185          0.5225
1675   F   0.610     0.485   0.180        1.2795          0.5735
1676   M   0.615     0.470   0.160        1.0175          0.4730
1677   M   0.615     0.475   0.175        1.2240          0.6035
1678   I   0.620     0.485   0.180        1.1540          0.4935
1679   F   0.620     0.515   0.155        1.3255          0.6685

      Viscera weight  Shell weight  Rings
1670          0.2915        0.3085     12
1671          0.2345        0.2945      9
1672          0.2230        0.3790     10
1673          0.1900        0.2600      9
1674          0.2405        0.3100      9
1675          0.2855        0.3550      7
1676          0.2395        0.2800     10
1677          0.2610        0.3110      9
1678          0.2560        0.3150     12
1679          0.2605        0.3350     12
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1680   M   0.620     0.515   0.175        1.2210          0.5350
1681   F   0.620     0.540   0.165        1.1390          0.4995
1682   I   0.620     0.490   0.160        1.0660          0.4460
1683   F   0.620     0.480   0.180        1.2215          0.5820
1684   I   0.620     0.470   0.140        0.8565          0.3595
1685   I   0.620     0.450   0.135        0.9240          0.3580
1686   M   0.620     0.480   0.150        1.2660          0.6285
1687   F   0.620     0.480   0.175        1.0405          0.4640
1688   M   0.625     0.490   0.165        1.1165          0.4895
1689   M   0.625     0.475   0.160        1.0845          0.5005

      Viscera weight  Shell weight  Rings
1680          0.2410        0.3950     13
1681          0.2435        0.3570     11
1682          0.2460        0.3050     11
1683          0.2695        0.3130     12
1684          0.1600        0.2950      9
1685          0.2265        0.2965     10
1686          0.2575        0.3090     12
1687          0.2225        0.3000      9
1688          0.2615        0.3325     11
1689          0.2355        0.3105     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1690   M   0.625     0.500   0.170        1.0985          0.4645
1691   I   0.625     0.470   0.155        1.1955          0.6430
1692   F   0.625     0.485   0.175        1.3620          0.6765
1693   I   0.625     0.485   0.150        1.0440          0.4380
1694   M   0.630     0.505   0.170        1.0915          0.4615
1695   F   0.630     0.500   0.180        1.1965          0.5140
1696   M   0.630     0.490   0.170        1.1745          0.5255
1697   M   0.630     0.485   0.165        1.2330          0.6565
1698   M   0.630     0.495   0.175        1.2695          0.6050
1699   I   0.635     0.500   0.165        1.4890          0.7150

      Viscera weight  Shell weight  Rings
1690          0.2200        0.3540      9
1691          0.2055        0.3145     12
1692          0.2615        0.3705     10
1693          0.2865        0.2780      9
1694          0.2660        0.3000      9
1695          0.2325        0.3995      8
1696          0.2730        0.3390     11
1697          0.2315        0.3035     10
1698          0.2710        0.3280     11
1699          0.3445        0.3615     13
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1700   M   0.635     0.500   0.170        1.4345          0.6110
1701   F   0.635     0.490   0.175        1.2435          0.5805
1702   F   0.635     0.490   0.170        1.2615          0.5385
1703   F   0.640     0.505   0.165        1.2235          0.5215
1704   M   0.640     0.515   0.180        1.2470          0.5475
1705   M   0.640     0.525   0.185        1.7070          0.7630
1706   M   0.645     0.505   0.150        1.1605          0.5190
1707   M   0.645     0.500   0.175        1.2860          0.5645
1708   M   0.645     0.500   0.190        1.5595          0.7410
1709   M   0.645     0.510   0.190        1.4745          0.6050

      Viscera weight  Shell weight  Rings
1700          0.3090        0.4180     12
1701          0.3130        0.3050     10
1702          0.2665        0.3800      9
1703          0.2695        0.3600     10
1704          0.2925        0.3685     10
1705          0.4205        0.4435     11
1706          0.2615        0.3350     10
1707          0.2880        0.3860     12
1708          0.3715        0.3845     14
1709          0.3450        0.4800      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1710   M   0.645     0.510   0.195        1.2260          0.5885
1711   M   0.645     0.510   0.160        1.3300          0.6665
1712   F   0.645     0.510   0.160        1.2415          0.5815
1713   M   0.645     0.500   0.175        1.3375          0.5540
1714   F   0.645     0.510   0.190        1.3630          0.5730
1715   M   0.645     0.485   0.150        1.2215          0.5695
1716   F   0.645     0.480   0.190        1.3710          0.6925
1717   F   0.650     0.495   0.155        1.3370          0.6150
1718   M   0.650     0.505   0.190        1.2740          0.5900
1719   M   0.650     0.525   0.185        1.4880          0.6650

      Viscera weight  Shell weight  Rings
1710          0.2215        0.3745     10
1711          0.3090        0.3170      9
1712          0.2760        0.3150      9
1713          0.3080        0.4150     10
1714          0.3620        0.3600     10
1715          0.2735        0.3300      9
1716          0.2905        0.3500     12
1717          0.3195        0.3350      9
1718          0.2300        0.3910     11
1719          0.3370        0.3780     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1720   M   0.650     0.510   0.160        1.3835          0.6385
1721   M   0.655     0.550   0.180        1.2740          0.5860
1722   F   0.655     0.510   0.150        1.0430          0.4795
1723   F   0.655     0.505   0.190        1.3485          0.5935
1724   F   0.655     0.505   0.195        1.4405          0.6880
1725   M   0.660     0.500   0.165        1.3195          0.6670
1726   F   0.660     0.535   0.175        1.5175          0.7110
1727   M   0.660     0.530   0.195        1.5505          0.6505
1728   M   0.660     0.510   0.165        1.6375          0.7685
1729   M   0.665     0.525   0.175        1.4430          0.6635

      Viscera weight  Shell weight  Rings
1720          0.2905        0.3665      9
1721          0.2810        0.3650     10
1722          0.2230        0.3050      9
1723          0.2745        0.4250     12
1724          0.3805        0.3630     11
1725          0.2690        0.3410      9
1726          0.3125        0.4150     12
1727          0.3295        0.4950     10
1728          0.3545        0.3925     14
1729          0.3845        0.3530     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1730   M   0.665     0.505   0.160        1.2890          0.6145
1731   F   0.665     0.505   0.160        1.2915          0.6310
1732   M   0.665     0.520   0.175        1.3725          0.6060
1733   M   0.665     0.500   0.175        1.2975          0.6075
1734   M   0.670     0.505   0.160        1.2585          0.6255
1735   M   0.670     0.520   0.165        1.3900          0.7110
1736   F   0.670     0.520   0.190        1.3200          0.5235
1737   F   0.670     0.550   0.155        1.5660          0.8580
1738   F   0.670     0.540   0.195        1.6190          0.7400
1739   M   0.675     0.525   0.160        1.2835          0.5720

      Viscera weight  Shell weight  Rings
1730          0.2530        0.3665     11
1731          0.2925        0.3200     11
1732          0.3200        0.3950     12
1733          0.3140        0.3150      9
1734          0.3110        0.3080     12
1735          0.2865        0.3000     11
1736          0.3095        0.4275     13
1737          0.3390        0.3540     10
1738          0.3305        0.4650     11
1739          0.2755        0.3545     13
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1740   F   0.675     0.510   0.195        1.3820          0.6045
1741   M   0.680     0.520   0.195        1.4535          0.5920
1742   F   0.680     0.510   0.200        1.6075          0.7140
1743   M   0.685     0.520   0.150        1.3735          0.7185
1744   F   0.685     0.565   0.175        1.6380          0.7775
1745   F   0.690     0.550   0.200        1.5690          0.6870
1746   M   0.700     0.565   0.175        1.8565          0.8445
1747   F   0.700     0.535   0.175        1.7730          0.6805
1748   F   0.705     0.545   0.170        1.5800          0.6435
1749   M   0.710     0.575   0.215        2.0090          0.9895

      Viscera weight  Shell weight  Rings
1740          0.3175        0.3965     10
1741          0.3910        0.4125     10
1742          0.3390        0.4705     11
1743          0.2930        0.3200     11
1744          0.3750        0.4380     11
1745          0.3675        0.4600     12
1746          0.3935        0.5400     10
1747          0.4800        0.5120     15
1748          0.4565        0.2650     11
1749          0.4475        0.5020     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1750   F   0.710     0.570   0.195        1.9805          0.9925
1751   F   0.710     0.540   0.205        1.5805          0.8020
1752   M   0.710     0.560   0.220        2.0150          0.9215
1753   M   0.720     0.570   0.200        1.8275          0.9190
1754   M   0.720     0.550   0.205        2.1250          1.1455
1755   F   0.720     0.525   0.180        1.4450          0.6310
1756   F   0.725     0.565   0.210        2.1425          1.0300
1757   F   0.730     0.560   0.190        1.9425          0.7990
1758   M   0.735     0.590   0.215        1.7470          0.7275
1759   F   0.740     0.565   0.205        2.1190          0.9655

      Viscera weight  Shell weight  Rings
1750          0.4925        0.4800     12
1751          0.2870        0.4350     10
1752          0.4540        0.5660     11
1753          0.3660        0.4850     10
1754          0.4425        0.5110     13
1755          0.3215        0.4350      7
1756          0.4870        0.5030     14
1757          0.5195        0.5655     11
1758          0.4030        0.5570     11
1759          0.5185        0.4820     12
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1760   F   0.750     0.565   0.215        1.9380          0.7735
1761   M   0.750     0.595   0.205        2.2205          1.0830
1762   M   0.770     0.620   0.195        2.5155          1.1155
1763   M   0.775     0.630   0.250        2.7795          1.3485
1764   I   0.275     0.175   0.090        0.2315          0.0960
1765   I   0.375     0.245   0.100        0.3940          0.1660
1766   F   0.375     0.270   0.135        0.5970          0.2720
1767   M   0.390     0.280   0.125        0.5640          0.3035
1768   I   0.435     0.300   0.120        0.5965          0.2590
1769   M   0.445     0.320   0.120        0.4140          0.1990

      Viscera weight  Shell weight  Rings
1760          0.4825        0.5750     11
1761          0.4210        0.6300     12
1762          0.6415        0.6420     12
1763          0.7600        0.5780     12
1764          0.0570        0.0705      5
1765          0.0910        0.1125      6
1766          0.1310        0.1675      7
1767          0.0955        0.1430      7
1768          0.1390        0.1645      8
1769          0.0900        0.1170      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1770   I   0.455     0.335   0.105        0.4220          0.2290
1771   I   0.455     0.325   0.135        0.8200          0.4005
1772   I   0.455     0.345   0.110        0.4340          0.2070
1773   I   0.465     0.325   0.140        0.7615          0.3620
1774   M   0.465     0.360   0.115        0.5795          0.2950
1775   I   0.485     0.365   0.105        0.5205          0.1950
1776   M   0.485     0.370   0.155        0.9680          0.4190
1777   I   0.485     0.345   0.160        0.8690          0.3085
1778   F   0.490     0.355   0.160        0.8795          0.3485
1779   M   0.500     0.370   0.150        1.0615          0.4940

      Viscera weight  Shell weight  Rings
1770          0.0865        0.1000      6
1771          0.1715        0.2110      8
1772          0.0855        0.1215      8
1773          0.1535        0.2090     10
1774          0.1395        0.1200      7
1775          0.1230        0.1820      8
1776          0.2455        0.2365      9
1777          0.1850        0.3190      9
1778          0.2150        0.2825      8
1779          0.2230        0.2960      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1780   M   0.515     0.350   0.155        0.9225          0.4185
1781   M   0.515     0.395   0.135        1.0070          0.4720
1782   M   0.525     0.365   0.170        0.9605          0.4380
1783   M   0.525     0.380   0.125        0.6500          0.3030
1784   M   0.530     0.410   0.140        0.7545          0.3495
1785   F   0.535     0.425   0.135        0.7710          0.3765
1786   I   0.535     0.385   0.180        1.0835          0.4955
1787   I   0.545     0.420   0.165        0.8935          0.4235
1788   F   0.545     0.415   0.200        1.3580          0.5670
1789   F   0.545     0.385   0.150        1.1185          0.5425

      Viscera weight  Shell weight  Rings
1780          0.1980        0.2730      9
1781          0.2495        0.2520      8
1782          0.2225        0.2760     10
1783          0.1550        0.1590      7
1784          0.1715        0.2105      8
1785          0.1815        0.1795      8
1786          0.2295        0.3040      8
1787          0.2195        0.2280      8
1788          0.3180        0.4030     10
1789          0.2445        0.2845      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1790   F   0.550     0.380   0.165        1.2050          0.5430
1791   M   0.550     0.420   0.160        1.3405          0.6325
1792   M   0.570     0.455   0.175        1.0200          0.4805
1793   M   0.575     0.440   0.185        1.0250          0.5075
1794   I   0.575     0.450   0.130        0.8145          0.4030
1795   F   0.580     0.430   0.170        1.4800          0.6535
1796   M   0.585     0.455   0.145        0.9530          0.3945
1797   I   0.585     0.450   0.150        0.8915          0.3975
1798   M   0.600     0.495   0.175        1.3005          0.6195
1799   M   0.600     0.465   0.165        1.0380          0.4975

      Viscera weight  Shell weight  Rings
1790          0.2940        0.3345     10
1791          0.3110        0.3440     10
1792          0.2145        0.2900      9
1793          0.2245        0.2485     10
1794          0.1715        0.2130     10
1795          0.3240        0.4155     10
1796          0.2685        0.2580     10
1797          0.2035        0.2530      8
1798          0.2840        0.3285     11
1799          0.2205        0.2510      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1800   M   0.605     0.475   0.175        1.2525          0.5575
1801   M   0.605     0.475   0.150        1.1500          0.5750
1802   F   0.610     0.475   0.150        1.1135          0.5195
1803   F   0.615     0.455   0.145        1.1155          0.5045
1804   M   0.620     0.470   0.145        1.0865          0.5110
1805   M   0.625     0.495   0.175        1.2540          0.5815
1806   M   0.625     0.490   0.185        1.1690          0.5275
1807   M   0.635     0.495   0.195        1.1720          0.4450
1808   F   0.635     0.475   0.150        1.1845          0.5330
1809   F   0.640     0.475   0.140        1.0725          0.4895

      Viscera weight  Shell weight  Rings
1800          0.3055        0.3430      9
1801          0.2320        0.2970     10
1802          0.2575        0.3005     11

1969          0.2465        0.4160     12
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1970   M   0.675     0.515   0.150        1.3120          0.5560
1971   F   0.675     0.510   0.185        1.4730          0.6295
1972   M   0.680     0.540   0.190        1.6230          0.7165
1973   M   0.680     0.540   0.155        1.5340          0.6710
1974   M   0.685     0.535   0.155        1.3845          0.6615
1975   M   0.690     0.550   0.180        1.6915          0.6655
1976   M   0.695     0.545   0.185        1.5715          0.6645
1977   F   0.700     0.575   0.205        1.7730          0.6050
1978   M   0.700     0.550   0.175        1.4405          0.6565
1979   M   0.700     0.550   0.195        1.6245          0.6750

      Viscera weight  Shell weight  Rings
1970          0.2845        0.4115     11
1971          0.3025        0.4245     11
1972          0.3540        0.4715     12
1973          0.3790        0.3840     10
1974          0.2145        0.4075     10
1975          0.4020        0.5000     11
1976          0.3835        0.4505     13
1977          0.4470        0.5380     13
1978          0.2985        0.3750     12
1979          0.3470        0.5350     13
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1980   F   0.705     0.535   0.220        1.8660          0.9290
1981   F   0.720     0.575   0.180        1.6705          0.7320
1982   M   0.720     0.565   0.190        2.0810          1.0815
1983   F   0.725     0.570   0.205        1.6195          0.7440
1984   F   0.750     0.550   0.195        1.8325          0.8300
1985   M   0.760     0.605   0.215        2.1730          0.8010
1986   I   0.135     0.130   0.040        0.0290          0.0125
1987   I   0.160     0.110   0.025        0.0195          0.0075
1988   I   0.210     0.150   0.055        0.0465          0.0170
1989   I   0.280     0.210   0.075        0.1195          0.0530

      Viscera weight  Shell weight  Rings
1980          0.3835        0.4395     10
1981          0.3605        0.5010     12
1982          0.4305        0.5030     11
1983          0.3150        0.4880     11
1984          0.3660        0.4400     11
1985          0.4915        0.6460     13
1986          0.0065        0.0080      4
1987          0.0050        0.0060      4
1988          0.0120        0.0150      5
1989          0.0265        0.0300      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1990   I   0.280     0.200   0.065        0.0895          0.0360
1991   I   0.285     0.215   0.060        0.0935          0.0310
1992   I   0.290     0.210   0.070        0.1115          0.0480
1993   I   0.290     0.210   0.060        0.1195          0.0560
1994   I   0.290     0.210   0.065        0.0970          0.0375
1995   I   0.320     0.240   0.070        0.1330          0.0585
1996   I   0.325     0.250   0.070        0.1745          0.0875
1997   I   0.335     0.250   0.080        0.1695          0.0695
1998   I   0.350     0.235   0.080        0.1700          0.0725
1999   I   0.350     0.250   0.070        0.1605          0.0715

      Viscera weight  Shell weight  Rings
1990          0.0185        0.0300      7
1991          0.0230        0.0300      6
1992          0.0205        0.0300      5
1993          0.0235        0.0300      6
1994          0.0220        0.0300      6
1995          0.0255        0.0410      6
1996          0.0355        0.0400      7
1997          0.0440        0.0495      6
1998          0.0465        0.0495      7
1999          0.0335        0.0460      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2000   I   0.355     0.270   0.105        0.2710          0.1425
2001   I   0.360     0.270   0.085        0.2185          0.1065
2002   I   0.360     0.270   0.085        0.1960          0.0905
2003   I   0.375     0.280   0.080        0.2260          0.1050
2004   I   0.375     0.275   0.085        0.2200          0.1090
2005   I   0.395     0.290   0.095        0.3000          0.1580
2006   I   0.405     0.250   0.090        0.2875          0.1280
2007   I   0.415     0.325   0.110        0.3160          0.1385
2008   I   0.425     0.315   0.095        0.3675          0.1865
2009   I   0.430     0.320   0.110        0.3675          0.1675

      Viscera weight  Shell weight  Rings
2000          0.0525        0.0735      9
2001          0.0380        0.0620      6
2002          0.0340        0.0530      7
2003          0.0470        0.0650      6
2004          0.0500        0.0605      7
2005          0.0680        0.0780      7
2006          0.0630        0.0805      7
2007          0.0795        0.0925      8
2008          0.0675        0.0985      7
2009          0.1020        0.1050      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2010   I   0.435     0.325   0.120        0.3460          0.1590
2011   M   0.450     0.330   0.105        0.4955          0.2575
2012   I   0.460     0.350   0.110        0.4675          0.2125
2013   M   0.470     0.365   0.135        0.5220          0.2395
2014   I   0.470     0.375   0.105        0.4410          0.1670
2015   I   0.475     0.365   0.120        0.5185          0.2680
2016   M   0.505     0.390   0.120        0.6530          0.3315
2017   M   0.505     0.395   0.135        0.5915          0.2880
2018   M   0.505     0.385   0.115        0.4825          0.2100
2019   I   0.510     0.455   0.135        0.6855          0.2875

      Viscera weight  Shell weight  Rings
2010          0.0840        0.0950      7
2011          0.0820        0.1290      8
2012          0.0990        0.1375      7
2013          0.1525        0.1450     10
2014          0.0865        0.1450     10
2015          0.1095        0.1365      8
2016          0.1385        0.1670      9
2017          0.1315        0.1850     12
2018          0.1035        0.1535     10
2019          0.1540        0.2035      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2020   M   0.515     0.400   0.140        0.6335          0.2880
2021   M   0.525     0.410   0.130        0.6875          0.3435
2022   F   0.530     0.430   0.150        0.7410          0.3250
2023   F   0.530     0.405   0.130        0.6355          0.2635
2024   M   0.545     0.440   0.140        0.8395          0.3560
2025   F   0.550     0.470   0.150        0.9205          0.3810
2026   F   0.560     0.410   0.160        0.8215          0.3420
2027   M   0.565     0.445   0.145        0.9255          0.4345
2028   F   0.570     0.435   0.150        0.8295          0.3875
2029   M   0.580     0.460   0.160        1.0630          0.5130

      Viscera weight  Shell weight  Rings
2020          0.1450        0.1680      9
2021          0.1495        0.1765      9
2022          0.1855        0.1960      9
2023          0.1565        0.1850      9
2024          0.1905        0.2385     11
2025          0.2435        0.2675     10
2026          0.1840        0.2530      9
2027          0.2120        0.2475      9
2028          0.1560        0.2450     10
2029          0.2705        0.2625      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2030   M   0.590     0.465   0.165        1.1150          0.5165
2031   F   0.600     0.450   0.140        0.8370          0.3700
2032   M   0.605     0.445   0.140        0.9820          0.4295
2033   M   0.610     0.490   0.160        1.1120          0.4650
2034   F   0.625     0.515   0.180        1.3485          0.5255
2035   M   0.660     0.515   0.195        1.5655          0.7345
2036   I   0.255     0.190   0.060        0.0860          0.0400
2037   I   0.270     0.195   0.065        0.1065          0.0475
2038   I   0.280     0.215   0.080        0.1320          0.0720
2039   I   0.285     0.215   0.070        0.1075          0.0510

      Viscera weight  Shell weight  Rings
2030          0.2730        0.2750     10
2031          0.1770        0.2425     10
2032          0.2085        0.2950     12
2033          0.2280        0.3410     10
2034          0.2520        0.3925     14
2035          0.3530        0.3860      9
2036          0.0185        0.0250      5
2037          0.0225        0.0285      5
2038          0.0220        0.0330      5
2039          0.0225        0.0270      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2040   I   0.320     0.255   0.085        0.1745          0.0720
2041   I   0.325     0.240   0.070        0.1520          0.0565
2042   I   0.385     0.280   0.100        0.2755          0.1305
2043   I   0.395     0.295   0.100        0.2930          0.1400
2044   F   0.400     0.305   0.160        0.3680          0.1730
2045   I   0.405     0.310   0.090        0.3120          0.1380
2046   I   0.415     0.305   0.120        0.3360          0.1650
2047   I   0.420     0.315   0.115        0.3550          0.1895
2048   I   0.440     0.305   0.115        0.3790          0.1620
2049   I   0.445     0.320   0.120        0.3780          0.1520

      Viscera weight  Shell weight  Rings
2040          0.0330        0.0570      8
2041          0.0305        0.0540      8
2042          0.0610        0.0725      8
2043          0.0620        0.0820      7
2044          0.0705        0.1050      7
2045          0.0600        0.0870      8
2046          0.0760        0.0805      7
2047          0.0650        0.0870      6
2048          0.0910        0.1100      9
2049          0.0825        0.1200      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2050   M   0.450     0.350   0.130        0.4655          0.2075
2051   F   0.455     0.355   1.130        0.5940          0.3320
2052   M   0.460     0.345   0.120        0.4935          0.2435
2053   M   0.460     0.345   0.110        0.4595          0.2350
2054   M   0.465     0.360   0.110        0.4955          0.2665
2055   I   0.465     0.355   0.090        0.4325          0.2005
2056   F   0.475     0.380   0.140        0.6890          0.3165
2057   I   0.480     0.350   0.135        0.5465          0.2735
2058   M   0.485     0.390   0.135        0.6170          0.2500
2059   I   0.490     0.370   0.110        0.5380          0.2710

      Viscera weight  Shell weight  Rings
2050          0.1045        0.1350      8
2051          0.1160        0.1335      8
2052          0.1175        0.1320      8
2053          0.0885        0.1160      7
2054          0.0850        0.1210      7
2055          0.0740        0.1275      9
2056          0.1315        0.1955      7
2057          0.0995        0.1580      8
2058          0.1345        0.1635      8
2059          0.1035        0.1390      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2060   M   0.500     0.390   0.135        0.7815          0.3610
2061   F   0.500     0.380   0.140        0.6355          0.2770
2062   M   0.505     0.385   0.130        0.6435          0.3135
2063   M   0.525     0.385   0.100        0.5115          0.2460
2064   M   0.535     0.420   0.125        0.7380          0.3550
2065   F   0.535     0.420   0.130        0.6990          0.3125
2066   F   0.540     0.385   0.140        0.7655          0.3265
2067   F   0.540     0.420   0.130        0.7505          0.3680
2068   F   0.545     0.430   0.160        0.8440          0.3945
2069   M   0.550     0.410   0.130        0.8705          0.4455

      Viscera weight  Shell weight  Rings
2060          0.1575        0.2385      9
2061          0.1430        0.1785      8
2062          0.1490        0.1515      7
2063          0.1005        0.1455      8
2064          0.1895        0.1795      8
2065          0.1565        0.2035      8
2066          0.1160        0.2365     10
2067          0.1675        0.1845      9
2068          0.1855        0.2310      9
2069          0.2115        0.2130      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2070   I   0.550     0.420   0.115        0.6680          0.2925
2071   F   0.565     0.440   0.135        0.8300          0.3930
2072   M   0.580     0.450   0.120        0.8685          0.4180
2073   F   0.580     0.435   0.150        0.8390          0.3485
2074   F   0.585     0.485   0.150        1.0790          0.4145
2075   M   0.595     0.465   0.150        0.9190          0.4335
2076   F   0.600     0.470   0.190        1.1345          0.4920
2077   F   0.610     0.430   0.140        0.9090          0.4380
2078   M   0.610     0.480   0.165        1.2435          0.5575
2079   F   0.620     0.490   0.160        1.0560          0.4930

      Viscera weight  Shell weight  Rings
2070          0.1370        0.2090     11
2071          0.1735        0.2380      9
2072          0.1475        0.2605      8
2073          0.2070        0.1920      7
2074          0.2115        0.3560     11
2075          0.1765        0.2620      9
2076          0.2595        0.3375     10
2077          0.2000        0.2200      8
2078          0.2675        0.3720      8
2079          0.2440        0.2725      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2080   M   0.645     0.495   0.150        1.2095          0.6030
2081   M   0.650     0.500   0.140        1.2380          0.6165
2082   F   0.665     0.525   0.210        1.6440          0.8180
2083   M   0.685     0.550   0.200        1.7725          0.8130
2084   F   0.690     0.540   0.195        1.2525          0.7300
2085   F   0.705     0.570   0.185        1.7610          0.7470
2086   F   0.710     0.500   0.150        1.3165          0.6835
2087   M   0.720     0.585   0.220        1.9140          0.9155
2088   F   0.720     0.575   0.215        2.1000          0.8565
2089   F   0.730     0.555   0.180        1.6895          0.6555

      Viscera weight  Shell weight  Rings
2080          0.2225        0.3390      9
2081          0.2355        0.3200      8
2082          0.3395        0.4275     10
2083          0.3870        0.4900     11
2084          0.3975        0.4620     12
2085          0.3725        0.4880     10
2086          0.2815        0.2800     10
2087          0.4480        0.4790     11
2088          0.4825        0.6020     12
2089          0.1965        0.4935     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2090   M   0.775     0.570   0.220        2.0320          0.7350
2091   F   0.505     0.390   0.115        0.6600          0.3045
2092   M   0.530     0.425   0.130        0.7455          0.2995
2093   F   0.505     0.385   0.115        0.6160          0.2430
2094   I   0.405     0.305   0.090        0.2825          0.1140
2095   M   0.415     0.300   0.100        0.3355          0.1545
2096   M   0.500     0.390   0.145        0.6510          0.2730
2097   M   0.425     0.330   0.080        0.3610          0.1340
2098   M   0.470     0.350   0.100        0.4775          0.1885
2099   F   0.400     0.310   0.115        0.3465          0.1475

      Viscera weight  Shell weight  Rings
2090          0.4755        0.6585     17
2091          0.1555        0.1750      8
2092          0.1355        0.2450     10
2093          0.1075        0.2100     11
2094          0.0575        0.0950      7
2095          0.0685        0.0950      7
2096          0.1320        0.2200     11
2097          0.0825        0.1250      7
2098          0.0885        0.1750      8
2099          0.0695        0.1150     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2100   I   0.370     0.290   0.100        0.2500          0.1025
2101   M   0.500     0.380   0.155        0.6600          0.2655
2102   I   0.410     0.310   0.110        0.3150          0.1240
2103   M   0.375     0.290   0.100        0.2760          0.1175
2104   F   0.490     0.385   0.125        0.5395          0.2175
2105   M   0.585     0.480   0.185        1.0400          0.4340
2106   M   0.595     0.455   0.155        1.0410          0.4160
2107   F   0.675     0.550   0.180        1.6885          0.5620
2108   M   0.665     0.535   0.225        2.1835          0.7535
2109   M   0.620     0.490   0.170        1.2105          0.5185

      Viscera weight  Shell weight  Rings
2100          0.0505         0.085     10
2101          0.1365         0.215     19
2102          0.0820         0.095      9
2103          0.0565         0.085      9
2104          0.1280         0.165     11
2105          0.2650         0.285     10
2106          0.2105         0.365     14
2107          0.3705         0.600     15
2108          0.3910         0.885     27
2109          0.2555         0.335     13
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2110   I   0.325     0.250   0.055        0.1660          0.0760
2111   I   0.455     0.355   0.080        0.4520          0.2165
2112   M   0.525     0.405   0.130        0.7185          0.3265
2113   I   0.385     0.290   0.090        0.2320          0.0855
2114   I   0.130     0.095   0.035        0.0105          0.0050
2115   I   0.180     0.130   0.045        0.0275          0.0125
2116   I   0.310     0.225   0.050        0.1445          0.0675
2117   F   0.375     0.290   0.080        0.2820          0.1405
2118   F   0.480     0.380   0.120        0.6080          0.2705
2119   I   0.455     0.370   0.125        0.4330          0.2010

      Viscera weight  Shell weight  Rings
2110          0.0510        0.0450      5
2111          0.0995        0.1250      9
2112          0.1975        0.1750      8
2113          0.0495        0.0800      7
2114          0.0065        0.0035      4
2115          0.0100        0.0090      3
2116          0.0385        0.0450      6
2117          0.0725        0.0800      7
2118          0.1405        0.1850      8
2119          0.1265        0.1450      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2120   M   0.425     0.325   0.100        0.3295          0.1365
2121   I   0.475     0.360   0.110        0.4555          0.1770
2122   F   0.435     0.350   0.120        0.4585          0.1920
2123   F   0.290     0.210   0.075        0.2750          0.1130
2124   M   0.385     0.295   0.095        0.3350          0.1470
2125   M   0.470     0.375   0.115        0.4265          0.1685
2126   F   0.500     0.400   0.125        0.5765          0.2395
2127   I   0.400     0.310   0.100        0.1270          0.1060
2128   M   0.620     0.510   0.175        1.1505          0.4375
2129   M   0.595     0.470   0.150        0.8915          0.3590

      Viscera weight  Shell weight  Rings
2120          0.0725         0.110      7
2121          0.0965         0.145      9
2122          0.1000         0.130     11
2123          0.0675         0.035      6
2124          0.0940         0.090      7
2125          0.0755         0.150      8
2126          0.1260         0.185     10
2127          0.0710         0.085      7
2128          0.2265         0.400     12
2129          0.2105         0.245     12
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2130   M   0.585     0.455   0.140        0.9700          0.4620
2131   M   0.320     0.240   0.080        0.1800          0.0800
2132   F   0.520     0.410   0.125        0.6985          0.2945
2133   M   0.440     0.350   0.110        0.4585          0.2000
2134   F   0.440     0.330   0.115        0.4005          0.1430
2135   M   0.565     0.425   0.100        0.7145          0.3055
2136   F   0.560     0.425   0.125        0.9320          0.3610
2137   F   0.590     0.455   0.175        0.9660          0.3910
2138   F   0.570     0.465   0.180        0.9995          0.4050
2139   M   0.680     0.530   0.205        1.4960          0.5825

      Viscera weight  Shell weight  Rings
2130          0.1850         0.295      9
2131          0.0385         0.055      6
2132          0.1625         0.215     10

(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2300   F   0.480     0.405   0.130        0.6375          0.2770
2301   F   0.520     0.425   0.150        0.8130          0.3850
2302   M   0.460     0.375   0.130        0.5735          0.2505
2303   F   0.580     0.455   0.120        0.9400          0.3990
2304   M   0.590     0.490   0.135        1.0080          0.4220
2305   F   0.550     0.415   0.135        0.7750          0.3020
2306   F   0.650     0.500   0.165        1.1445          0.4850
2307   F   0.465     0.375   0.135        0.6000          0.2225
2308   M   0.455     0.355   0.130        0.5150          0.2000
2309   M   0.470     0.375   0.130        0.5795          0.2145

      Viscera weight  Shell weight  Rings
2300          0.1445         0.210     10
2301          0.2015         0.230     10
2302          0.1190         0.195      9
2303          0.2570         0.265     11
2304          0.2245         0.285     11
2305          0.1790         0.260     23
2306          0.2180         0.365     12
2307          0.1290         0.230     16
2308          0.1275         0.175     11
2309          0.1640         0.195     13
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2310   F   0.435     0.350   0.110        0.3840          0.1430
2311   M   0.350     0.265   0.110        0.2965          0.1365
2312   I   0.315     0.240   0.070        0.1370          0.0545
2313   M   0.595     0.470   0.145        0.9910          0.4035
2314   F   0.580     0.475   0.135        0.9250          0.3910
2315   M   0.575     0.435   0.150        0.8050          0.2930
2316   M   0.535     0.435   0.155        0.8915          0.3415
2317   M   0.515     0.420   0.140        0.7690          0.2505
2318   F   0.505     0.385   0.135        0.6185          0.2510
2319   F   0.505     0.395   0.145        0.6515          0.2695

      Viscera weight  Shell weight  Rings
2310          0.1005         0.125     13
2311          0.0630         0.085      7
2312          0.0315         0.040      8
2313          0.1505         0.340     16
2314          0.1650         0.275     14
2315          0.1625         0.270     17
2316          0.1770         0.250     13
2317          0.1540         0.290     13
2318          0.1175         0.200     12
2319          0.1530         0.205     15
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2320   I   0.400     0.310   0.100        0.2875          0.1145
2321   M   0.490     0.395   0.135        0.5545          0.2130
2322   M   0.530     0.435   0.135        0.7365          0.3275
2323   I   0.395     0.325   0.105        0.3060          0.1110
2324   F   0.665     0.535   0.190        1.4960          0.5775
2325   F   0.415     0.305   0.105        0.3605          0.1200
2326   M   0.430     0.345   0.115        0.3045          0.0925
2327   M   0.475     0.395   0.135        0.5920          0.2465
2328   F   0.525     0.425   0.145        0.7995          0.3345
2329   I   0.480     0.390   0.145        0.5825          0.2315

      Viscera weight  Shell weight  Rings
2320          0.0635         0.095     10
2321          0.0925         0.215     14
2322          0.1315         0.220     12
2323          0.0735         0.095      8
2324          0.2815         0.475     17
2325          0.0820         0.100     10
2326          0.0550         0.120     11
2327          0.1645         0.200     13
2328          0.2090         0.240     15
2329          0.1210         0.255     15
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2330   I   0.420     0.345   0.115        0.3435          0.1515
2331   M   0.590     0.460   0.155        0.9060          0.3270
2332   F   0.515     0.420   0.135        0.6295          0.2815
2333   M   0.695     0.550   0.220        1.5515          0.5660
2334   F   0.800     0.630   0.195        2.5260          0.9330
2335   M   0.610     0.490   0.150        1.1030          0.4250
2336   F   0.565     0.480   0.175        0.9570          0.3885
2337   M   0.560     0.455   0.165        0.8600          0.4015
2338   M   0.655     0.485   0.195        1.6200          0.6275
2339   M   0.640     0.520   0.200        1.4070          0.5660

      Viscera weight  Shell weight  Rings
2330          0.0795         0.115      9
2331          0.1485         0.335     15
2332          0.1270         0.215      9
2333          0.3835         0.445     13
2334          0.5900         0.620     23
2335          0.2025         0.360     23
2336          0.2150         0.275     18
2337          0.1695         0.245     11
2338          0.3580         0.485     17
2339          0.3040         0.455     17
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2340   F   0.590     0.470   0.170        0.9000          0.3550
2341   I   0.310     0.240   0.090        0.1455          0.0605
2342   I   0.255     0.185   0.070        0.0750          0.0280
2343   I   0.170     0.125   0.055        0.0235          0.0090
2344   M   0.670     0.550   0.170        1.2470          0.4720
2345   F   0.710     0.565   0.195        1.7265          0.6380
2346   F   0.560     0.430   0.125        0.8025          0.3130
2347   M   0.505     0.400   0.130        0.7640          0.3035
2348   M   0.525     0.430   0.165        0.8645          0.3760
2349   F   0.450     0.360   0.105        0.4715          0.2035

      Viscera weight  Shell weight  Rings
2340          0.1905        0.2500     11
2341          0.0315        0.0450      7
2342          0.0180        0.0250      6
2343          0.0055        0.0080      6
2344          0.2455        0.4000     21
2345          0.3365        0.5650     17
2346          0.1715        0.2630     13
2347          0.1890        0.2175     11
2348          0.1945        0.2515     16
2349          0.0935        0.1490      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2350   F   0.515     0.435   0.170        0.6310          0.2765
2351   M   0.590     0.475   0.160        0.9455          0.3815
2352   M   0.700     0.530   0.190        1.3185          0.5480
2353   F   0.720     0.560   0.175        1.7265          0.6370
2354   M   0.635     0.495   0.150        1.0810          0.4825
2355   M   0.555     0.440   0.135        0.9025          0.3805
2356   M   0.575     0.470   0.150        1.1415          0.4515
2357   M   0.585     0.455   0.125        1.0270          0.3910
2358   F   0.610     0.485   0.210        1.3445          0.5350
2359   F   0.645     0.525   0.200        1.4490          0.6010

      Viscera weight  Shell weight  Rings
2350          0.1110         0.216     12
2351          0.1840         0.270     19
2352          0.2330         0.420     18
2353          0.3415         0.525     17
2354          0.2420         0.310     11
2355          0.2105         0.280     13
2356          0.2040         0.400     13
2357          0.2120         0.250     17
2358          0.2205         0.515     20
2359          0.2565         0.505     13
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2360   F   0.545     0.440   0.175        0.7745          0.2985
2361   M   0.550     0.450   0.155        0.7895          0.3430
2362   F   0.660     0.525   0.205        1.3665          0.5005
2363   M   0.570     0.475   0.195        1.0295          0.4635
2364   F   0.600     0.470   0.200        1.0310          0.3920
2365   F   0.630     0.505   0.165        1.0650          0.4595
2366   M   0.695     0.570   0.230        1.8850          0.8665
2367   M   0.650     0.545   0.160        1.2425          0.4870
2368   F   0.720     0.595   0.225        1.9690          0.8045
2369   I   0.560     0.440   0.170        0.9445          0.3545

      Viscera weight  Shell weight  Rings
2360          0.1875         0.265     11
2361          0.1590         0.250     12
2362          0.2910         0.410     18
2363          0.1905         0.305     18
2364          0.2035         0.290     15
2365          0.2160         0.315     12
2366          0.4350         0.500     19
2367          0.2960         0.480     15
2368          0.4230         0.660     16
2369          0.2175         0.300     12
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2370   I   0.420     0.325   0.115        0.3540          0.1625
2371   M   0.180     0.125   0.050        0.0230          0.0085
2372   F   0.405     0.325   0.110        0.3575          0.1450
2373   F   0.500     0.405   0.150        0.5965          0.2530
2374   I   0.435     0.335   0.110        0.3830          0.1555
2375   M   0.340     0.275   0.090        0.2065          0.0725
2376   F   0.430     0.340   0.110        0.3820          0.1540
2377   I   0.535     0.410   0.155        0.6315          0.2745
2378   I   0.415     0.325   0.115        0.3285          0.1405
2379   F   0.360     0.265   0.090        0.2165          0.0960

      Viscera weight  Shell weight  Rings
2370          0.0640        0.1050      8
2371          0.0055        0.0100      3
2372          0.0725        0.1100     12
2373          0.1260        0.1850     12
2374          0.0675        0.1350     12
2375          0.0430        0.0700     10
2376          0.0955        0.1090      8
2377          0.1415        0.1815     12
2378          0.0510        0.1060     12
2379          0.0370        0.0735     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2380   M   0.175     0.135   0.040        0.0305          0.0110
2381   M   0.155     0.115   0.025        0.0240          0.0090
2382   I   0.525     0.430   0.150        0.7365          0.3225
2383   F   0.525     0.390   0.135        0.6005          0.2265
2384   F   0.440     0.345   0.105        0.4285          0.1650
2385   F   0.450     0.345   0.115        0.4960          0.1905
2386   F   0.485     0.365   0.140        0.6195          0.2595
2387   I   0.470     0.350   0.135        0.5670          0.2315
2388   I   0.515     0.375   0.140        0.6505          0.2495
2389   M   0.420     0.340   0.125        0.4495          0.1650

      Viscera weight  Shell weight  Rings
2380          0.0075        0.0100      5
2381          0.0050        0.0075      5
2382          0.1610        0.2150     11
2383          0.1310        0.2100     16
2384          0.0830        0.1320     11
2385          0.1170        0.1400     12
2386          0.1445        0.1770     14
2387          0.1465        0.1525     11
2388          0.1410        0.2215     10
2389          0.1125        0.1440     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2390   F   0.455     0.350   0.125        0.4485          0.1585
2391   M   0.370     0.290   0.090        0.2410          0.1100
2392   M   0.330     0.250   0.090        0.1970          0.0850
2393   I   0.300     0.220   0.090        0.1425          0.0570
2394   I   0.625     0.460   0.160        1.2395          0.5500
2395   I   0.610     0.475   0.170        1.0385          0.4435
2396   I   0.625     0.465   0.155        0.9720          0.4040
2397   I   0.635     0.505   0.190        1.3315          0.5805
2398   I   0.500     0.385   0.155        0.7620          0.3795
2399   F   0.530     0.430   0.170        0.7750          0.3500

      Viscera weight  Shell weight  Rings
2390          0.1020        0.1335     16
2391          0.0450        0.0690     10
2392          0.0410        0.0605     10
2393          0.0335        0.0430      7
2394          0.2730        0.3800     14
2395          0.2410        0.3200     14
2396          0.1845        0.3500     14
2397          0.2520        0.4350     17
2398          0.1610        0.1900     14
2399          0.1520        0.2350     17
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2400   I   0.445     0.330   0.100        0.4370          0.1630
2401   F   0.585     0.415   0.155        0.6985          0.3000
2402   I   0.440     0.355   0.165        0.4350          0.1590
2403   M   0.290     0.225   0.080        0.1295          0.0535
2404   I   0.555     0.455   0.170        0.8435          0.3090
2405   I   0.655     0.515   0.145        1.2500          0.5265
2406   F   0.580     0.460   0.185        1.0170          0.3515
2407   I   0.625     0.430   0.175        1.4110          0.5720
2408   I   0.620     0.485   0.170        1.2080          0.4805
2409   F   0.640     0.500   0.150        1.0705          0.3710

      Viscera weight  Shell weight  Rings
2400          0.0755         0.170     13
2401          0.1460         0.195     12
2402          0.1050         0.140     16
2403          0.0260         0.045     10
2404          0.1905         0.300     15
2405          0.2830         0.315     15
2406          0.2000         0.320     10
2407          0.2970         0.395     12
2408          0.3045         0.330     15
2409          0.2705         0.360      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2410   F   0.505     0.375   0.115        0.5895          0.2635
2411   I   0.500     0.395   0.120        0.5370          0.2165
2412   M   0.310     0.245   0.095        0.1500          0.0525
2413   F   0.505     0.380   0.145        0.6510          0.2935
2414   I   0.420     0.305   0.110        0.2800          0.0940
2415   M   0.400     0.315   0.105        0.2870          0.1135
2416   M   0.425     0.315   0.125        0.3525          0.1135
2417   M   0.310     0.235   0.060        0.1200          0.0415
2418   F   0.465     0.350   0.130        0.4940          0.1945
2419   F   0.465     0.360   0.120        0.4765          0.1920

      Viscera weight  Shell weight  Rings
2410          0.1200        0.1670     10
2411          0.1085        0.1785      9
2412          0.0340        0.0480      7
2413          0.1900        0.1700     12
2414          0.0785        0.0955      9
2415          0.0370        0.1130     10
2416          0.0565        0.1300     18
2417          0.0330        0.0400     11
2418          0.1030        0.1550     18
2419          0.1125        0.1600     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2420   M   0.350     0.255   0.085        0.2145          0.1000
2421   I   0.520     0.415   0.160        0.5950          0.2105
2422   F   0.475     0.365   0.130        0.4805          0.1905
2423   F   0.410     0.315   0.110        0.3210          0.1255
2424   M   0.260     0.200   0.065        0.0960          0.0440
2425   I   0.575     0.450   0.170        0.9315          0.3580
2426   I   0.565     0.435   0.155        0.7820          0.2715
2427   M   0.260     0.190   0.075        0.0945          0.0445
2428   F   0.530     0.385   0.125        0.6695          0.2890
2429   M   0.340     0.255   0.095        0.2130          0.0810

      Viscera weight  Shell weight  Rings
2420          0.0465        0.0600     13
2421          0.1420        0.2600     15
2422          0.1140        0.1475     12
2423          0.0655        0.0950     10
2424          0.0270        0.0300      6
2425          0.2145        0.2600     13
2426          0.1680        0.2850     14
2427          0.0200        0.0300      6
2428          0.1510        0.1800     10
2429          0.0340        0.0700      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2430   I   0.520     0.380   0.140        0.5250          0.1775
2431   F   0.635     0.500   0.180        1.3120          0.5290
2432   F   0.610     0.485   0.165        1.0870          0.4255
2433   F   0.660     0.515   0.180        1.5230          0.5400
2434   I   0.635     0.500   0.180        1.3190          0.5485
2435   F   0.465     0.380   0.135        0.5790          0.2080
2436   M   0.515     0.400   0.160        0.8175          0.2515
2437   I   0.335     0.240   0.095        0.1700          0.0620
2438   F   0.515     0.400   0.170        0.7960          0.2580
2439   F   0.345     0.255   0.100        0.1970          0.0710

      Viscera weight  Shell weight  Rings
2430          0.1150         0.185     11
2431          0.2485         0.485     18
2432          0.2320         0.380     11
2433          0.3365         0.555     16
2434          0.2920         0.490     16
2435          0.1095         0.220     14
2436          0.1560         0.300     23
2437          0.0390         0.055      9
2438          0.1755         0.280     16
2439          0.0510         0.060      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2440   M   0.465     0.355   0.125        0.5255          0.2025
2441   M   0.540     0.415   0.170        0.8790          0.3390
2442   M   0.475     0.355   0.125        0.4625          0.1860
2443   F   0.445     0.335   0.140        0.4565          0.1785
2444   M   0.500     0.355   0.140        0.5280          0.2125
2445   M   0.500     0.380   0.135        0.5835          0.2295
2446   F   0.550     0.435   0.170        0.8840          0.2875
2447   I   0.275     0.205   0.080        0.0960          0.0360
2448   F   0.350     0.265   0.090        0.1855          0.0745
2449   F   0.370     0.285   0.105        0.2700          0.1125

      Viscera weight  Shell weight  Rings
2440          0.1350        0.1450     13
2441          0.2080        0.2550     10
2442          0.1070        0.1450      9
2443          0.1140        0.1400     11
2444          0.1490        0.1400      9
2445          0.1265        0.1800     12
2446          0.1645        0.2800     14
2447          0.0185        0.0300      6
2448          0.0415        0.0600      7
2449          0.0585        0.0835      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2450   F   0.420     0.330   0.125        0.4630          0.1860
2451   M   0.350     0.260   0.090        0.1980          0.0725
2452   M   0.395     0.305   0.105        0.2820          0.0975
2453   I   0.325     0.200   0.080        0.0995          0.0395
2454   I   0.275     0.200   0.065        0.0920          0.0385
2455   I   0.235     0.170   0.065        0.0625          0.0230
2456   I   0.250     0.180   0.060        0.0730          0.0280
2457   I   0.250     0.185   0.065        0.0710          0.0270
2458   I   0.200     0.145   0.050        0.0360          0.0125
2459   F   0.585     0.470   0.170        1.0990          0.3975

      Viscera weight  Shell weight  Rings
2450          0.1100        0.1450     10
2451          0.0560        0.0600     10
2452          0.0650        0.0960      9
2453          0.0225        0.0320      8
2454          0.0235        0.0270      5
2455          0.0140        0.0220      6
2456          0.0170        0.0225      5
2457          0.0185        0.0225      5
2458          0.0080        0.0110      4
2459          0.2325        0.3580     20
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2460   M   0.445     0.350    0.14        0.5905          0.2025
2461   F   0.500     0.385    0.13        0.7680          0.2625
2462   M   0.440     0.325    0.08        0.4130          0.1440
2463   M   0.515     0.405    0.14        0.8505          0.3120
2464   F   0.520     0.405    0.14        0.6915          0.2760
2465   M   0.500     0.390    0.13        0.7090          0.2750
2466   M   0.425     0.325    0.12        0.3755          0.1420
2467   M   0.510     0.415    0.14        0.8185          0.3025
2468   F   0.370     0.275    0.08        0.2270          0.0930
2469   M   0.540     0.415    0.13        0.8245          0.2720

      Viscera weight  Shell weight  Rings
2460          0.1580         0.190     14
2461          0.0950         0.270     13
2462          0.1015         0.130      8
2463          0.1460         0.315     17

(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2650   I   0.510     0.395   0.155        0.5395          0.2465
2651   I   0.510     0.385   0.150        0.6250          0.3095
2652   I   0.515     0.400   0.125        0.5925          0.2650
2653   I   0.520     0.395   0.135        0.6330          0.2985
2654   F   0.545     0.430   0.140        0.8320          0.4355
2655   M   0.545     0.420   0.145        0.7780          0.3745
2656   M   0.545     0.420   0.120        0.7865          0.4030
2657   F   0.545     0.400   0.140        0.7780          0.3680
2658   I   0.550     0.420   0.130        0.6360          0.2940
2659   F   0.550     0.440   0.135        0.8435          0.4340

      Viscera weight  Shell weight  Rings
2650          0.1085        0.1670      8
2651          0.1190        0.1725      8
2652          0.1175        0.1680      9
2653          0.1295        0.1750      9
2654          0.1700        0.2010      9
2655          0.1545        0.2050      7
2656          0.1850        0.1700      7
2657          0.2150        0.1800      9
2658          0.1440        0.1755      8
2659          0.1995        0.1850      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2660   I   0.555     0.425   0.130        0.6480          0.2835
2661   M   0.565     0.430   0.130        0.7840          0.3495
2662   F   0.570     0.450   0.180        0.9080          0.4015
2663   M   0.570     0.450   0.135        1.0200          0.5460
2664   F   0.570     0.430   0.160        0.8110          0.3875
2665   F   0.575     0.480   0.150        0.8970          0.4235
2666   M   0.580     0.455   0.130        0.8520          0.4100
2667   F   0.585     0.450   0.150        0.9380          0.4670
2668   F   0.585     0.435   0.140        0.6955          0.3085
2669   M   0.590     0.470   0.150        0.8610          0.4130

      Viscera weight  Shell weight  Rings
2660          0.1330        0.2105      8
2661          0.1885        0.2130      9
2662          0.2170        0.2550      9
2663          0.2040        0.2500      9
2664          0.1590        0.2285      9
2665          0.1905        0.2480      8
2666          0.1725        0.2250      8
2667          0.2030        0.2250      7
2668          0.1290        0.2245      8
2669          0.1640        0.2490      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2670   M   0.590     0.460   0.140        1.0040          0.4960
2671   F   0.590     0.460   0.160        1.0115          0.4450
2672   F   0.595     0.465   0.150        1.1005          0.5415
2673   M   0.595     0.470   0.165        1.1080          0.4915
2674   M   0.595     0.460   0.140        0.8520          0.4215
2675   M   0.600     0.490   0.210        1.9875          1.0050
2676   F   0.605     0.480   0.150        1.0790          0.4505
2677   F   0.615     0.475   0.170        1.0550          0.5430
2678   M   0.615     0.450   0.150        1.1980          0.7070
2679   F   0.615     0.470   0.155        1.0840          0.5885

      Viscera weight  Shell weight  Rings
2670          0.2165        0.2600      9
2671          0.2615        0.2565      8
2672          0.1660        0.2650      8
2673          0.2325        0.3345      9
2674          0.2255        0.2270      9
2675          0.4190        0.4910     10
2676          0.2835        0.2930     10
2677          0.2460        0.2345      9
2678          0.2095        0.2505      7
2679          0.2090        0.2460      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2680   M   0.615     0.475   0.175        1.1030          0.4635
2681   M   0.620     0.490   0.155        1.1000          0.5050
2682   M   0.620     0.480   0.150        1.1015          0.4965
2683   M   0.625     0.495   0.185        1.3835          0.7105
2684   F   0.625     0.490   0.155        1.1150          0.4840
2685   M   0.625     0.480   0.145        1.0850          0.4645
2686   M   0.630     0.505   0.150        1.3165          0.6325
2687   M   0.630     0.510   0.175        1.3415          0.6575
2688   M   0.630     0.465   0.150        1.0270          0.5370
2689   M   0.645     0.515   0.160        1.1845          0.5060

      Viscera weight  Shell weight  Rings
2680          0.3095        0.2725     10
2681          0.2475        0.3100      9
2682          0.2430        0.3050     10
2683          0.3005        0.3450     11
2684          0.2770        0.3095      9
2685          0.2445        0.3270     10
2686          0.2465        0.3700     11
2687          0.2620        0.3750     10
2688          0.1880        0.1760      8
2689          0.3110        0.3350      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2690   M   0.645     0.480   0.150        1.1920          0.6055
2691   F   0.645     0.520   0.180        1.2850          0.5775
2692   M   0.650     0.515   0.125        1.1805          0.5235
2693   M   0.650     0.520   0.175        1.2655          0.6150
2694   F   0.650     0.535   0.175        1.2895          0.6095
2695   M   0.650     0.510   0.155        1.4070          0.7215
2696   F   0.650     0.490   0.155        1.1220          0.5450
2697   M   0.660     0.515   0.165        1.4465          0.6940
2698   F   0.665     0.505   0.165        1.3490          0.5985
2699   M   0.670     0.500   0.200        1.2690          0.5760

      Viscera weight  Shell weight  Rings
2690          0.2595        0.2850      9
2691          0.3520        0.3170      9
2692          0.2830        0.3275      9
2693          0.2775        0.3360      9
2694          0.2765        0.3440     10
2695          0.2980        0.3350      9
2696          0.2280        0.3055      9
2697          0.2980        0.3755     10
2698          0.3175        0.3600      9
2699          0.2985        0.3510     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2700   M   0.670     0.510   0.180        1.6800          0.9260
2701   F   0.675     0.550   0.190        1.5510          0.7105
2702   M   0.680     0.520   0.165        1.4775          0.7240
2703   M   0.680     0.530   0.180        1.5290          0.7635
2704   M   0.700     0.525   0.175        1.7585          0.8745
2705   M   0.700     0.550   0.200        1.5230          0.6930
2706   F   0.725     0.530   0.190        1.7315          0.8300
2707   M   0.725     0.550   0.200        1.5100          0.8735
2708   M   0.735     0.570   0.175        1.8800          0.9095
2709   F   0.740     0.575   0.220        2.0120          0.8915

      Viscera weight  Shell weight  Rings
2700          0.2975        0.3935     13
2701          0.3685        0.4120     13
2702          0.2790        0.4060     11
2703          0.3115        0.4025     11
2704          0.3615        0.4700     10
2705          0.3060        0.4405     13
2706          0.3980        0.4050     11
2707          0.4265        0.5085      9
2708          0.3870        0.4880     11
2709          0.5265        0.4710     12
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2710   M   0.750     0.555   0.215        2.2010          1.0615
2711   I   0.190     0.140   0.030        0.0315          0.0125
2712   I   0.210     0.150   0.045        0.0400          0.0135
2713   I   0.250     0.175   0.060        0.0635          0.0275
2714   I   0.290     0.215   0.065        0.0985          0.0425
2715   I   0.335     0.250   0.080        0.1670          0.0675
2716   I   0.340     0.245   0.085        0.2015          0.1005
2717   I   0.345     0.255   0.095        0.1830          0.0750
2718   I   0.355     0.255   0.080        0.1870          0.0780
2719   I   0.360     0.260   0.080        0.1795          0.0740

      Viscera weight  Shell weight  Rings
2710          0.5235        0.5285     11
2711          0.0050        0.0105      3
2712          0.0080        0.0105      4
2713          0.0080        0.0200      4
2714          0.0210        0.0310      5
2715          0.0325        0.0575      6
2716          0.0380        0.0530      6
2717          0.0385        0.0600      6
2718          0.0505        0.0580      7
2719          0.0315        0.0600      5
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2720   I   0.370     0.275   0.090        0.2065          0.0960
2721   I   0.375     0.290   0.140        0.3000          0.1400
2722   I   0.375     0.275   0.095        0.2295          0.0950
2723   I   0.385     0.300   0.125        0.3430          0.1705
2724   I   0.385     0.285   0.085        0.2440          0.1215
2725   I   0.395     0.320   0.100        0.3075          0.1490
2726   I   0.400     0.305   0.100        0.3415          0.1760
2727   I   0.405     0.305   0.100        0.2710          0.0965
2728   I   0.405     0.310   0.110        0.9100          0.4160
2729   I   0.405     0.305   0.100        0.2680          0.1145

      Viscera weight  Shell weight  Rings
2720          0.0395        0.0580      7
2721          0.0625        0.0825      8
2722          0.0545        0.0660      7
2723          0.0735        0.0810      7
2724          0.0445        0.0680      8
2725          0.0535        0.0900      8
2726          0.0625        0.0865      7
2727          0.0610        0.0910      7
2728          0.2075        0.0995      8
2729          0.0530        0.0850      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2730   I   0.405     0.300   0.090        0.2885          0.1380
2731   I   0.410     0.315   0.100        0.3000          0.1240
2732   I   0.410     0.325   0.110        0.3260          0.1325
2733   I   0.415     0.335   0.100        0.3580          0.1690
2734   I   0.420     0.325   0.115        0.3140          0.1295
2735   I   0.420     0.315   0.110        0.4025          0.1855
2736   I   0.430     0.340   0.110        0.3645          0.1590
2737   I   0.445     0.360   0.110        0.4235          0.1820
2738   M   0.450     0.325   0.115        0.4305          0.2235
2739   I   0.450     0.335   0.095        0.3505          0.1615

      Viscera weight  Shell weight  Rings
2730          0.0635        0.0765      6
2731          0.0575        0.1000      8
2732          0.0750        0.1010      8
2733          0.0670        0.1050      7
2734          0.0635        0.1000      8
2735          0.0830        0.1015      8
2736          0.0855        0.1050      7
2737          0.0765        0.1400      9
2738          0.0785        0.1155      8
2739          0.0625        0.1185      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2740   I   0.455     0.340   0.115        0.4860          0.2610
2741   I   0.460     0.350   0.100        0.4710          0.2520
2742   I   0.460     0.345   0.105        0.4150          0.1870
2743   I   0.475     0.355   0.115        0.5195          0.2790
2744   M   0.480     0.375   0.120        0.5895          0.2535
2745   I   0.485     0.380   0.125        0.5215          0.2215
2746   I   0.485     0.365   0.140        0.4475          0.1895
2747   I   0.490     0.365   0.125        0.5585          0.2520
2748   I   0.505     0.385   0.125        0.5960          0.2450
2749   I   0.505     0.380   0.135        0.5385          0.2645

      Viscera weight  Shell weight  Rings
2740          0.0655        0.1315      8
2741          0.0770        0.1230      8
2742          0.0870        0.1100      8
2743          0.0880        0.1325      7
2744          0.1280        0.1720     11
2745          0.1180        0.1600      8
2746          0.0925        0.2305      8
2747          0.1260        0.1615     10
2748          0.0970        0.2100      9
2749          0.0950        0.1650      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2750   I   0.510     0.385   0.145        0.7665          0.3985
2751   F   0.515     0.395   0.135        0.5160          0.2015
2752   M   0.515     0.410   0.140        0.7355          0.3065
2753   I   0.515     0.390   0.110        0.5310          0.2415
2754   I   0.525     0.385   0.130        0.6070          0.2355
2755   F   0.525     0.415   0.150        0.7055          0.3290
2756   I   0.525     0.400   0.130        0.6445          0.3450
2757   I   0.525     0.375   0.120        0.6315          0.3045
2758   M   0.535     0.430   0.155        0.7845          0.3285
2759   F   0.545     0.440   0.150        0.9475          0.3660

      Viscera weight  Shell weight  Rings
2750          0.1400        0.1805      8
2751          0.1320        0.1620      9
2752          0.1370        0.2000      7
2753          0.0980        0.1615      8
2754          0.1250        0.1950      8
2755          0.1470        0.1990     10
2756          0.1285        0.2000      8
2757          0.1140        0.1900      9
2758          0.1690        0.2450     10
2759          0.2390        0.2750      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2760   I   0.550     0.430   0.145        0.7120          0.3025
2761   I   0.550     0.425   0.145        0.8900          0.4325
2762   I   0.550     0.420   0.155        0.9120          0.4950
2763   I   0.550     0.425   0.135        0.6560          0.2570
2764   I   0.550     0.465   0.150        0.9360          0.4810
2765   I   0.555     0.435   0.145        0.6975          0.2620
2766   F   0.555     0.445   0.175        1.1465          0.5510
2767   I   0.560     0.440   0.140        0.8250          0.4020
2768   I   0.560     0.435   0.135        0.7200          0.3290
2769   I   0.565     0.430   0.150        0.8215          0.3320

      Viscera weight  Shell weight  Rings
2760          0.1520        0.2250     10
2761          0.1710        0.2360     10
2762          0.1805        0.2050      9
2763          0.1700        0.2030     10
2764          0.1740        0.2435      9
2765          0.1575        0.2400     11
2766          0.2440        0.2785      8
2767          0.1390        0.2450     10
2768          0.1030        0.2510     11
2769          0.1685        0.2900     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2770   F   0.570     0.445   0.155        1.0170          0.5265
2771   F   0.575     0.435   0.155        0.8975          0.4115
2772   M   0.580     0.440   0.175        1.2255          0.5405
2773   F   0.580     0.465   0.145        0.9865          0.4700
2774   F   0.580     0.425   0.150        0.8440          0.3645
2775   I   0.585     0.460   0.145        0.8465          0.3390
2776   M   0.585     0.465   0.165        0.8850          0.4025
2777   I   0.585     0.420   0.145        0.6735          0.2895
2778   F   0.585     0.455   0.130        0.8755          0.4110
2779   M   0.590     0.470   0.145        0.9235          0.4545

      Viscera weight  Shell weight  Rings
2770          0.2025        0.2650     10
2771          0.2325        0.2300      9
2772          0.2705        0.3265     10
2773          0.2155        0.2500     11
2774          0.1850        0.2705      9
2775          0.1670        0.2950     10
2776          0.1625        0.2740     10
2777          0.1345        0.2200      9
2778          0.2065        0.2250      8
2779          0.1730        0.2540      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2780   M   0.590     0.475   0.140        0.9770          0.4625
2781   M   0.595     0.475   0.140        1.0305          0.4925
2782   M   0.600     0.480   0.090        1.0500          0.4570
2783   M   0.600     0.495   0.185        1.1145          0.5055
2784   M   0.600     0.450   0.145        0.8770          0.4325
2785   M   0.600     0.510   0.185        1.2850          0.6095
2786   M   0.610     0.480   0.185        1.3065          0.6895
2787   F   0.610     0.450   0.130        0.8725          0.3890
2788   F   0.615     0.460   0.150        1.0265          0.4935
2789   F   0.620     0.465   0.140        1.1605          0.6005

      Viscera weight  Shell weight  Rings
2780          0.2025        0.2750     10
2781          0.2170        0.2780     10
2782          0.2685        0.2800      8
2783          0.2635        0.3670     11
2784          0.1550        0.2400      9
2785          0.2745        0.3150      9
2786          0.2915        0.2900     10
2787          0.1715        0.2720     11
2788          0.2010        0.2745     10
2789          0.2195        0.3070      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2790   F   0.620     0.480   0.165        1.0125          0.5325
2791   M   0.625     0.500   0.140        1.0960          0.5445
2792   M   0.625     0.490   0.165        1.2050          0.5175
2793   M   0.630     0.505   0.175        1.2210          0.5550
2794   F   0.630     0.475   0.155        1.0005          0.4520
2795   M   0.630     0.470   0.150        1.1355          0.5390
2796   M   0.630     0.525   0.195        1.3135          0.4935
2797   M   0.640     0.505   0.155        1.1955          0.5565
2798   M   0.640     0.485   0.150        1.0980          0.5195
2799   M   0.640     0.495   0.170        1.1390          0.5395

      Viscera weight  Shell weight  Rings
2790          0.4365        0.3240     10
2791          0.2165        0.2950     10
2792          0.3105        0.3465     10
2793          0.2520        0.3400     12
2794          0.2520        0.2650     10
2795          0.2325        0.3115     12
2796          0.2565        0.4650     10
2797          0.2110        0.3460     11
2798          0.2220        0.3175     10
2799          0.2820        0.2850     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2800   F   0.640     0.495   0.170        1.2265          0.4900
2801   M   0.640     0.515   0.080        1.0420          0.5150
2802   M   0.650     0.520   0.155        1.3680          0.6185
2803   M   0.650     0.510   0.175        1.4460          0.6485
2804   F   0.660     0.505   0.190        1.4045          0.6255
2805   F   0.660     0.525   0.200        1.4630          0.6525
2806   F   0.675     0.525   0.170        1.7110          0.8365
2807   M   0.700     0.540   0.205        1.7400          0.7885
2808   F   0.705     0.540   0.205        1.7570          0.8265
2809   M   0.710     0.565   0.200        1.6010          0.7060

      Viscera weight  Shell weight  Rings
2800          0.3770        0.2875     11
2801          0.1755        0.1750     10
2802          0.2880        0.3650      9
2803          0.2705        0.4500     12
2804          0.3375        0.3745      9
2805          0.2995        0.4220     11
2806          0.3520        0.4750      9
2807          0.3730        0.4865     13
2808          0.4170        0.4610      9
2809          0.3210        0.4500     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2810   M   0.720     0.550   0.205        2.1650          1.1055
2811   M   0.725     0.570   0.190        2.3305          1.2530
2812   I   0.240     0.170   0.050        0.0545          0.0205
2813   I   0.255     0.195   0.055        0.0725          0.0285
2814   I   0.275     0.200   0.055        0.0925          0.0380
2815   I   0.320     0.235   0.090        0.1830          0.0980
2816   I   0.325     0.240   0.075        0.1525          0.0720
2817   I   0.330     0.225   0.075        0.1870          0.0945
2818   I   0.360     0.270   0.090        0.2320          0.1200
2819   I   0.375     0.265   0.095        0.1960          0.0850

      Viscera weight  Shell weight  Rings
2810          0.5250        0.4040     10
2811          0.5410        0.5200      9
2812          0.0160        0.0155      5
2813          0.0170        0.0210      4

(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2990   F   0.590     0.440   0.140        1.0070          0.4775
2991   M   0.595     0.485   0.150        1.0835          0.5305
2992   I   0.595     0.430   0.165        0.9845          0.4525
2993   F   0.595     0.430   0.210        1.5245          0.6530
2994   M   0.610     0.475   0.175        1.0240          0.4090
2995   M   0.610     0.485   0.170        1.2810          0.5970
2996   F   0.620     0.500   0.170        1.1480          0.5475
2997   F   0.625     0.490   0.110        1.1360          0.5265
2998   F   0.635     0.510   0.170        1.2235          0.5320
2999   F   0.635     0.525   0.180        1.3695          0.6340

      Viscera weight  Shell weight  Rings
2990          0.2105        0.2925      9
2991          0.2310        0.2760      8
2992          0.2070        0.2725      8
2993          0.3960        0.4100     11
2994          0.2610        0.3220      9
2995          0.3035        0.3300      9
2996          0.2200        0.3315     10
2997          0.1915        0.2925      9
2998          0.2710        0.3540      9
2999          0.3180        0.3630     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3000   M   0.640     0.485   0.160        1.0060          0.4560
3001   M   0.640     0.495   0.165        1.3070          0.6780
3002   M   0.645     0.505   0.185        1.4630          0.5920
3003   F   0.655     0.505   0.175        1.2905          0.6205
3004   F   0.670     0.515   0.170        1.4265          0.6605
3005   M   0.680     0.540   0.210        1.7885          0.8345
3006   M   0.700     0.545   0.185        1.6135          0.7500
3007   M   0.730     0.585   0.225        2.2305          1.2395
3008   F   0.750     0.615   0.205        2.2635          0.8210
3009   I   0.255     0.185   0.065        0.0740          0.0305

      Viscera weight  Shell weight  Rings
3000          0.2245        0.2835      9
3001          0.2920        0.2660     11
3002          0.3905        0.4160     10
3003          0.2965        0.3260     10
3004          0.3395        0.3700     11
3005          0.4080        0.4370     13
3006          0.4035        0.3685     11
3007          0.4220        0.5630     14
3008          0.4230        0.7260     12
3009          0.0165        0.0200      4
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3010   I   0.375     0.260   0.080        0.2075          0.0900
3011   I   0.375     0.285   0.090        0.2370          0.1060
3012   I   0.390     0.300   0.100        0.2665          0.1105
3013   I   0.390     0.280   0.090        0.2150          0.0845
3014   I   0.395     0.300   0.090        0.2530          0.1155
3015   I   0.420     0.320   0.110        0.3090          0.1150
3016   I   0.435     0.335   0.105        0.3535          0.1560
3017   I   0.435     0.325   0.105        0.3350          0.1360
3018   I   0.440     0.320   0.105        0.3875          0.1755
3019   I   0.450     0.330   0.115        0.3650          0.1400

      Viscera weight  Shell weight  Rings
3010          0.0415        0.0700      6
3011          0.0395        0.0800      8
3012          0.0590        0.0840      7
3013          0.0340        0.0790      8
3014          0.0500        0.0750      6
3015          0.0645        0.0945      6
3016          0.0500        0.1135      7
3017          0.0650        0.1150      8
3018          0.0740        0.1200      9
3019          0.0825        0.1245      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3020   I   0.450     0.340   0.125        0.4045          0.1710
3021   I   0.455     0.355   0.105        0.3720          0.1380
3022   I   0.460     0.370   0.110        0.3965          0.1485
3023   I   0.470     0.375   0.125        0.5225          0.2265
3024   I   0.475     0.375   0.110        0.4560          0.1820
3025   I   0.495     0.330   0.100        0.4400          0.1770
3026   I   0.495     0.375   0.115        0.5070          0.2410
3027   I   0.500     0.380   0.135        0.5285          0.2260
3028   I   0.515     0.385   0.125        0.5720          0.2370
3029   I   0.520     0.410   0.140        0.6625          0.2775

      Viscera weight  Shell weight  Rings
3020          0.0700        0.1345      8
3021          0.0765        0.1350      9
3022          0.0855        0.1455      8
3023          0.1040        0.1620      8
3024          0.0990        0.1600      9
3025          0.0950        0.1500      7
3026          0.1030        0.1500      8
3027          0.1230        0.2090      8
3028          0.1435        0.1650      7
3029          0.1555        0.1960     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3030   I   0.520     0.395   0.115        0.6445          0.3155
3031   I   0.525     0.400   0.110        0.6275          0.3015
3032   I   0.535     0.420   0.145        0.6885          0.2730
3033   M   0.535     0.410   0.120        0.6835          0.3125
3034   M   0.540     0.420   0.190        0.6855          0.2930
3035   I   0.550     0.405   0.150        0.6755          0.3015
3036   I   0.550     0.445   0.145        0.7830          0.3045
3037   M   0.560     0.450   0.145        0.8940          0.3885
3038   I   0.565     0.440   0.135        0.7680          0.3305
3039   M   0.570     0.450   0.145        0.9500          0.4005

      Viscera weight  Shell weight  Rings
3030          0.1245        0.1860     11
3031          0.1260        0.1800      8
3032          0.1515        0.2370      9
3033          0.1655        0.1590      8
3034          0.1630        0.3800     10
3035          0.1465        0.2100     10
3036          0.1570        0.2650     11
3037          0.2095        0.2640      9
3038          0.1385        0.2475      9
3039          0.2235        0.2845     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3040   F   0.570     0.470   0.140        0.8710          0.3850
3041   M   0.575     0.470   0.150        0.9785          0.4505
3042   I   0.575     0.430   0.130        0.7425          0.2895
3043   M   0.575     0.445   0.140        0.7370          0.3250
3044   I   0.575     0.445   0.160        0.9175          0.4500
3045   F   0.580     0.435   0.155        0.8785          0.4250
3046   M   0.585     0.450   0.175        1.1275          0.4925
3047   M   0.590     0.435   0.165        0.9765          0.4525
3048   I   0.590     0.470   0.145        0.9740          0.4530
3049   M   0.590     0.405   0.150        0.8530          0.3260

      Viscera weight  Shell weight  Rings
3040          0.2110        0.2315     10
3041          0.1960        0.2760      9
3042          0.2005        0.2200      8
3043          0.1405        0.2370     10
3044          0.1935        0.2400      9
3045          0.1685        0.2425     10
3046          0.2620        0.3350     11
3047          0.2395        0.2350      9
3048          0.2360        0.2890      8
3049          0.2615        0.2450      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3050   M   0.595     0.470   0.175        0.9910          0.3820
3051   M   0.595     0.480   0.140        0.9125          0.4095
3052   F   0.595     0.460   0.160        0.9210          0.4005
3053   F   0.600     0.450   0.140        0.8690          0.3425
3054   M   0.600     0.450   0.150        0.8665          0.3695
3055   F   0.610     0.495   0.160        1.0890          0.4690
3056   M   0.615     0.485   0.215        0.9615          0.4220
3057   M   0.615     0.490   0.170        1.1450          0.4915
3058   I   0.620     0.475   0.160        0.9070          0.3710
3059   F   0.625     0.515   0.155        1.1635          0.4875

      Viscera weight  Shell weight  Rings
3050          0.2395        0.5000     12
3051          0.1825        0.2890      9
3052          0.2025        0.2875      9
3053          0.1950        0.2910     11
3054          0.1955        0.2550     12
3055          0.1980        0.3840     11
3056          0.1760        0.2900     11
3057          0.2080        0.3430     13
3058          0.1670        0.3075     11
3059          0.2590        0.3550     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3060   M   0.630     0.515   0.175        1.1955          0.4920
3061   M   0.630     0.495   0.180        1.3100          0.4950
3062   F   0.635     0.505   0.165        1.2510          0.5770
3063   F   0.635     0.490   0.155        1.1450          0.4775
3064   M   0.635     0.500   0.180        1.1540          0.4405
3065   F   0.640     0.485   0.145        1.1335          0.5525
3066   F   0.640     0.500   0.150        1.2015          0.5590
3067   M   0.650     0.505   0.170        1.5595          0.6950
3068   M   0.650     0.510   0.175        1.3165          0.6345
3069   M   0.655     0.540   0.165        1.4030          0.6955

      Viscera weight  Shell weight  Rings
3060          0.2470        0.3700     11
3061          0.2950        0.4695     10
3062          0.2270        0.3825     11
3063          0.3035        0.3155      9
3064          0.2315        0.3870      9
3065          0.2505        0.3015     11
3066          0.2310        0.3355      9
3067          0.3515        0.3950     11
3068          0.2605        0.3640     12
3069          0.2385        0.4200     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3070   F   0.655     0.490   0.160        1.2040          0.5455
3071   F   0.655     0.455   0.170        1.2895          0.5870
3072   F   0.660     0.530   0.180        1.5175          0.7765
3073   M   0.665     0.525   0.155        1.3575          0.5325
3074   M   0.675     0.520   0.145        1.3645          0.5570
3075   F   0.680     0.520   0.185        1.4940          0.6150
3076   F   0.680     0.560   0.195        1.6640          0.5800
3077   M   0.685     0.510   0.165        1.5450          0.6860
3078   F   0.695     0.535   0.200        1.5855          0.6670
3079   F   0.700     0.555   0.220        1.6660          0.6470

      Viscera weight  Shell weight  Rings
3070          0.2615        0.3225      9
3071          0.3165        0.3415     11
3072          0.3020        0.4010     10
3073          0.3045        0.4485     10
3074          0.3405        0.3850     11
3075          0.3935        0.4060     11
3076          0.3855        0.5450     11
3077          0.3775        0.4055     10
3078          0.3340        0.4710     11
3079          0.4285        0.4550     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3080   M   0.710     0.560   0.175        1.7240          0.5660
3081   F   0.730     0.550   0.205        1.9080          0.5415
3082   F   0.755     0.575   0.200        2.0730          1.0135
3083   I   0.225     0.170   0.050        0.0515          0.0190
3084   I   0.230     0.170   0.050        0.0570          0.0260
3085   I   0.255     0.185   0.060        0.0925          0.0390
3086   I   0.355     0.270   0.075        0.2040          0.3045
3087   I   0.425     0.310   0.095        0.3075          0.1390
3088   I   0.425     0.320   0.085        0.2620          0.1235
3089   M   0.455     0.350   0.110        0.4580          0.2000

      Viscera weight  Shell weight  Rings
3080          0.4575        0.4625     13
3081          0.3565        0.5965     14
3082          0.4655        0.4800     11
3083          0.0120        0.0170      4
3084          0.0130        0.0160      5
3085          0.0210        0.0250      6
3086          0.0460        0.0595      7
3087          0.0745        0.0930      7
3088          0.0670        0.0725      8
3089          0.1110        0.1305      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3090   M   0.460     0.355   0.140        0.4910          0.2070
3091   M   0.495     0.380   0.120        0.4740          0.1970
3092   M   0.510     0.395   0.125        0.5805          0.2440
3093   F   0.520     0.430   0.150        0.7280          0.3020
3094   M   0.525     0.400   0.130        0.6220          0.2655
3095   M   0.530     0.415   0.120        0.7060          0.3355
3096   F   0.530     0.395   0.115        0.5685          0.2490
3097   M   0.545     0.435   0.145        0.9385          0.3685
3098   F   0.550     0.430   0.150        0.6550          0.2635
3099   M   0.575     0.480   0.150        0.9465          0.4355

      Viscera weight  Shell weight  Rings
3090          0.1150        0.1740     10
3091          0.1065        0.1545     10
3092          0.1335        0.1880     11
3093          0.1575        0.2350     11
3094          0.1470        0.1840      9
3095          0.1635        0.1345      9
3096          0.1375        0.1610      9
3097          0.1245        0.3450     11
3098          0.1220        0.2210      8
3099          0.2605        0.2505      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3100   M   0.580     0.430   0.125        0.9115          0.4460
3101   M   0.595     0.455   0.145        0.9420          0.4300
3102   M   0.600     0.465   0.180        1.1930          0.5145
3103   M   0.645     0.500   0.180        1.4610          0.5985
3104   M   0.660     0.525   0.200        1.4890          0.6065
3105   I   0.290     0.215   0.060        0.1115          0.0530
3106   I   0.300     0.220   0.065        0.1235          0.0590
3107   I   0.370     0.275   0.100        0.2815          0.1505
3108   I   0.375     0.285   0.080        0.2260          0.0975
3109   I   0.380     0.290   0.085        0.2285          0.0880

      Viscera weight  Shell weight  Rings
3100          0.2075        0.1210     10
3101          0.1820        0.2770     11
3102          0.3150        0.3055      8
3103          0.2425        0.4390     11
3104          0.3795        0.4210     10
3105          0.0185        0.0320      5
3106          0.0260        0.0315      5
3107          0.0505        0.0680      5
3108          0.0400        0.0725      7
3109          0.0465        0.0750      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3110   I   0.395     0.300   0.120        0.2995          0.1265
3111   I   0.410     0.325   0.105        0.3610          0.1605
3112   I   0.415     0.320   0.115        0.3045          0.1215
3113   I   0.425     0.325   0.105        0.3975          0.1815
3114   I   0.440     0.340   0.100        0.3790          0.1725
3115   I   0.440     0.340   0.120        0.4995          0.2965
3116   M   0.465     0.405   0.135        0.7775          0.4360
3117   F   0.470     0.360   0.100        0.4705          0.1635
3118   M   0.510     0.415   0.145        0.7510          0.3295
3119   F   0.525     0.400   0.135        0.7140          0.3180

      Viscera weight  Shell weight  Rings
3110          0.0680        0.0895      8
3111          0.0665        0.1030      8
3112          0.0735        0.0940      7
3113          0.0810        0.1175      7
3114          0.0815        0.1010      7
3115          0.0945        0.1185      6
3116          0.1715        0.1455     10
3117          0.0890        0.1385      8
3118          0.1835        0.2030      8
3119          0.1380        0.2080     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3120   F   0.525     0.400   0.130        0.6995          0.3115
3121   F   0.550     0.425   0.140        0.9520          0.4895
3122   M   0.560     0.420   0.150        0.8755          0.4400
3123   M   0.575     0.450   0.135        0.9215          0.3540
3124   F   0.575     0.450   0.135        0.8285          0.3620
3125   M   0.585     0.460   0.150        1.2060          0.5810
3126   M   0.615     0.495   0.155        1.2865          0.4350
3127   F   0.620     0.485   0.155        1.1945          0.5105
3128   F   0.630     0.495   0.190        1.1655          0.5360
3129   F   0.630     0.490   0.170        1.2155          0.4625

      Viscera weight  Shell weight  Rings
3120          0.1310        0.2230      9
3121          0.1945        0.2185      7
3122          0.1965        0.2315      8
3123          0.2090        0.2365      9
3124          0.1655        0.2360     10
3125          0.2160        0.3230     10
3126          0.2930        0.3245     11
3127          0.2710        0.3520      9
3128          0.2115        0.1625     10
3129          0.2045        0.3105     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3130   M   0.670     0.515   0.165        1.1735          0.5260
3131   M   0.675     0.505   0.160        1.5320          0.7400
3132   F   0.685     0.530   0.170        1.5105          0.7385
3133   F   0.485     0.390   0.100        0.5565          0.2215
3134   M   0.460     0.360   0.125        0.5470          0.2165
3135   M   0.460     0.350   0.125        0.5165          0.1885
3136   M   0.535     0.420   0.125        0.7640          0.3120
3137   M   0.465     0.360   0.105        0.4880          0.1880
3138   M   0.510     0.400   0.140        0.6905          0.2590
3139   I   0.335     0.260   0.090        0.1835          0.0780

      Viscera weight  Shell weight  Rings
3130          0.2850        0.3160     11
3131          0.3570        0.3815     11
3132          0.3525        0.3725     10
3133          0.1155        0.1850      9
3134          0.1105        0.1900      8
3135          0.1145        0.1850      9
3136          0.1505        0.2650     11
3137          0.0845        0.1900     10
3138          0.1510        0.2300     10
3139          0.0240        0.0650     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3140   M   0.550     0.425   0.160        0.9700          0.2885
3141   I   0.180     0.135   0.080        0.0330          0.0145
3142   I   0.215     0.165   0.055        0.0590          0.0265
3143   I   0.200     0.150   0.040        0.0460          0.0210
3144   F   0.625     0.480   0.200        1.3235          0.6075
3145   M   0.550     0.420   0.170        0.8465          0.3360
3146   M   0.585     0.450   0.150        1.0470          0.4315
3147   F   0.645     0.500   0.180        1.2785          0.5345
3148   F   0.710     0.530   0.195        1.8745          0.6755
3149   F   0.700     0.540   0.215        1.9780          0.6675

      Viscera weight  Shell weight  Rings
3140          0.1390        0.4800     20
3141          0.0070        0.0100      5
3142          0.0125        0.0185      5
3143          0.0070        0.0065      4
3144          0.3055        0.3550      9
3145          0.2405        0.2450     13
3146          0.2760        0.3150     14
3147          0.2995        0.3450     13
3148          0.4065        0.6855     12
3149          0.3125        0.7100     24
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3150   F   0.655     0.505   0.165        1.3670          0.5835
3151   F   0.665     0.500   0.175        1.7420          0.5950
3152   F   0.470     0.375   0.105        0.5130          0.2320
3153   M   0.425     0.335   0.100        0.4085          0.1755
3154   M   0.540     0.410   0.130        0.5600          0.2375
3155   M   0.505     0.395   0.125        0.6350          0.2900
3156   M   0.535     0.440   0.165        0.8750          0.2790
3157   F   0.430     0.350   0.090        0.3970          0.1575
3158   M   0.550     0.435   0.110        0.8060          0.3415
3159   F   0.340     0.255   0.085        0.2040          0.0970

      Viscera weight  Shell weight  Rings
3150          0.3515         0.396     10
3151          0.3025         0.725     21
3152          0.1420         0.130     11
3153          0.0920         0.135      9

(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3330   F   0.385     0.305   0.125        0.3140          0.1460
3331   F   0.510     0.340   0.180        0.7005          0.3120
3332   I   0.440     0.340   0.125        0.4895          0.1735
3333   I   0.450     0.360   0.125        0.4500          0.1910
3334   I   0.390     0.300   0.105        0.2590          0.0955
3335   F   0.425     0.325   0.135        0.3820          0.1465
3336   F   0.450     0.350   0.125        0.4435          0.1850
3337   I   0.660     0.525   0.180        1.6935          0.6025
3338   F   0.685     0.525   0.175        1.7100          0.5415
3339   F   0.585     0.475   0.185        0.8575          0.3465

      Viscera weight  Shell weight  Rings
3330          0.0555         0.080     10
3331          0.1650         0.200     11
3332          0.0875         0.200     13
3333          0.0865         0.145     12
3334          0.0380         0.085      8
3335          0.0790         0.140     12
3336          0.0900         0.145     11
3337          0.4005         0.420     15
3338          0.3090         0.580     16
3339          0.1785         0.275     12
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3340   I   0.540     0.435   0.145        0.9700          0.4285
3341   F   0.490     0.390   0.135        0.5900          0.2150
3342   M   0.430     0.330   0.095        0.3400          0.1315
3343   F   0.455     0.365   0.110        0.3850          0.1660
3344   I   0.495     0.380   0.145        0.5150          0.1750
3345   F   0.480     0.380   0.145        0.5900          0.2320
3346   I   0.470     0.400   0.160        0.5100          0.1615
3347   M   0.415     0.320   0.100        0.3005          0.1215
3348   I   0.490     0.385   0.115        0.6830          0.3265
3349   I   0.470     0.375   0.105        0.4680          0.1665

      Viscera weight  Shell weight  Rings
3340          0.2200        0.2640     17
3341          0.1250        0.1845     12
3342          0.0850        0.1120     14
3343          0.0460        0.1345     13
3344          0.0980        0.2120     13
3345          0.1410        0.2300     12
3346          0.0730        0.1980     14
3347          0.0575        0.1040     11
3348          0.1615        0.1650     13
3349          0.1080        0.1700     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3350   I   0.445     0.345   0.130        0.4075          0.1365
3351   F   0.510     0.380   0.130        0.5840          0.2240
3352   F   0.520     0.405   0.145        0.8290          0.3535
3353   I   0.475     0.365   0.140        0.4545          0.1710
3354   F   0.455     0.360   0.110        0.4385          0.2060
3355   I   0.435     0.340   0.110        0.4070          0.1685
3356   I   0.390     0.300   0.100        0.3085          0.1385
3357   I   0.375     0.285   0.100        0.2390          0.1050
3358   M   0.285     0.215   0.075        0.1060          0.0415
3359   I   0.580     0.445   0.170        1.1780          0.3935

      Viscera weight  Shell weight  Rings
3350          0.0645         0.180     11
3351          0.1355         0.185     13
3352          0.1685         0.205     15
3353          0.1180         0.158      8
3354          0.0980         0.125     10
3355          0.0730         0.130     10
3356          0.0735         0.085      6
3357          0.0555         0.070      8
3358          0.0230         0.035      5
3359          0.2165         0.315     20
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3360   F    0.58     0.440   0.175        1.0730          0.4005
3361   M    0.41     0.315   0.095        0.3060          0.1210
3362   M    0.41     0.300   0.100        0.3010          0.1240
3363   I    0.54     0.405   0.150        0.7585          0.3070
3364   M    0.33     0.245   0.085        0.1710          0.0655
3365   I    0.44     0.310   0.115        0.3625          0.1340
3366   M    0.28     0.210   0.065        0.0905          0.0350
3367   I    0.59     0.465   0.195        1.0885          0.3685
3368   I    0.61     0.480   0.165        1.0970          0.4215
3369   I    0.61     0.460   0.170        1.2780          0.4100

      Viscera weight  Shell weight  Rings
3360          0.2345         0.335     19
3361          0.0735         0.090      9
3362          0.0690         0.090      9
3363          0.2075         0.190     10
3364          0.0365         0.055     11
3365          0.0820         0.120     11
3366          0.0200         0.030      5
3367          0.1870         0.375     17
3368          0.2640         0.335     13
3369          0.2570         0.370     17
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3370   M   0.455     0.345   0.125        0.4400          0.1690
3371   M   0.330     0.235   0.090        0.1630          0.0615
3372   I   0.440     0.330   0.135        0.5220          0.1700
3373   M   0.540     0.405   0.155        0.9715          0.3225
3374   F   0.475     0.375   0.125        0.5880          0.2370
3375   F   0.460     0.330   0.150        0.5325          0.2085
3376   I   0.310     0.235   0.090        0.1270          0.0480
3377   I   0.255     0.190   0.070        0.0815          0.0280
3378   M   0.335     0.255   0.075        0.1635          0.0615
3379   I   0.295     0.210   0.080        0.1000          0.0380

      Viscera weight  Shell weight  Rings
3370          0.1065         0.135     12
3371          0.0340         0.055     10
3372          0.0905         0.195     16
3373          0.1940         0.290     19
3374          0.1715         0.155     10
3375          0.1805         0.125     10
3376          0.0310         0.040      6
3377          0.0160         0.031      5
3378          0.0345         0.057      8
3379          0.0260         0.031      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3380   I   0.190     0.130   0.045        0.0265          0.0090
3381   M   0.545     0.435   0.165        0.9955          0.3245
3382   M   0.495     0.400   0.120        0.6605          0.2605
3383   M   0.500     0.375   0.130        0.7210          0.3055
3384   F   0.305     0.225   0.070        0.1485          0.0585
3385   F   0.475     0.350   0.115        0.4870          0.1940
3386   M   0.515     0.400   0.125        0.9550          0.3410
3387   M   0.545     0.410   0.145        0.8730          0.3035
3388   M   0.740     0.535   0.185        1.6500          0.7340
3389   M   0.565     0.465   0.150        1.1285          0.3770

      Viscera weight  Shell weight  Rings
3380          0.0050         0.009      5
3381          0.2665         0.325     19
3382          0.1610         0.190     15
3383          0.1725         0.220     14
3384          0.0335         0.045      7
3385          0.1455         0.125     13
3386          0.2535         0.260     13
3387          0.1960         0.310     18
3388          0.4505         0.335     13
3389          0.3525         0.330     16
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3390   M   0.560     0.440   0.160        1.1115          0.5035
3391   M   0.545     0.420   0.125        0.9745          0.3530
3392   M   0.645     0.515   0.185        1.4605          0.5835
3393   M   0.575     0.435   0.130        1.0105          0.3680
3394   M   0.620     0.480   0.160        1.0765          0.4120
3395   F   0.605     0.450   0.165        1.2225          0.3570
3396   M   0.605     0.475   0.160        1.6160          0.5495
3397   F   0.475     0.375   0.150        0.5590          0.1955
3398   M   0.365     0.285   0.085        0.2205          0.0855
3399   F   0.460     0.350   0.115        0.4400          0.1900

      Viscera weight  Shell weight  Rings
3390          0.2785        0.2600     10
3391          0.1740        0.3050     13
3392          0.3155        0.4100     19
3393          0.2220        0.3200     10
3394          0.2530        0.3000     13
3395          0.2020        0.3850     13
3396          0.3320        0.3400     18
3397          0.1215        0.1945     12
3398          0.0515        0.0700      9
3399          0.1025        0.1300      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3400   M   0.530     0.430   0.135        0.8790          0.2800
3401   M   0.480     0.395   0.150        0.6815          0.2145
3402   M   0.455     0.345   0.150        0.5795          0.1685
3403   I   0.350     0.265   0.110        0.2090          0.0660
3404   M   0.370     0.280   0.105        0.2240          0.0815
3405   I   0.340     0.250   0.075        0.1765          0.0785
3406   I   0.350     0.280   0.075        0.1960          0.0820
3407   I   0.350     0.265   0.080        0.1920          0.0810
3408   I   0.390     0.315   0.090        0.3095          0.1470
3409   I   0.395     0.310   0.095        0.3130          0.1310

      Viscera weight  Shell weight  Rings
3400          0.2165        0.2500     10
3401          0.1405        0.2495     18
3402          0.1250        0.2150     13
3403          0.0590        0.0750      9
3404          0.0575        0.0750      8
3405          0.0405        0.0500      7
3406          0.0400        0.0640      8
3407          0.0465        0.0530      6
3408          0.0500        0.0900      7
3409          0.0720        0.0930      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3410   I   0.415     0.310   0.105        0.3595          0.1670
3411   I   0.430     0.320   0.100        0.3855          0.1920
3412   I   0.480     0.355   0.115        0.5785          0.2500
3413   M   0.490     0.395   0.120        0.6740          0.3325
3414   F   0.490     0.370   0.105        0.5265          0.2490
3415   F   0.560     0.465   0.160        1.0315          0.4320
3416   M   0.560     0.450   0.140        0.9000          0.4720
3417   M   0.580     0.460   0.150        1.0165          0.4910
3418   F   0.580     0.480   0.180        1.2495          0.4945
3419   M   0.590     0.470   0.135        1.1685          0.5390

      Viscera weight  Shell weight  Rings
3410          0.0830        0.0915      6
3411          0.0745        0.1000      7
3412          0.1060        0.1840      8
3413          0.1235        0.1850      9
3414          0.1005        0.1480      7
3415          0.2025        0.3370      9
3416          0.1820        0.2180      7
3417          0.2210        0.2650      9
3418          0.2700        0.3710      8
3419          0.2790        0.2800      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3420   F   0.595     0.475   0.165        1.1480          0.4440
3421   M   0.600     0.475   0.150        1.0890          0.5195
3422   M   0.610     0.470   0.155        1.0325          0.4970
3423   F   0.630     0.475   0.150        1.1720          0.5360
3424   M   0.640     0.510   0.170        1.3715          0.5670
3425   F   0.650     0.545   0.185        1.5055          0.6565
3426   M   0.710     0.550   0.200        1.9045          0.8820
3427   M   0.740     0.605   0.200        2.4925          1.1455
3428   I   0.250     0.180   0.065        0.0805          0.0345
3429   I   0.280     0.210   0.065        0.1110          0.0425

      Viscera weight  Shell weight  Rings
3420          0.2140        0.3700     10
3421          0.2230        0.2920     11
3422          0.2175        0.2785      9
3423          0.2540        0.3160     11
3424          0.3070        0.4090     10
3425          0.3410        0.4300     10
3426          0.4400        0.5000     13
3427          0.5750        0.5235     13
3428          0.0185        0.0215      4
3429          0.0285        0.0300      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3430   I   0.325     0.240   0.075        0.1520          0.0650
3431   I   0.350     0.265   0.095        0.1990          0.0730
3432   I   0.360     0.270   0.090        0.2190          0.0970
3433   I   0.365     0.270   0.105        0.2155          0.0915
3434   I   0.370     0.280   0.090        0.2565          0.1255
3435   I   0.375     0.285   0.090        0.2570          0.1045
3436   I   0.380     0.275   0.095        0.2505          0.0945
3437   I   0.395     0.300   0.090        0.2790          0.1340
3438   I   0.430     0.335   0.105        0.3780          0.1880
3439   I   0.440     0.350   0.125        0.4560          0.2100

      Viscera weight  Shell weight  Rings
3430          0.0305        0.0450      6
3431          0.0490        0.0600      5
3432          0.0405        0.0650      6
3433          0.0475        0.0630      6
3434          0.0645        0.0645      6
3435          0.0620        0.0750      7
3436          0.0655        0.0750      6
3437          0.0490        0.0750      8
3438          0.0785        0.0900      6
3439          0.0955        0.1310      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3440   I   0.465     0.370   0.100        0.5055          0.2340
3441   F   0.465     0.355   0.115        0.4705          0.1955
3442   M   0.480     0.370   0.130        0.6430          0.3490
3443   I   0.485     0.370   0.100        0.5130          0.2190
3444   F   0.490     0.400   0.115        0.5690          0.2560
3445   I   0.495     0.400   0.145        0.5780          0.2545
3446   I   0.500     0.385   0.110        0.5960          0.3015
3447   F   0.505     0.390   0.120        0.5725          0.2555
3448   M   0.520     0.390   0.120        0.6435          0.2885
3449   M   0.520     0.395   0.125        0.8115          0.4035

      Viscera weight  Shell weight  Rings
3440          0.1100        0.1400      7
3441          0.1180        0.1260      7
3442          0.1155        0.1350      8
3443          0.1075        0.1300      7
3444          0.1325        0.1450      9
3445          0.1305        0.1645      8
3446          0.1040        0.1510      8
3447          0.1325        0.1460      8
3448          0.1570        0.1610      7
3449          0.1660        0.2000      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3450   F   0.525     0.440   0.125        0.7115          0.3205
3451   M   0.550     0.440   0.155        0.9155          0.3645
3452   F   0.555     0.440   0.145        0.8815          0.4300
3453   F   0.555     0.420   0.110        0.9310          0.4445
3454   F   0.575     0.460   0.165        1.0650          0.4985
3455   M   0.600     0.475   0.155        1.1385          0.5020
3456   F   0.610     0.480   0.160        1.2340          0.5980
3457   F   0.610     0.495   0.175        1.2635          0.5300
3458   F   0.610     0.470   0.160        1.0745          0.4925
3459   M   0.615     0.505   0.190        1.4030          0.6715

      Viscera weight  Shell weight  Rings
3450          0.1590        0.1915      7
3451          0.1950        0.2500      8
3452          0.1975        0.2155      8
3453          0.1710        0.2250      8
3454          0.2145        0.2815      8
3455          0.2295        0.3100      9
3456          0.2380        0.3150     12
3457          0.3150        0.3455     10
3458          0.2360        0.2900      8
3459          0.2925        0.3650      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3460   M   0.620     0.485   0.165        1.1325          0.5235
3461   F   0.625     0.495   0.160        1.1115          0.4495
3462   F   0.625     0.470   0.170        1.2550          0.5250
3463   M   0.625     0.485   0.170        1.4370          0.5855
3464   M   0.635     0.495   0.155        1.3635          0.5830
3465   F   0.640     0.480   0.195        1.1435          0.4915
3466   M   0.640     0.500   0.170        1.4545          0.6420
3467   M   0.660     0.525   0.180        1.4780          0.5815
3468   F   0.665     0.520   0.165        1.6885          0.7295
3469   F   0.715     0.585   0.230        2.0725          0.8655

      Viscera weight  Shell weight  Rings
3460          0.2505        0.2825      9
3461          0.2825        0.3450     11
3462          0.2415        0.4050     10
3463          0.2930        0.4750     11
3464          0.2985        0.2950     10
3465          0.2345        0.3530      9
3466          0.3575        0.3540      9
3467          0.3810        0.3720     10
3468          0.4070        0.4265     11
3469          0.4095        0.5650     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3470   M   0.720     0.565   0.200        1.7870          0.7180
3471   F   0.725     0.580   0.185        1.5230          0.8045
3472   I   0.165     0.120   0.050        0.0210          0.0075
3473   I   0.210     0.150   0.055        0.0455          0.0200
3474   I   0.355     0.265   0.085        0.2435          0.1220
3475   I   0.400     0.315   0.085        0.2675          0.1160
3476   I   0.400     0.290   0.100        0.2580          0.1040
3477   I   0.400     0.300   0.110        0.2985          0.1375
3478   I   0.435     0.335   0.110        0.4110          0.2025
3479   I   0.440     0.330   0.110        0.3800          0.1970

      Viscera weight  Shell weight  Rings
3470          0.3850        0.5290     11
3471          0.3595        0.4375      9
3472          0.0045        0.0140      3
3473          0.0065        0.0130      4
3474          0.0525        0.0600      6
3475          0.0585        0.0765      6
3476          0.0590        0.0815      7
3477          0.0710        0.0750      6
3478          0.0945        0.1000      7
3479          0.0790        0.0900      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3480   I   0.450     0.340   0.105        0.4385          0.2100
3481   I   0.465     0.345   0.105        0.4015          0.2420
3482   I   0.470     0.355   0.145        0.4485          0.1560
3483   I   0.470     0.355   0.115        0.4155          0.1670
3484   I   0.475     0.420   0.160        0.7095          0.3500
3485   I   0.485     0.370   0.115        0.6370          0.3800
3486   F   0.505     0.475   0.160        1.1155          0.5090
3487   I   0.510     0.405   0.130        0.5990          0.3065
3488   I   0.520     0.380   0.130        0.5345          0.2375
3489   F   0.530     0.420   0.140        0.6270          0.2905

      Viscera weight  Shell weight  Rings
3480          0.0925        0.1200      8
3481          0.0345        0.1090      6
3482          0.1020        0.1230      7
3483          0.0840        0.1390      7
3484          0.1505        0.1845      8
3485          0.1335        0.1280      7
3486          0.2390        0.3065      8
3487          0.1155        0.1485      8
3488          0.1220        0.1535      8
3489          0.1165        0.1830      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3490   M   0.535     0.420   0.160        0.7465          0.3480
3491   M   0.550     0.440   0.160        0.9850          0.4645
3492   M   0.555     0.440   0.145        0.8500          0.4165
3493   M   0.555     0.440   0.150        0.8380          0.4155
3494   F   0.555     0.430   0.135        0.8120          0.4055
3495   M   0.560     0.415   0.130        0.7615          0.3695
3496   M   0.575     0.440   0.145        0.8700          0.3945
3497   F   0.585     0.450   0.145        0.9835          0.4845
3498   M   0.590     0.460   0.145        0.9290          0.3800
3499   F   0.595     0.470   0.165        1.0155          0.4910

      Viscera weight  Shell weight  Rings
3490          0.1515        0.2185     10
3491          0.2010        0.2700      8
3492          0.1685        0.2300      8
3493          0.1460        0.2300      8

(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3660   F   0.545     0.410   0.125        0.6540          0.2945
3661   I   0.550     0.415   0.150        0.7915          0.3535
3662   I   0.550     0.450   0.140        0.7530          0.3445
3663   I   0.550     0.400   0.135        0.7170          0.3315
3664   I   0.555     0.430   0.150        0.7830          0.3450
3665   I   0.575     0.450   0.145        0.8720          0.4675
3666   I   0.575     0.440   0.150        0.9830          0.4860
3667   F   0.585     0.420   0.155        1.0340          0.4370
3668   F   0.585     0.465   0.145        0.9855          0.4325
3669   I   0.585     0.460   0.140        0.7635          0.3260

      Viscera weight  Shell weight  Rings
3660          0.1315        0.2050     10
3661          0.1760        0.2360     10
3662          0.1325        0.2400      8
3663          0.1495        0.2210      9
3664          0.1755        0.2470      9
3665          0.1800        0.2170      9
3666          0.2150        0.2390      8
3667          0.2225        0.3200     11
3668          0.2145        0.2845     10
3669          0.1530        0.2650      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3670   M   0.590     0.465   0.135        0.9895          0.4235
3671   I   0.595     0.470   0.135        0.9365          0.4340
3672   F   0.595     0.440   0.135        0.9640          0.5005
3673   F   0.595     0.460   0.155        1.0455          0.4565
3674   F   0.595     0.450   0.165        1.0810          0.4900
3675   M   0.600     0.470   0.160        1.0120          0.4410
3676   F   0.600     0.500   0.160        1.1220          0.5095
3677   M   0.605     0.490   0.165        1.1245          0.4920
3678   F   0.605     0.490   0.150        1.1345          0.4305
3679   M   0.610     0.450   0.190        1.0805          0.5170

      Viscera weight  Shell weight  Rings
3670          0.1990        0.2800      8
3671          0.1840        0.2870     10
3672          0.1715        0.2575     10
3673          0.2400        0.3085     10
3674          0.2525        0.2790     12
3675          0.2015        0.3050     10
3676          0.2560        0.3090     10
3677          0.2220        0.3555     11
3678          0.2525        0.3500     10
3679          0.2495        0.2935     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3680   F   0.610     0.495   0.165        1.0835          0.4525
3681   M   0.615     0.470   0.175        1.2420          0.5675
3682   M   0.620     0.500   0.180        1.3915          0.7260
3683   M   0.620     0.525   0.155        1.0850          0.4540
3684   I   0.620     0.470   0.155        0.9660          0.4470
3685   M   0.620     0.480   0.165        1.0855          0.4810
3686   F   0.625     0.485   0.135        1.3025          0.6100
3687   I   0.625     0.485   0.160        1.1500          0.5255
3688   I   0.630     0.490   0.170        1.2170          0.5515
3689   F   0.630     0.505   0.195        1.3060          0.5160

      Viscera weight  Shell weight  Rings
3680          0.2730        0.3170      9
3681          0.2870        0.3170     11
3682          0.2795        0.3320     11
3683          0.1965        0.3500     10
3684          0.1710        0.2840     11
3685          0.2575        0.3050     10
3686          0.2675        0.3605     14
3687          0.2570        0.3315     11
3688          0.2120        0.3100     11
3689          0.3305        0.3750      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3690   M   0.640     0.500   0.175        1.2730          0.5065
3691   M   0.645     0.510   0.190        1.4865          0.6445
3692   M   0.650     0.520   0.170        1.3655          0.6155
3693   M   0.650     0.495   0.170        1.2760          0.6215
3694   M   0.650     0.495   0.160        1.2075          0.5500
3695   F   0.650     0.520   0.195        1.2810          0.5985
3696   M   0.650     0.525   0.205        1.4275          0.6900
3697   M   0.650     0.510   0.175        1.1550          0.4955
3698   F   0.650     0.510   0.175        1.3500          0.5750
3699   M   0.650     0.525   0.190        1.3685          0.5975

      Viscera weight  Shell weight  Rings
3690          0.2925        0.4050     13
3691          0.2960        0.4250     12
3692          0.2885        0.3600     11
3693          0.2305        0.3990     11
3694          0.2695        0.3200     10
3695          0.2460        0.3825     10
3696          0.3060        0.4355     13
3697          0.2025        0.3850     12
3698          0.3155        0.3885     10
3699          0.2960        0.4000     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3700   F   0.660     0.530   0.170        1.4310          0.6220
3701   M   0.660     0.510   0.180        1.2610          0.5000
3702   F   0.665     0.540   0.195        1.7640          0.8505
3703   F   0.670     0.510   0.155        1.2780          0.5605
3704   M   0.670     0.540   0.195        1.2170          0.5320
3705   F   0.670     0.540   0.200        1.4600          0.6435
3706   F   0.675     0.535   0.185        1.5575          0.7035
3707   M   0.675     0.510   0.170        1.5270          0.8090
3708   F   0.675     0.530   0.195        1.4985          0.6200
3709   M   0.685     0.550   0.190        1.8850          0.8900

      Viscera weight  Shell weight  Rings
3700          0.3090        0.3980     10
3701          0.2335        0.3390     10
3702          0.3615        0.4700     11
3703          0.3045        0.3580     11
3704          0.2735        0.3315     11
3705          0.3280        0.4165      9
3706          0.4020        0.4000     11
3707          0.3180        0.3410     11
3708          0.3750        0.4250      9
3709          0.4100        0.4895     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3710   M   0.685     0.535   0.175        1.4320          0.6370
3711   M   0.705     0.550   0.210        1.4385          0.6550
3712   F   0.705     0.530   0.170        1.5640          0.6120
3713   M   0.710     0.555   0.175        2.1400          1.2455
3714   F   0.725     0.560   0.185        1.7920          0.8730
3715   M   0.780     0.600   0.210        2.5480          1.1945
3716   I   0.235     0.130   0.075        0.1585          0.0685
3717   I   0.350     0.250   0.100        0.4015          0.1725
3718   I   0.360     0.250   0.115        0.4650          0.2100
3719   I   0.380     0.280   0.095        0.2885          0.1650

      Viscera weight  Shell weight  Rings
3710          0.2470        0.4600     11
3711          0.3255        0.4620     11
3712          0.3940        0.4400     10
3713          0.3725        0.4340     11
3714          0.3670        0.4350     11
3715          0.5745        0.6745     11
3716          0.0370        0.0465      5
3717          0.0630        0.1255      7
3718          0.1055        0.1280      7
3719          0.0435        0.0670      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3720   F   0.380     0.320   0.115        0.6475          0.3230
3721   M   0.430     0.310   0.130        0.6485          0.2735
3722   I   0.465     0.360   0.105        0.4520          0.2200
3723   I   0.470     0.355   0.120        0.4915          0.1765
3724   F   0.485     0.365   0.150        0.9145          0.4145
3725   M   0.495     0.375   0.155        0.9760          0.4500
3726   I   0.500     0.395   0.145        0.7865          0.3320
3727   M   0.505     0.400   0.150        0.7750          0.3445
3728   I   0.510     0.375   0.150        0.8415          0.3845
3729   M   0.510     0.380   0.135        0.6810          0.3435

      Viscera weight  Shell weight  Rings
3720          0.1325        0.1640      7
3721          0.1630        0.1840      9
3722          0.1590        0.1035      9
3723          0.1125        0.1325      9
3724          0.1990        0.2730      7
3725          0.2285        0.2475      9
3726          0.1815        0.2455      8
3727          0.1570        0.1850      7
3728          0.1560        0.2550     10
3729          0.1420        0.1700      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3730   M   0.515     0.370   0.115        0.6145          0.3415
3731   F   0.550     0.415   0.180        1.1655          0.5020
3732   F   0.575     0.420   0.190        1.7640          0.9140
3733   M   0.605     0.455   0.160        1.1215          0.5330
3734   M   0.615     0.505   0.165        1.1670          0.4895
3735   M   0.615     0.475   0.150        1.0375          0.4760
3736   M   0.625     0.480   0.180        1.2230          0.5650
3737   M   0.625     0.470   0.150        1.1240          0.5560
3738   F   0.635     0.505   0.170        1.2635          0.5120
3739   F   0.650     0.525   0.165        1.2380          0.6470

      Viscera weight  Shell weight  Rings
3730          0.1550        0.1460      9
3731          0.3010        0.3110      9
3732          0.3770        0.4095     10
3733          0.2730        0.2710     10
3734          0.2955        0.3450     10
3735          0.2325        0.2830      9
3736          0.2975        0.3375     10
3737          0.2315        0.2870      9
3738          0.3220        0.3550      9
3739          0.2485        0.3005      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3740   F   0.650     0.500   0.170        1.4045          0.6940
3741   F   0.670     0.525   0.195        1.3700          0.6065
3742   F   0.695     0.525   0.205        1.8185          0.8190
3743   F   0.705     0.555   0.195        1.7525          0.7105
3744   I   0.275     0.205   0.065        0.1010          0.0410
3745   I   0.285     0.205   0.070        0.1060          0.0390
3746   I   0.360     0.265   0.085        0.1865          0.0675
3747   I   0.385     0.290   0.100        0.2575          0.1000
3748   I   0.400     0.315   0.100        0.3225          0.1430
3749   I   0.430     0.330   0.095        0.3200          0.1180

      Viscera weight  Shell weight  Rings
3740          0.3180        0.3235     11
3741          0.2955        0.4070     12
3742          0.4025        0.4525     13
3743          0.4215        0.5160     12
3744          0.0210        0.0340      5
3745          0.0285        0.0340      5
3746          0.0370        0.0615      7
3747          0.0610        0.0860      6
3748          0.0735        0.0910      6
3749          0.0650        0.1230      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3750   I   0.435     0.375   0.110        0.4155          0.1700
3751   I   0.450     0.335   0.115        0.3935          0.1950
3752   I   0.475     0.355   0.135        0.4775          0.2145
3753   I   0.475     0.360   0.110        0.4520          0.1910
3754   I   0.485     0.370   0.140        0.5065          0.2425
3755   I   0.510     0.395   0.105        0.5525          0.2340
3756   I   0.515     0.390   0.120        0.5650          0.2350
3757   I   0.520     0.410   0.140        0.6990          0.3395
3758   I   0.525     0.400   0.140        0.6055          0.2605
3759   M   0.530     0.425   0.155        0.7905          0.3070

      Viscera weight  Shell weight  Rings
3750           0.076        0.1450      8
3751           0.071        0.1100      7
3752           0.090        0.1435      8
3753           0.099        0.1300      8
3754           0.088        0.1465      8
3755           0.127        0.1650      8
3756           0.135        0.1790      9
3757           0.129        0.1945     10
3758           0.108        0.2100      9
3759           0.171        0.2595      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3760   M   0.530     0.425   0.130        0.7020          0.2975
3761   M   0.530     0.420   0.135        0.6750          0.2940
3762   I   0.530     0.395   0.115        0.4750          0.2025
3763   I   0.530     0.410   0.150        0.6120          0.2435
3764   I   0.535     0.400   0.145        0.7050          0.3065
3765   I   0.535     0.450   0.135        0.7280          0.2845
3766   F   0.555     0.440   0.140        0.8460          0.3460
3767   M   0.555     0.460   0.160        0.8600          0.3345
3768   M   0.560     0.465   0.145        0.8875          0.3345
3769   F   0.560     0.430   0.145        0.8980          0.3895

      Viscera weight  Shell weight  Rings
3760          0.1395        0.2200      9
3761          0.1560        0.1825     10
3762          0.1010        0.1480      8
3763          0.1525        0.1895     11
3764          0.1365        0.2200     10
3765          0.1845        0.2650      9
3766          0.1715        0.2735     10
3767          0.1935        0.2750     10
3768          0.2200        0.2695      9
3769          0.2325        0.2450      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3770   I   0.565     0.430   0.125        0.6545          0.2815
3771   I   0.575     0.450   0.145        0.7950          0.3640
3772   M   0.575     0.465   0.120        1.0535          0.5160
3773   F   0.575     0.460   0.150        0.9270          0.3330
3774   I   0.580     0.420   0.140        0.7010          0.3285
3775   M   0.580     0.450   0.155        0.8275          0.3210
3776   F   0.585     0.420   0.155        0.9845          0.4420
3777   M   0.585     0.470   0.145        0.9565          0.4025
3778   I   0.590     0.450   0.125        0.8600          0.4370
3779   M   0.595     0.480   0.185        1.1785          0.5260

      Viscera weight  Shell weight  Rings
3770          0.1390        0.2100      9
3771          0.1505        0.2600     10
3772          0.2185        0.2350      9
3773          0.2070        0.2985      9
3774          0.1020        0.2255      9
3775          0.1975        0.2445      8
3776          0.2155        0.2875     13
3777          0.2365        0.2650      9
3778          0.1515        0.2450      9
3779          0.2975        0.3140     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3780   M   0.615     0.480   0.185        1.2205          0.4985
3781   M   0.615     0.455   0.130        0.9685          0.4900
3782   F   0.620     0.500   0.175        1.1070          0.4895
3783   I   0.620     0.480   0.180        1.1305          0.5285
3784   M   0.620     0.480   0.155        1.2555          0.5270
3785   M   0.625     0.495   0.155        1.1770          0.5055
3786   M   0.625     0.500   0.185        1.2425          0.5995
3787   M   0.630     0.490   0.160        1.0900          0.4070
3788   F   0.630     0.475   0.150        1.0720          0.4330
3789   F   0.645     0.510   0.155        1.1290          0.5015

      Viscera weight  Shell weight  Rings
3780          0.3150        0.3300     10
3781          0.1820        0.2655     10
3782          0.2400        0.3430     11
3783          0.2655        0.3060     12
3784          0.3740        0.3175     11
3785          0.2780        0.3450      9
3786          0.2480        0.3350     10
3787          0.2240        0.3540     12
3788          0.2975        0.3150      8
3789          0.2400        0.3420     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3790   F   0.650     0.505   0.175        1.2075          0.5105
3791   F   0.650     0.495   0.175        1.2270          0.5280
3792   F   0.655     0.520   0.175        1.4720          0.6275
3793   F   0.665     0.525   0.180        1.5785          0.6780
3794   M   0.670     0.520   0.175        1.4755          0.6275
3795   M   0.675     0.540   0.175        1.5545          0.6645
3796   F   0.675     0.540   0.210        1.5930          0.6860
3797   M   0.695     0.580   0.200        1.8995          0.6750
3798   F   0.695     0.535   0.175        1.3610          0.5465
3799   F   0.705     0.560   0.170        1.4575          0.6070

      Viscera weight  Shell weight  Rings
3790          0.2620        0.3900     10
3791          0.2580        0.3700     11
3792          0.2700        0.4500     13
3793          0.2290        0.4560     14
3794          0.3790        0.3740     10
3795          0.2780        0.5120     12
3796          0.3180        0.4500     11
3797          0.4780        0.5295     13
3798          0.2815        0.4650     10
3799          0.3180        0.4400     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3800   M   0.740     0.580   0.205        2.3810          0.8155
3801   I   0.205     0.155   0.045        0.0495          0.0235
3802   I   0.305     0.230   0.075        0.1455          0.0595
3803   I   0.320     0.230   0.060        0.1290          0.0615
3804   I   0.355     0.270   0.100        0.2255          0.1100
3805   M   0.425     0.305   0.110        0.3590          0.1730
3806   I   0.425     0.310   0.095        0.3505          0.1645
3807   F   0.450     0.365   0.115        0.5885          0.3180
3808   M   0.515     0.385   0.130        0.6230          0.2855
3809   F   0.520     0.375   0.135        0.5375          0.2210

      Viscera weight  Shell weight  Rings
3800          0.4695        0.4880     12
3801          0.0110        0.0140      3
3802          0.0305        0.0500      6
3803          0.0275        0.0355      7
3804          0.0420        0.0640      7
3805          0.0875        0.0975      9
3806          0.0710        0.1000      8
3807          0.1210        0.1325      8
3808          0.1285        0.1750     10
3809          0.1170        0.1700      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3810   I   0.525     0.400   0.125        0.5655          0.2435
3811   M   0.555     0.445   0.130        0.8625          0.4225
3812   F   0.610     0.490   0.170        1.1370          0.4605
3813   I   0.350     0.260   0.095        0.2210          0.0985
3814   I   0.380     0.275   0.095        0.2425          0.1060
3815   I   0.460     0.340   0.100        0.3860          0.1805
3816   M   0.465     0.355   0.120        0.5315          0.2725
3817   M   0.475     0.385   0.120        0.5620          0.2890
3818   M   0.565     0.445   0.140        0.8360          0.4060
3819   M   0.570     0.450   0.140        0.9275          0.4770

      Viscera weight  Shell weight  Rings
3810          0.1190        0.1750      8
3811          0.1550        0.2400      9
3812          0.2825        0.3440     12
3813          0.0430        0.0700      8
3814          0.0485        0.2100      6
3815          0.0875        0.0965      8
3816          0.0970        0.1395      8
3817          0.0905        0.1530      8
3818          0.1605        0.2245      9
3819          0.1605        0.2515      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3820   M   0.570     0.440   0.145        0.8815          0.3605
3821   M   0.595     0.460   0.155        1.0300          0.4275
3822   F   0.605     0.480   0.175        1.1685          0.4815
3823   F   0.615     0.455   0.135        1.0590          0.4735
3824   M   0.620     0.460   0.170        1.1270          0.5350
3825   M   0.625     0.470   0.170        1.1665          0.4605
3826   F   0.680     0.520   0.185        1.5410          0.5985
3827   M   0.680     0.540   0.195        1.7825          0.5565
3828   M   0.680     0.520   0.175        1.5430          0.7525
3829   F   0.710     0.555   0.170        1.4700          0.5375

      Viscera weight  Shell weight  Rings
3820          0.1955        0.2735     10
3821          0.2070        0.3305     10
3822          0.2305        0.3560      9
3823          0.2630        0.2740      9

(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4010   M   0.610     0.475   0.150        1.1420          0.6200
4011   M   0.615     0.530   0.170        1.1200          0.5775
4012   F   0.620     0.465   0.140        1.0110          0.4790
4013   M   0.625     0.505   0.175        1.1310          0.5425
4014   M   0.625     0.480   0.175        1.0650          0.4865
4015   M   0.635     0.480   0.145        1.1810          0.6650
4016   F   0.640     0.525   0.175        1.3820          0.6460
4017   M   0.660     0.505   0.190        1.4385          0.6775
4018   M   0.660     0.485   0.155        1.2275          0.6100
4019   M   0.660     0.515   0.155        1.4415          0.7055

      Viscera weight  Shell weight  Rings
4010          0.2370         0.245      9
4011          0.2095         0.286      9
4012          0.2385         0.255      8
4013          0.2265         0.323      8
4014          0.2590         0.285     10
4015          0.2290         0.225     10
4016          0.3115         0.370      9
4017          0.2850         0.178     11
4018          0.2740         0.300      8
4019          0.3555         0.335     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4020   F   0.680     0.550   0.175        1.4730          0.7130
4021   F   0.690     0.580   0.195        1.6580          0.7080
4022   M   0.720     0.545   0.195        1.7475          0.8215
4023   I   0.275     0.200   0.070        0.0960          0.0370
4024   I   0.330     0.245   0.065        0.1445          0.0580
4025   I   0.330     0.260   0.085        0.1965          0.0915
4026   I   0.365     0.280   0.090        0.1960          0.0865
4027   I   0.365     0.270   0.090        0.2155          0.1005
4028   I   0.420     0.310   0.100        0.2805          0.1125
4029   I   0.435     0.335   0.110        0.3340          0.1355

      Viscera weight  Shell weight  Rings
4020          0.2820        0.4295     11
4021          0.3615        0.4715     10
4022          0.3830        0.4705     11
4023          0.0225        0.0300      6
4024          0.0320        0.0505      6
4025          0.0425        0.0550      7
4026          0.0360        0.0605      7
4027          0.0490        0.0655      6
4028          0.0615        0.0925      8
4029          0.0775        0.0965      7
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4030   I   0.435     0.325   0.100        0.3660          0.1740
4031   I   0.440     0.325   0.110        0.4965          0.2580
4032   I   0.485     0.365   0.090        0.6510          0.3165
4033   I   0.495     0.385   0.125        0.5125          0.2075
4034   M   0.510     0.405   0.125        0.6925          0.3270
4035   I   0.520     0.410   0.140        0.5995          0.2420
4036   I   0.540     0.420   0.140        0.7400          0.3595
4037   I   0.540     0.415   0.155        0.7020          0.3220
4038   I   0.550     0.445   0.125        0.6720          0.2880
4039   I   0.560     0.440   0.155        0.8110          0.3685

      Viscera weight  Shell weight  Rings
4030          0.0725        0.1090      7
4031          0.1195        0.1075      8
4032          0.1320        0.1800      8
4033          0.1155        0.1720     10
4034          0.1550        0.1805      7
4035          0.1375        0.1820     11
4036          0.1590        0.1985      8
4037          0.1670        0.1900     10
4038          0.1365        0.2100     11
4039          0.1780        0.2350     11
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4040   F   0.575     0.450   0.120        0.9585          0.4470
4041   I   0.575     0.450   0.150        0.8580          0.4490
4042   F   0.575     0.460   0.165        0.9575          0.4815
4043   F   0.580     0.460   0.135        0.9260          0.4025
4044   F   0.580     0.425   0.155        0.8730          0.3615
4045   M   0.590     0.450   0.160        0.9980          0.4450
4046   M   0.600     0.460   0.155        0.6655          0.2850
4047   M   0.620     0.485   0.145        1.0030          0.4655
4048   F   0.625     0.495   0.160        1.2340          0.6335
4049   M   0.625     0.495   0.155        1.0250          0.4600

      Viscera weight  Shell weight  Rings
4040          0.1690         0.275     12
4041          0.1660         0.215     10
4042          0.1945         0.236     10
4043          0.2080         0.275      8
4044          0.2490         0.239     10
4045          0.2140         0.301      9
4046          0.1490         0.269     11
4047          0.2195         0.280     11
4048          0.1920         0.350     13
4049          0.1945         0.340      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4050   M   0.625     0.495   0.175        1.2935          0.5805
4051   M   0.625     0.500   0.175        1.0565          0.4615
4052   M   0.625     0.470   0.145        1.7855          0.6750
4053   F   0.625     0.485   0.165        1.2255          0.5075
4054   F   0.635     0.500   0.180        1.2565          0.5390
4055   F   0.645     0.500   0.150        1.1590          0.4675
4056   M   0.645     0.510   0.165        1.4030          0.5755
4057   F   0.690     0.535   0.185        1.8260          0.7970
4058   F   0.695     0.560   0.185        1.7715          0.8195
4059   M   0.515     0.390   0.120        0.6125          0.3020

      Viscera weight  Shell weight  Rings
4050          0.3170        0.3550      9
4051          0.2580        0.3050     10
4052          0.2470        0.3245     13
4053          0.2960        0.3600     10
4054          0.2920        0.3500     10
4055          0.3355        0.3100      9
4056          0.2515        0.4545     11
4057          0.4090        0.4990     11
4058          0.3310        0.4370     10
4059          0.1365        0.1415      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4060   I   0.545     0.405   0.130        0.6580          0.3270
4061   M   0.620     0.465   0.145        0.9110          0.3750
4062   M   0.630     0.490   0.150        1.1955          0.5845
4063   F   0.630     0.515   0.160        1.3360          0.5530
4064   F   0.640     0.490   0.180        1.3600          0.6530
4065   I   0.370     0.275   0.080        0.2325          0.0930
4066   I   0.395     0.310   0.085        0.3170          0.1530
4067   I   0.400     0.300   0.115        0.3180          0.1335
4068   I   0.410     0.305   0.100        0.2645          0.1000
4069   I   0.455     0.335   0.105        0.4055          0.1750

      Viscera weight  Shell weight  Rings
4060          0.1445        0.1740      8
4061          0.2145        0.2780     10
4062          0.2570        0.3000      9
4063          0.3205        0.3500     11
4064          0.3470        0.3050      9
4065          0.0560        0.0720      6
4066          0.0505        0.0935      7
4067          0.0725        0.0935      6
4068          0.0655        0.0850      7
4069          0.0920        0.1185      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4070   I   0.480     0.335   0.125        0.5240          0.2460
4071   I   0.485     0.375   0.110        0.4640          0.2015
4072   I   0.500     0.360   0.120        0.4390          0.1875
4073   I   0.515     0.395   0.125        0.5805          0.2365
4074   I   0.520     0.400   0.140        0.6220          0.2780
4075   M   0.545     0.450   0.150        0.7805          0.3795
4076   I   0.545     0.430   0.140        0.7720          0.2890
4077   I   0.550     0.435   0.125        0.7410          0.3480
4078   M   0.550     0.430   0.180        0.8265          0.4405
4079   M   0.550     0.385   0.130        0.7275          0.3430

      Viscera weight  Shell weight  Rings
4070          0.1095        0.1450      7
4071          0.0900        0.1490      8
4072          0.1055        0.1305      8
4073          0.1075        0.1900      9
4074          0.1455        0.1690      8
4075          0.1625        0.2160      8
4076          0.1900        0.2615      8
4077          0.1585        0.2060      9
4078          0.1590        0.2250     10
4079          0.1625        0.1900      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4080   I   0.555     0.430   0.125        0.7005          0.3395
4081   M   0.560     0.450   0.145        0.9355          0.4250
4082   I   0.565     0.465   0.150        1.1815          0.5810
4083   M   0.570     0.445   0.160        1.0145          0.5160
4084   F   0.575     0.480   0.170        1.1000          0.5060
4085   M   0.585     0.510   0.160        1.2180          0.6390
4086   M   0.590     0.450   0.155        0.8740          0.3690
4087   I   0.595     0.475   0.155        0.9840          0.4865
4088   M   0.600     0.470   0.130        1.0105          0.4230
4089   M   0.610     0.365   0.155        1.0765          0.4880

      Viscera weight  Shell weight  Rings
4080          0.1355        0.2095      8
4081          0.1645        0.2725     11
4082          0.2215        0.3095      9
4083          0.1640        0.3000     10
4084          0.2485        0.3100     10
4085          0.2410        0.3000     11
4086          0.2135        0.2400      8
4087          0.1840        0.2755     10
4088          0.2190        0.2980      9
4089          0.2490        0.2700      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4090   M   0.615     0.475   0.205        1.3370          0.5995
4091   M   0.625     0.500   0.180        1.3705          0.6450
4092   F   0.625     0.490   0.190        1.7015          0.7465
4093   M   0.630     0.485   0.180        1.2435          0.5175
4094   M   0.630     0.530   0.175        1.4135          0.6670
4095   F   0.635     0.485   0.155        1.0730          0.4670
4096   F   0.635     0.500   0.175        1.4770          0.6840
4097   M   0.635     0.500   0.180        1.2915          0.5940
4098   F   0.650     0.495   0.160        1.3105          0.5770
4099   M   0.670     0.525   0.180        1.4915          0.7280

      Viscera weight  Shell weight  Rings
4090          0.2815        0.3700     11
4091          0.3030        0.3705     12
4092          0.4105        0.3855     11
4093          0.3080        0.3700     11
4094          0.2945        0.3555     13
4095          0.1975        0.3500     11
4096          0.3005        0.3900     12
4097          0.2695        0.3700      9
4098          0.3315        0.3550      9
4099          0.3430        0.3810      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4100   F   0.675     0.520   0.175        1.4940          0.7365
4101   F   0.675     0.510   0.150        1.1965          0.4750
4102   M   0.680     0.545   0.185        1.6720          0.7075
4103   M   0.700     0.545   0.215        1.9125          0.8825
4104   F   0.710     0.545   0.175        1.9070          0.8725
4105   F   0.715     0.565   0.180        1.7900          0.8440
4106   F   0.720     0.590   0.205        1.7495          0.7755
4107   I   0.420     0.305   0.100        0.3415          0.1645
4108   I   0.480     0.350   0.100        0.5190          0.2365
4109   M   0.480     0.365   0.130        0.5305          0.2405

      Viscera weight  Shell weight  Rings
4100          0.3055        0.3700      9
4101          0.3040        0.3860     11
4102          0.3640        0.4800     11
4103          0.4385        0.5060     10
4104          0.4565        0.4750     11
4105          0.3535        0.5385      9
4106          0.4225        0.4800     11
4107          0.0775        0.0860      7
4108          0.1275        0.1260      7
4109          0.1270        0.1390      8
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4110   M   0.510     0.410   0.155        1.2825          0.5690
4111   I   0.515     0.400   0.140        0.7165          0.3495
4112   F   0.560     0.420   0.180        1.6645          0.7755
4113   I   0.560     0.420   0.140        0.8370          0.4140
4114   F   0.570     0.450   0.150        0.9645          0.5310
4115   F   0.605     0.465   0.155        1.1000          0.5470
4116   M   0.625     0.480   0.160        1.2415          0.6575
4117   F   0.640     0.505   0.175        1.3185          0.6185
4118   M   0.650     0.525   0.185        1.3455          0.5860
4119   I   0.300     0.215   0.050        0.1185          0.0480

      Viscera weight  Shell weight  Rings
4110          0.2910        0.3795      9
4111          0.1595        0.1785      8
4112          0.3500        0.4525      9
4113          0.2140        0.2000      8
4114          0.1890        0.2090      9
4115          0.2665        0.2585     10
4116          0.2625        0.2785      9
4117          0.3020        0.3315      9
4118          0.2780        0.3865      9
4119          0.0225        0.0420      4
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4120   M   0.350     0.265   0.090        0.1970          0.0730
4121   I   0.455     0.350   0.130        0.4725          0.2150
4122   I   0.460     0.365   0.110        0.4495          0.1755
4123   I   0.490     0.375   0.115        0.5570          0.2275
4124   I   0.500     0.385   0.120        0.5160          0.1970
4125   I   0.540     0.415   0.135        0.7090          0.3195
4126   M   0.550     0.420   0.145        0.7385          0.3210
4127   I   0.550     0.445   0.110        0.7935          0.3780
4128   M   0.555     0.435   0.145        0.9205          0.4040
4129   I   0.570     0.425   0.140        0.7655          0.3310

      Viscera weight  Shell weight  Rings
4120          0.0365        0.0770      7
4121          0.0745        0.1500      9
4122          0.1020        0.1500      8
4123          0.1335        0.1765      8
4124          0.1305        0.1650      8
4125          0.1740        0.1850      9
4126          0.1485        0.2520     11
4127          0.1420        0.2600     10
4128          0.2275        0.2550      8
4129          0.1400        0.2400     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4130   M   0.580     0.450   0.140        0.8240          0.3465
4131   I   0.580     0.425   0.145        0.8300          0.3790
4132   I   0.585     0.470   0.170        0.9850          0.3695
4133   M   0.585     0.450   0.150        0.9970          0.4055
4134   F   0.595     0.455   0.140        0.9140          0.3895
4135   F   0.600     0.500   0.170        1.1300          0.4405
4136   F   0.615     0.495   0.155        1.0805          0.5200
4137   M   0.630     0.505   0.155        1.1050          0.4920
4138   M   0.630     0.490   0.155        1.2290          0.5350
4139   F   0.635     0.495   0.175        1.2355          0.5205

      Viscera weight  Shell weight  Rings
4130          0.1765        0.2630     10
4131          0.1605        0.2575     11
4132          0.2395        0.3150     10
4133          0.2830        0.2510     11
4134          0.2225        0.2710      9
4135          0.2670        0.3350     11
4136          0.1900        0.3200      9
4137          0.2260        0.3250     11
4138          0.2900        0.3350     11
4139          0.3085        0.3470     10
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4140   F   0.645     0.535   0.190        1.2395          0.4680
4141   F   0.650     0.505   0.165        1.3570          0.5725
4142   M   0.655     0.525   0.180        1.4020          0.6240
4143   F   0.655     0.500   0.220        1.3590          0.6420
4144   M   0.670     0.535   0.190        1.6690          0.7465
4145   M   0.670     0.525   0.200        1.7405          0.6205
4146   M   0.695     0.530   0.210        1.5100          0.6640
4147   M   0.695     0.550   0.195        1.6645          0.7270
4148   M   0.770     0.605   0.175        2.0505          0.8005
4149   I   0.280     0.215   0.070        0.1240          0.0630

      Viscera weight  Shell weight  Rings
4140          0.2385         0.424     10
4141          0.2810         0.430     11
4142          0.2935         0.365     13
4143          0.3255         0.405     13
4144          0.2935         0.508     11
4145          0.2970         0.657     11
4146          0.4095         0.385     10
4147          0.3600         0.445     11
4148          0.5260         0.355     11
4149          0.0215         0.030      6
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4150   I   0.330     0.230   0.080        0.1400          0.0565
4151   I   0.350     0.250   0.075        0.1695          0.0835
4152   I   0.370     0.280   0.090        0.2180          0.0995
4153   I   0.430     0.315   0.115        0.3840          0.1885
4154   I   0.435     0.330   0.095        0.3930          0.2190
4155   I   0.440     0.350   0.110        0.3805          0.1575
4156   M   0.475     0.370   0.110        0.4895          0.2185
4157   M   0.475     0.360   0.140        0.5135          0.2410
4158   I   0.480     0.355   0.110        0.4495          0.2010
4159   F   0.560     0.440   0.135        0.8025          0.3500

      Viscera weight  Shell weight  Rings
4150          0.0365        0.0460      7
4151          0.0355        0.0410      6
4152          0.0545        0.0615      7
4153          0.0715        0.1100      8
4154          0.0750        0.0885      6
4155          0.0895        0.1150      6
4156          0.1070        0.1460      8
4157          0.1045        0.1550      8
4158          0.0890        0.1400      8
4159          0.1615        0.2590      9
(10, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4160   F   0.585     0.475   0.165        1.0530          0.4580
4161   F   0.585     0.455   0.170        0.9945          0.4255
4162   M   0.385     0.255   0.100        0.3175          0.1370
4163   I   0.390     0.310   0.085        0.3440          0.1810
4164   I   0.390     0.290   0.100        0.2845          0.1255
4165   I   0.405     0.300   0.085        0.3035          0.1500
4166   I   0.475     0.365   0.115        0.4990          0.2320
4167   M   0.500     0.380   0.125        0.5770          0.2690
4168   F   0.515     0.400   0.125        0.6150          0.2865
4169   M   0.520     0.385   0.165        0.7910          0.3750

      Viscera weight  Shell weight  Rings
4160          0.2170        0.3000     11
4161          0.2630        0.2845     11
4162          0.0680        0.0920      8
4163          0.0695        0.0790      7
4164          0.0635        0.0810      7
4165          0.0505        0.0880      7
4166          0.0885        0.1560     10
4167          0.1265        0.1535      9
4168          0.1230        0.1765      8
4169          0.1800        0.1815     10
(7, 9)
     Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4170   M   0.550     0.430   0.130        0.8395          0.3155
4171   M   0.560     0.430   0.155        0.8675          0.4000
4172   F   0.565     0.450   0.165        0.8870          0.3700
4173   M   0.590     0.440   0.135        0.9660          0.4390
4174   M   0.600     0.475   0.205        1.1760          0.5255
4175   F   0.625     0.485   0.150        1.0945          0.5310
4176   M   0.710     0.555   0.195        1.9485          0.9455

      Viscera weight  Shell weight  Rings
4170          0.1955        0.2405     10
4171          0.1720        0.2290      8
4172          0.2390        0.2490     11
4173          0.2145        0.2605     10
4174          0.2875        0.3080      9
4175          0.2610        0.2960     10
4176          0.3765        0.4950     12

In [45]:
'''
Load the dataset by specifically asking for an iterator of it. In this case, you can decide 
dynamically the length (that is, how many lines) you want for each piece of the pandas DataFrame. 
'''

abalone_iterator = pd.read_csv(abalone_p, sep=',', decimal='.', header=None, 
                               names=['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 
                                      'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings'],  
                               iterator=True)

## Read a piece of data with 10 lines.

In [46]:
# Please refer to: https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-chunking
abalone_iterator.get_chunk(10).shape

(10, 9)

## Read further 20 rows.

In [47]:
abalone_iterator.get_chunk(20).shape

(20, 9)

## Finally, read two further rows, save in a variable and print it.

In [48]:
piece = abalone_iterator.get_chunk(2)
print(piece)

   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
30   M    0.58      0.47   0.165        0.9975          0.3935
31   F    0.68      0.56   0.165        1.6390          0.6055

    Viscera weight  Shell weight  Rings
30          0.2420          0.33     10
31          0.2805          0.46     15